### ISSUE TITLE
[Question] API GW V2 metrics not found with dimensionNameRequirements

### ISSUE THREAD

**Issue by bogdankatishev** [nerdswords/yet-another-cloudwatch-exporter#1031]
Hello,

I have a question regarding the scraping of API GW V2 metrics. I noticed that the supporting PR was released in v0.52.0 for scraping API GW  V2 metrics (HTTP API).

We have this config block in our config.yaml:
```
      # API GW V1 (REST)
      # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html
      - <<: *default_job_config
        type: AWS/ApiGateway
        dimensionNameRequirements:
          - ApiName
          - Stage
        metrics:
          - name: Latency
            statistics: [ Average, Maximum, p95, p99 ]
          - name: Count
            statistics: [ SampleCount, Sum ]
          - name: 4XXError
            statistics: [ Sum, Average ]
          - name: 5XXError
            statistics: [ Sum, Average ]

      # API GW V2 (HTTP)
      # https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-metrics.html
      - <<: *default_job_config
        type: AWS/ApiGateway
        dimensionNameRequirements:
          - ApiId
          - Stage
          - Route
        metrics:
          - name: Latency
            statistics: [ Average, Maximum, p95, p99 ]
          - name: Count
            statistics: [ SampleCount, Sum ]
          - name: 4xx
            statistics: [ Sum ]
          - name: 5xx
            statistics: [ Sum ]
```

default_job_config has the values: 
```
default_job_config: &default_job_config
  addCloudwatchTimestamp: true
  roles:
    - <roles>
  regions:
    - eu-west-1
  period: 300
  length: 300
```

We are also using these feature flags: 
```
-enable-feature=aws-sdk-v2,max-dimensions-associator,list-metrics-callback
```

But we are getting these logs when running (multiple times):
```
{"account":"<account>","arn":"<role>","job_type":"AWS/ApiGateway","level":"info","msg":"No metrics data found","region":"eu-west-1","time":"2023-06-22T13:09:42Z"}
```

What are we doing wrong in our config.yaml?

**Comment by bogdankatishev** [comment]
Hello @ash-cohesity,

We also tried this without using `dimensionNameRequirements`. But we were still missing `4xx` and `5xx` metrics from API GW V2.

And we also do not want to use `searchTags` because we want to scrape all API GW's in that account.

**Comment by wimsymons** [comment]
#816 is a duplicate and there is a possible fix in #984

**Comment by cristiangreco** [comment]
> We also tried this without using `dimensionNameRequirements`. But we were still missing `4xx` and `5xx` metrics from API GW V2.

@bogdankatishev Are those metrics missing only from YACE, e.g. do you see those metrics in CloudWatch console? Note that some combination of dimensions require an additional setting to be enabled.

<img width="1160" alt="Screenshot 2023-06-27 at 11 13 32" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/316923/5dcfb1bc-ea7a-4163-adcd-8a94a0379198">

**Comment by bogdankatishev** [comment]
@cristiangreco Yes these metrics are only missing from YACE, we see them in the CloudWatch console. 
We are also aware that some combinations require an additional setting to be enabled. We have this setting enabled on the API GW.

**Comment by flomsk** [comment]
Also try to setup ApiGW metrics with `dimensionNameRequirements` , and also receive `msg":"skipping metric unmatched by associator`

No feature flag helped, neither `aws-sdk-v2` nor `max-dimensions-associator` nor both.

**Comment by cristiangreco** [comment]
@flomsk a debug log would help here, thanks!

**Comment by cristiangreco** [comment]
Thanks @flomsk, do you also have the part of the output relative to the GetTagging API request? Also, can you please provide examples of ARN names for your apigw resources? Thanks so much!

**Comment by cristiangreco** [comment]
@flomsk just by looking at the logs you pasted above, I would expect that by removing  `dimensionNameRequirements` you would still get the `4xx`  and `5xx` metrics with `ApiId` and `Stage` dimensions.

**Comment by flomsk** [comment]
hey @cristiangreco 
im not sure i took the correct one about GetTagging, is that what you need?
```
-----------------------------------------------------
2023/07/06 09:08:22 {"PaginationToken":"","ResourceTagMappingList":[{"ResourceARN":"arn:aws:apigateway:eu-west-1::/apis/xxxxxxxxxxx/stages/beta","Tags":[{"Key":"app","Value":"testapp"}]},{"ResourceARN":"arn:aws:apigateway:eu-west-1::/apis/xxxxxxxxxxx","Tags":[{"Key":"app","Value":"testapp"}]}]}
{"level":"debug","msg":"GetResourcesPages finished","time":"2023-07-06T09:08:22Z","total":2}
```

also removing `dimensionNameRequirements` giving me only one dimension `ApiId`
```
aws_apigateway_5xx_sum{account_id="123456789012",dimension_ApiId="xxxxxxxxxxx",name="arn:aws:apigateway:eu-west-1::/apis/xxxxxxxxxxx",region="eu-west-1"}
```

And also you can see ARN on the lines above

**Comment by cristiangreco** [comment]
I think this is kinda expected behaviour for the way the associator algorithm work -- basically it's not able to associate the metric with multiple dimensions (`ApiId`, `Stage`, `Resource`, `Method`) back to the ARN of the gw (which contains only the `ApiId` value). That's why you see only `ApiId` in the `4xx` and `5xx` metrics.

I don't think `dimensionNameRequirements` should be used here, it's pointless as it only filters metrics _after_ the associator.

I can try to think of ways to change the algorithm to account for cases like this, but don't have a way to easily test it at the moment as I don't have any apigateway resource.

**Comment by cristiangreco** [comment]
@flomsk are you able to test a custom branch or build? Would you please be able to let me know what happens with this PR? https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/1067

Please continue to use the `max-dimensions-associator` feature flag.

**Comment by bogdankatishev** [comment]
Hello @cristiangreco 

We have tested it again with the 0.53.0 release with the feature flag: `-enable-feature=max-dimensions-associator` but still no luck. These dimensions are missing as labels in the prometheus metrics: method, stage and resource when using the discovery job config.

When using customNamespace method to fetch ApiGateway metrics, we receive all the needed labels correctly (method, stage and resource):
```
customNamespace:
- addCloudwatchTimestamp: true
  regions:
  - eu-west-1
  period: 300
  length: 300
  name: temporary-apigateway
  namespace: AWS/ApiGateway
  metrics:
  - name: Latency
    statistics:
    - Average
    - Maximum
    - p95
    - p99
  - name: Count
    statistics:
    - SampleCount
    - Sum
  - name: 4xx
    statistics:
    - Sum
  - name: 4XXError
    statistics:
    - Sum
    - Average
  - name: 5xx
    statistics:
    - Sum
  - name: 5XXError
    statistics:
    - Sum
    - Average

```
```
aws_apigateway_4xx_sum{account_id="xxx", dimension_api_id="xxx", dimension_method="GET", dimension_resource="/path/of/resource", dimension_stage="$default", env="xxx", job="xxx", name="temporary-apigateway", region="eu-west-1"}
```

BUT, when using the discovery method to fetch ApiGateway metrics, we lose all those labels (method, stage and resource):
```
---
apiVersion: v1alpha1
discovery:
  jobs:
  - addCloudwatchTimestamp: true                  
    regions:                                      
    - eu-west-1                                   
    period: 300                                   
    length: 300                                   
    type: AWS/ApiGateway                          
    metrics:                                      
    - name: Latency                               
      statistics:                                 
      - Average                                   
      - Maximum                                   
      - p95                                       
      - p99                                       
    - name: Count                                 
      statistics:                                 
      - SampleCount                               
      - Sum                                       
    - name: 4xx                                   
      statistics:                                 
      - Sum                                       
    - name: 4XXError                              
      statistics:                                 
      - Sum                                       
      - Average                                   
    - name: 5xx                                   
      statistics:                                 
      - Sum                                       
    - name: 5XXError                              
      statistics:                                 
      - Sum                                       
      - Average  
```
```
aws_apigateway_4xx_sum{account_id="xxx", dimension_api_id="xxx", env="xxx", job="xxx", name="arn:aws:apigateway:eu-west-1::/apis/xxx", region="eu-west-1"}
```

**Note that we are not using: `dimensionNameRequirements` anymore :arrow_double_up:** 

We also did not test #1067 yet.

Debug output is also the same as @flomsk has pasted above already.
