### ISSUE TITLE
[BUG] "invalid memory address or nil pointer dereference" panic if nilToZero isn't included in static job config

### ISSUE THREAD

**Issue by zackelan** [nerdswords/yet-another-cloudwatch-exporter#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.52.0

### Config file

```
apiVersion: v1alpha1

static:
  - name: email
    namespace: AWS/SES
    regions:
      - us-west-2
    metrics:
      - name: Reputation.BounceRate
        statistics: [Average]
        period: 60
        length: 300
```

### Current Behavior

```
{"level":"info","msg":"Parsing config","time":"2023-06-26T20:57:59Z"}
{"level":"info","msg":"Yace startup completed","time":"2023-06-26T20:57:59Z","version":"0.52.0"}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e671e]

goroutine 10 [running]:
github.com/nerdswords/yet-another-cloudwatch-exporter/pkg/promutil.BuildMetrics({0xc0000120f0, 0x1, 0x0?}, 0x0?, {0x32e3640, 0xc000184e00})
        /github/workspace/pkg/promutil/migrate.go:73 +0x21e
github.com/nerdswords/yet-another-cloudwatch-exporter/pkg.UpdateMetrics({0x32e0728, 0xc0004e0aa0}, {0x32e3640, 0xc000184e00}, {{0xc000411c40, 0x8}, {0x0, 0x0}, {0x0, {0x0, ...}}, ...}, ...)
        /github/workspace/pkg/exporter.go:161 +0x23e
main.(*scraper).scrape(0xc0004ab7a0, {0x32e0728, 0xc0004e0aa0}, {0x32e3640?, 0xc000184e00}, {0x32e16a0, 0xc0004e0a50})
        /github/workspace/cmd/yace/scraper.go:73 +0x3f2
main.(*scraper).decoupled(0xc0004ab7a0, {0x32e0728?, 0xc0004e0aa0}, {0x32e3640, 0xc000184e00}, {0x32e16a0?, 0xc0004e0a50})
        /github/workspace/cmd/yace/scraper.go:39 +0xcf
created by main.startScraper
        /github/workspace/cmd/yace/main.go:209 +0x70c
```

### Expected Behavior

if I add `nilToZero` to the static job config with a value of either true or false, the metrics are scraped successfully

I'd expect it to either use a default value for that option, or to error out on startup and tell me I need to add that field to my config file.
