### ISSUE TITLE
[BUG] Missing dimension for Lambda?

### ISSUE THREAD

**Issue by 80kk** [nerdswords/yet-another-cloudwatch-exporter#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.52.0

### Config file

config: |-
  apiVersion: v1alpha1
  sts-region: eu-west-1
  discovery:
    jobs:
      - type: AWS/Lambda
        enableMetricData: true
        regions:
          - eu-west-1
        period: 300
        length: 300
        metrics:
          - name: Invocations
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Errors
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Duration
            statistics: [Average, Maximum, Minimum, p90]
            period: 300
            length: 3600

### Current Behavior

Missing `dimension_FunctionName` filter

### Expected Behavior

Get `dimension_FunctionName` to filter by Lambda name.

### Steps To Reproduce

I've deployed YACE for various of CloudWatch metrics including Lambda and I found that for some reason I can't filter by `dimension_FunctionName` like it is possible with other metrics  (dimension_xxx). I thought it is because of configuration above so I used snippet I found in examples but with no luck either:
```
config: |-
  apiVersion: v1alpha1
  sts-region: eu-west-1
  discovery:
    jobs:
      - type: AWS/Lambda
        regions:
          - eu-west-1
        period: 300
        length: 300
        metrics:
          - name: Invocations
            statistics: [Sum]
          - name: Errors
            statistics: [Sum]
          - name: Throttles
            statistics: [Sum]
          - name: Duration
            statistics: [Average, Maximum, Minimum, p90]
```

### Anything else?

Helm chart `0.21.0`

**Comment by cristiangreco** [comment]
@80kk can you run yace with `-debug` flag and paste the output here?

**Comment by 80kk** [comment]
> @80kk can you run yace with `-debug` flag and paste the output here?

Yeah,
```
{"level":"info","msg":"Parsing config","time":"2023-07-06T10:06:31Z"}
{"level":"info","msg":"Yace startup completed","time":"2023-07-06T10:06:31Z","version":"v0.52.0"}
{"level":"debug","msg":"Starting scraping async","time":"2023-07-06T10:06:31Z"}
2023/07/06 10:06:31 DEBUG: Request sts/AssumeRoleWithWebIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.284 (go1.20.5; linux; amd64)
Content-Length: 1211
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept-Encoding: gzip

Action=AssumeRoleWithWebIdentity&RoleArn=xxxRoleSessionName=xxx&Version=2011-06-15&WebIdentityToken=xxx>
-----------------------------------------------------
2023/07/06 10:06:31 DEBUG: Response sts/AssumeRoleWithWebIdentity Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 2274
Content-Type: text/xml
Date: Thu, 06 Jul 2023 10:06:30 GMT
X-Amzn-Requestid: xxx

-----------------------------------------------------
2023/07/06 10:06:31 <AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <AssumeRoleWithWebIdentityResult>
    <Audience>sts.amazonaws.com</Audience>
    <AssumedRoleUser>
      <AssumedRoleId>xxx</AssumedRoleId>
      <Arn>arn:aws:sts::xxx:assumed-role/cloudwatch/xxx</Arn>
    </AssumedRoleUser>
    <Provider>arn:aws:iam::xxx:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/xxx</Provider>
    <Credentials>
      <AccessKeyId>xxx</AccessKeyId>
      <SecretAccessKey>xxx</SecretAccessKey>
      <SessionToken>xxx>
      <Expiration>2023-07-06T11:06:31Z</Expiration>
    </Credentials>
    <SubjectFromWebIdentityToken>system:serviceaccount:xxx:grafana</SubjectFromWebIdentityToken>
  </AssumeRoleWithWebIdentityResult>
  <ResponseMetadata>
    <RequestId>xxx</RequestId>
  </ResponseMetadata>
</AssumeRoleWithWebIdentityResponse>
...
-----------------------------------------------------
2023/07/06 10:06:31 <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:sts::xxx:assumed-role/cloudwatch/xxx</Arn>
    <UserId>xxx:xxx</UserId>
    <Account>xxx</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>xxx</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>

{"account":"xxx","arn":"","job_type":"AWS/Lambda","level":"debug","msg":"Get tagged resources","region":"eu-west-1","time":"2023-07-06T10:06:31Z"}
2023/07/06 10:06:31 DEBUG: Response sts/GetCallerIdentity Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 455
Content-Type: text/xml
Date: Thu, 06 Jul 2023 10:06:30 GMT
X-Amzn-Requestid: xxx

{"ResourceTypeFilters":["lambda:function"],"ResourcesPerPage":100}
-----------------------------------------------------
2023/07/06 10:06:31 DEBUG: Request tagging/GetResources Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: tagging.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.284 (go1.20.5; linux; amd64)
Content-Length: 54
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230706/eu-west-1/tagging/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=xxx>
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20230706T100631Z
X-Amz-Security-Token: xxx
X-Amz-Target: ResourceGroupsTaggingAPI_20170126.GetResources
Accept-Encoding: gzip

-----------------------------------------------------
2023/07/06 10:06:31 {"PaginationToken":"","ResourceTagMappingList":[{"ResourceARN":"arn:aws:lambda:eu-west-1:xxx:function:datadog-forwarder-Forwarder-xxx","Tags":[{"Key":"aws:cloudformation:stack-name","Value":"datado>
{"level":"debug","msg":"GetResourcesPages finished","time":"2023-07-06T10:06:31Z","total":1}
{"account":"xxx","arn":"","job_type":"AWS/Lambda","level":"debug","map[FunctionName:map[datadog-forwarder-Forwarder-xxx:0xc000598410]]":"(MISSING)","msg":"associator","region":"eu-west-1","time":"2023-07-06T10:06:31Z"}
{"account":"xxx","arn":"","job_type":"AWS/Lambda","level":"debug","map[FunctionName:map[datadog-forwarder-Forwarder-xxx:0xc000598410]]":"(MISSING)","msg":"associator","region":"eu-west-1","time":"2023-07-06T10:06:31Z"}
{"input":"{\n  MetricName: \"Duration\",\n  Namespace: \"AWS/Lambda\"\n}","level":"debug","msg":"ListMetrics","time":"2023-07-06T10:06:31Z"}
{"account":"xxx","arn":"","job_type":"AWS/Lambda","level":"debug","map[FunctionName:map[datadog-forwarder-Forwarder-xxx:0xc000598410]]":"(MISSING)","msg":"associator","region":"eu-west-1","time":"2023-07-06T10:06:31Z"}
{"input":"{\n  MetricName: \"Errors\",\n  Namespace: \"AWS/Lambda\"\n}","level":"debug","msg":"ListMetrics","time":"2023-07-06T10:06:31Z"}
{"input":"{\n  MetricName: \"Invocations\",\n  Namespace: \"AWS/Lambda\"\n}","level":"debug","msg":"ListMetrics","time":"2023-07-06T10:06:31Z"}
2023/07/06 10:06:31 DEBUG: Request monitoring/ListMetrics Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: monitoring.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.284 (go1.20.5; linux; amd64)
Content-Length: 78
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230706/eu-west-1/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=xxx>
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20230706T100631Z
X-Amz-Security-Token: xxx
Accept-Encoding: gzip

Action=ListMetrics&MetricName=Errors&Namespace=AWS%2FLambda&Version=2010-08-01

-----------------------------------------------------
2023/07/06 10:06:31 DEBUG: Request monitoring/ListMetrics Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: monitoring.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.284 (go1.20.5; linux; amd64)
Content-Length: 80
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230706/eu-west-1/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=xxx>
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20230706T100631Z
X-Amz-Security-Token: xxx>
Accept-Encoding: gzip

Action=ListMetrics&MetricName=Duration&Namespace=AWS%2FLambda&Version=2010-08-01

-----------------------------------------------------
2023/07/06 10:06:31 DEBUG: Request monitoring/ListMetrics Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: monitoring.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.284 (go1.20.5; linux; amd64)
Content-Length: 83
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230706/eu-west-1/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=xxx>
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20230706T100631Z
X-Amz-Security-Token: xxx
Accept-Encoding: gzip

Action=ListMetrics&MetricName=Invocations&Namespace=AWS%2FLambda&Version=2010-08-01
-----------------------------------------------------
2023/07/06 10:06:31 DEBUG: Response tagging/GetResources Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 11829
Content-Type: application/x-amz-json-1.1
Date: Thu, 06 Jul 2023 10:06:30 GMT
X-Amzn-Requestid: xxx

-----------------------------------------------------
2023/07/06 10:06:31 <ListMetricsResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <ListMetricsResult>
    <Metrics>
      <member>
        <MetricName>Duration</MetricName>
        <Namespace>AWS/Lambda</Namespace>
        <Dimensions>
          <member>
            <Name>FunctionName</Name>
            <Value>xxx</Value>
          </member> 
          <member> 
            <Name>ExecutedVersion</Name>
            <Value>$LATEST</Value>
          </member>
          <member> 
            <Name>Resource</Name>
            <Value>xxx:$LATEST</Value>
          </member>
        </Dimensions>
      </member>
      <member>
        <MetricName>Duration</MetricName>
        <Namespace>AWS/Lambda</Namespace>
        <Dimensions>
          <member>  
            <Name>FunctionName</Name>
            <Value>xxx</Value>
          </member>
        </Dimensions>
      </member>
      <member> 
        <MetricName>Duration</MetricName>
        <Namespace>AWS/Lambda</Namespace>
        <Dimensions/>
      </member>
      <member>
        <MetricName>Duration</MetricName>
        <Namespace>AWS/Lambda</Namespace>
        <Dimensions>
          <member>
            <Name>FunctionName</Name>
            <Value>xxx</Value>
          </member>
          <member>
            <Name>Resource</Name>
            <Value>xxx:$LATEST</Value>
          </member>
        </Dimensions>
      </member>
    </Metrics>
  </ListMetricsResult>
  <ResponseMetadata>
    <RequestId>xxx</RequestId>
  </ResponseMetadata>
</ListMetricsResponse>

{"level":"debug","msg":"ListMetrics","output":[{"Dimensions":[{"Name":"CacheClusterId","Value":"xxx-001"}],"MetricName":"Evictions","Namespace":"AWS/ElastiCache"},{"Dimensions":[{"Name":"CacheClusterId","Valu>
{"level":"debug","msg":"ListMetrics","output":[{"Dimensions":[{"Name":"FunctionName","Value":"xxx"},{"Name":"ExecutedVersion","Value":"$LATEST"},{"Name":"Resource","Value":"xxx:$LATEST"}],"MetricNa>
{"account":"xxx,"arn":"","dimensions":"FunctionName=xxx,ExecutedVersion=$LATEST,Resource=xxx:$LATEST","job_type":"AWS/Lambda","level":"debug","metric":"Duration","msg":"skipping metric un>
{"account":"xxx","arn":"","dimensions":"FunctionName=xxx","job_type":"AWS/Lambda","level":"debug","metric":"Duration","msg":"skipping metric unmatched by associator","region":"eu-west-1","time":"2023-07-06T1>
{"account":"xxx","arn":"","dimensions":"FunctionName=xxx,Resource=xxx:$LATEST","job_type":"AWS/Lambda","level":"debug","metric":"Duration","msg":"skipping metric unmatched by associator",">
{"input":"{\n  MetricName: \"CacheHits\",\n  Namespace: \"AWS/ElastiCache\"\n}","level":"debug","msg":"ListMetrics","time":"2023-07-06T10:06:31Z"}
2023/07/06 10:06:31 DEBUG: Request monitoring/ListMetrics Details:
```

Not sure why it is mixed with Elasticache. But everything else except Lambda works.

My current config:
```
config: |-
  apiVersion: v1alpha1
  sts-region: eu-west-1
  discovery:
    jobs:
      - type: AWS/RDS
        regions:
          - eu-west-1
        metrics:
          - name: CPUUtilization
            statistics: [Maximum, Average]
            period: 300
            length: 3600
          - name: FreeableMemory
            statistics: [Average]
            period: 300
            length: 3600
          - name: FreeStorageSpace
            statistics: [Average]
            period: 300
            length: 3600
      - type: AWS/Lambda
        regions:
          - eu-west-1
        metrics:
          - name: Invocations
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Errors
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Duration
            statistics: [Average, Maximum]
            period: 300
            length: 3600
      - type: AWS/SQS
        regions:
          - eu-west-1
        metrics:
          - name: NumberOfEmptyReceives
            statistics: [Sum]
            period: 300
            length: 3600
          - name: ApproximateAgeOfOldestMessage
            statistics: [Maximum]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesVisible
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesNotVisible
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesDelayed
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: NumberOfMessagesSent
            statistics: [Sum]
            period: 300
            length: 3600
          - name: NumberOfMessagesReceived
            statistics: [Sum]
            period: 300
            length: 3600
          - name: SentMessageSize
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: NumberOfMessagesDeleted
            statistics: [Sum]
            period: 300
            length: 3600
      - type: AWS/ElastiCache
        regions:
          - eu-west-1
        metrics:
          - name: CPUUtilization
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: FreeableMemory
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NetworkBytesIn
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NetworkBytesOut
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CurrConnections
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NewConnections
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: SwapUsage
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: Evictions
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CacheHits
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CacheMisses
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
```
