### ISSUE TITLE
[BUG] Ghost stats in Grafana

### ISSUE THREAD

**Issue by 80kk** [nerdswords/yet-another-cloudwatch-exporter#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.52.0

### Config file

```
config: |-
  apiVersion: v1alpha1
  sts-region: eu-west-1
  discovery:
    jobs:
      - type: AWS/RDS
        regions:
          - eu-west-1
        metrics:
          - name: CPUUtilization
            statistics: [Maximum, Average]
            period: 300
            length: 3600
          - name: FreeableMemory
            statistics: [Average]
            period: 300
            length: 3600
          - name: FreeStorageSpace
            statistics: [Average]
            period: 300
            length: 3600
      - type: AWS/Lambda
        regions:
          - eu-west-1
        metrics:
          - name: Invocations
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Errors
            statistics: [Sum]
            period: 300
            length: 3600
          - name: Duration
            statistics: [Average, Maximum]
            period: 300
            length: 3600
      - type: AWS/SQS
        regions:
          - eu-west-1
        metrics:
          - name: NumberOfEmptyReceives
            statistics: [Sum]
            period: 300
            length: 3600
          - name: ApproximateAgeOfOldestMessage
            statistics: [Maximum]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesVisible
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesNotVisible
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesDelayed
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: NumberOfMessagesSent
            statistics: [Sum]
            period: 300
            length: 3600
          - name: NumberOfMessagesReceived
            statistics: [Sum]
            period: 300
            length: 3600
          - name: SentMessageSize
            statistics: [Sum, Average]
            period: 300
            length: 3600
          - name: NumberOfMessagesDeleted
            statistics: [Sum]
            period: 300
            length: 3600
      - type: AWS/ElastiCache
        regions:
          - eu-west-1
        metrics:
          - name: CPUUtilization
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: FreeableMemory
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NetworkBytesIn
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NetworkBytesOut
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CurrConnections
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: NewConnections
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: SwapUsage
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: Evictions
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CacheHits
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
          - name: CacheMisses
            statistics: [Sum, SampleCount, Minimum, Maximum, Average]
            period: 300
            length: 3600
```

### Current Behavior

When I go to Grafana and try to create either an alert or a graph I am seeing ghost stats: https://ibb.co/HFgntTw Thi is definitely not a Grafana issue as the original https://github.com/prometheus/cloudwatch_exporter is not doing that. I've also checked Grafana 9.x and 10.x both affected in the same way.

### Expected Behavior

Not show ghost stats

### Anything else?

I am migrating from https://github.com/prometheus/cloudwatch_exporter if that make any difference, but original one is not doing this.
