### ISSUE TITLE
[BUG] customTags not working?

### ISSUE THREAD

**Issue by 80kk** [nerdswords/yet-another-cloudwatch-exporter#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

`0.52`

### Config file

```
config: |-
  apiVersion: v1alpha1
  sts-region: eu-west-1
  discovery:
    jobs:
      - type: AWS/SQS
        regions:
          - eu-west-1
        customTags:
          - key: Tier
            value: gold
        metrics:
          - name: NumberOfEmptyReceives
            statistics: [Sum]
            period: 300
            length: 3600
          - name: ApproximateAgeOfOldestMessage
            statistics: [Maximum]
            period: 300
            length: 3600
          - name: ApproximateNumberOfMessagesVisible
            statistics: [Sum, Average]
            period: 300
            length: 3600
```

### Current Behavior

According to the config above I would imagine I could filter stats by these having particular tag confiugred in AWS. What happen is it shows all stats if I apply the `custom_tag_Tier` = `gold` and won't display any stats if I negate it using `=!`
Either I don't understand how this should work or it doesn't work as it mentioned to be.

### Expected Behavior

Filter metrics by tags.
