### ISSUE TITLE
Couldn't read /config/config.yml:Service is not in known list!: sns

### ISSUE THREAD

**Issue by mhernahapetyan** [nerdswords/yet-another-cloudwatch-exporter#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Config file

              # - type: "sns"
              #   region: us-west-2
              #   metrics:
              #     - name: NumberOfMessagesPublished
              #       statistics: [Sum]
              #       period: 300
              #       length: 300
              #     - name: NumberOfNotificationsDelivered
              #       statistics: [Sum]
              #       period: 300
              #       length: 300
              #     - name: NumberOfNotificationsFailed
              #       statistics: [Sum]
              #       period: 300
              #       length: 300
              #     - name: PublishSize
              #       statistics: [Average]
              #       period: 300
              #       length: 300
              #     - name: PublishLatency
              #       statistics: [Maximum]
              #       period: 300
              #       length: 300

### Current Behavior

Couldn't read /config/config.yml:Service is not in known list!: sns

**Comment by vainiusd** [comment]
Hi @mhernahapetyan,

Here is a valid config:
```
# yace verify-config --config.file sns.yml 
{"level":"info","msg":"Parsing config","time":"2023-07-21T13:13:39+02:00"}
{"level":"info","msg":"Config file is valid","path":"sns.yml","time":"2023-07-21T13:13:39+02:00"}
```
Config:
```
apiVersion: v1alpha1
discovery: 
  jobs: 
    - type: "sns"
      roles:
        - roleArn: "arn:aws:iam::12345678901234:role/test/role"
      period: 300
      length: 300
      delay: 120
      regions: 
        - us-west-2
      metrics:
        - name: NumberOfMessagesPublished
          statistics: [Sum]
          period: 300
          length: 300
        - name: NumberOfNotificationsDelivered
          statistics: [Sum]
          period: 300
          length: 300
        - name: NumberOfNotificationsFailed
          statistics: [Sum]
          period: 300
          length: 300
        - name: PublishSize
          statistics: [Average]
          period: 300
          length: 300
        - name: PublishLatency
          statistics: [Maximum]
          period: 300
          length: 300
```
