### ISSUE TITLE
[BUG] Missing data points for Lambda after scrape interval increased to 2 mins

### ISSUE THREAD

**Issue by azadsagar** [nerdswords/yet-another-cloudwatch-exporter#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.53.0

### Config file

```
      apiVersion: v1alpha1
      sts-region: us-east-1
      discovery:
        exportedTagsOnMetrics:
          lambda:
            - my_tags_here
        jobs:
          - type: lambda
            addCloudwatchTimestamp: true
            period: 60
            length: 360
            delay: 180
            regions:
              - us-east-1
            roles:
              - roleArn: "arn:aws:iam::xxxxxxxxx:role/yace-iam-role"
            searchTags:
              - key: my_tags_here
                value: .*
            customTags:
              - key: source_aws_account
                value: my_aws_account_name
            metrics:
              - name: execution_time
                statistics:
                  - Average
              - name: status_code
                statistics:
                  - Average
              - name: record_count
                statistics:
                  - Average
              - name: Invocations
                statistics:
                  - Sum
              - name: Errors
                statistics:
                  - Sum
              - name: Throttles
                statistics:
                  - Sum
              - name: Duration
                statistics:
                  - Maximum
                  - Average
              - name: ConcurrentExecutions
                statistics:
                  - Maximum
              - name: UnreservedConcurrentExecutions
                statistics:
                  - Maximum
              - name: ProvisionedConcurrencyInvocations
                statistics:
                  - Maximum
              - name: ProvisionedConcurrentExecutions
                statistics:
                  - Maximum
              - name: ProvisionedConcurrencyUtilization
                statistics:
                  - Maximum
              - name: IteratorAge
                statistics:
                  - Maximum
              - name: DeadLetterErrors
                statistics:
                  - Maximum
              - name: ProvisionedConcurrencyUtilization
                statistics:
                  - Maximum
```

### Current Behavior

In order to save cost with GMD calls, we increased scrape interval to 2 minute. (Earlier it was one minute).
To avoid any data point loss we increase add `length` and `delay` property to job.
Where `length` is set to `360` (6 minutes) and `delay` set to `180` (3 minutes).
As per the code, start time is set to `time.Now() - (length +delay)` and end time is set to `time.Now() - delay` for GMD calls.
This should actually returns 6 data points and export 6 data points on `/metrics` endpoints for lambda `invocations` metric.
However we only see one data point being exported. We don't know how it ends up with aggregating (i guess) or showing only one data point from the selected range. Our scraper (grafana agent service monitor) honors cloudwatch time timestamp.
PFB : Sometime data comes as straight line and sometime with spike but plots invalid data points.
<img width="1351" alt="Screenshot 2023-07-28 at 2 19 37 PM" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/8531843/31664e8c-360e-426a-87d6-668d5acb20e8">

<img width="1355" alt="Screenshot 2023-07-28 at 2 19 56 PM" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/8531843/db45da2f-e16e-4fad-93f0-6e7f538d3f78">

### Expected Behavior

All data points should be exported in a given range as per `length` and `delay` configuration. No data should be lost with increase in scrape interval.

PFB plotted graph on cloudwatch for Invocation Sum with Period of 1 minute.
<img width="1318" alt="Screenshot 2023-07-28 at 2 26 34 PM" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/8531843/f128cb93-aff0-4c75-abad-7b980cc56b79">

### Steps To Reproduce

Use the config provided above use grafana agent as scraper with service monitor.
