### ISSUE TITLE
[BUG] memorydb No tagged resources made it through 

### ISSUE THREAD

**Issue by xiaozhuang-a** [nerdswords/yet-another-cloudwatch-exporter#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.54.0

### Config file

      - type: AWS/MemoryDB
        regions:
          - us-west-2
        period: 60
        length: 60
        metrics:
          - name: CPUUtilization
            statistics: [Maximum]  
          - name: EngineCPUUtilization 
            statistics: [Maximum]
          - name: FreeableMemory
            statistics: [Average]
          - name: NetworkBytesIn  
            statistics: [Maximum]

### Current Behavior

memorydb Unable to collect metric，error：
err":"expected to discover resources but none were found","job_type":"AWS/MemoryDB","level":"error","msg":"No tagged resources made it through filtering","region":"us-west-2"

### Expected Behavior

have data

**Comment by cristiangreco** [comment]
Hi @xiaozhuang-a, do to have added tags to your resources? A discovery job can only be used with resources that have tags.

**Comment by xiaozhuang-a** [comment]
yes,After actively adding a label, it is sufficient, but theoretically, other resources such as RDS do not need to be actively added.

**Comment by cristiangreco** [comment]
Closing this ticket as resolved.

**Comment by mbhattrh23** [comment]
Hi @cristiangreco , i am facing the same issue here: what kind of tags we need to add to these resources?
```
{"account":"123456789","arn":"","caller":"discovery.go:96","end":2356,"job_type":"alb","level":"warn","msg":"GetMetricData partition empty result","partitionNum":4,"region":"us-east-1","start":2000,"ts":"2023-10-26T15:05:49.009417208Z","version":"v0.55.0"}
{"account":"123456789","arn":"","caller":"discovery.go:45","err":"expected to discover resources but none were found","job_type":"es","level":"error","msg":"No tagged resources made it through filtering","region":"us-east-1","ts":"2023-10-26T15:10:49.205085348Z","version":"v0.55.0"}
{"account":"123456789","arn":"","caller":"discovery.go:45","err":"expected to discover resources but none were found","job_type":"lambda","level":"error","msg":"No tagged resources made it through filtering","region":"us-east-1","ts":"2023-10-26T15:10:49.208628578Z","version":"v0.55.0"}
{"account":"123456789","arn":"","caller":"discovery.go:45","err":"expected to discover resources but none were found","job_type":"sqs","level":"error","msg":"No tagged resources made it through filtering","region":"us-east-1","ts":"2023-10-26T15:10:49.210078139Z","version":"v0.55.0"}
{"account":"123456789","arn":"","caller":"discovery.go:45","err":"expected to discover resources but none were found","job_type":"rds","level":"error","msg":"No tagged resources made it through filtering","region":"us-east-1","ts":"2023-10-26T15:10:49.217374535Z","version":"v0.55.0"}
{"caller":"client.go:113","err":"ValidationError: The value Minimumm for parameter MetricDataQueries.member.256.MetricStat.Stat is not a valid statistic.\nThe value Minimumm for parameter MetricDataQueries.member.260.MetricStat.Stat is not a valid statistic.\nThe value Minimumm for parameter MetricDataQueries.member.264.MetricStat.Stat is not a valid statistic.\nThe value Minimumm for parameter MetricDataQueries.member.268.MetricStat.Stat is not a valid statistic.\nThe value Minimumm for parameter MetricDataQueries.member.296.MetricStat.Stat is not a valid statistic.
```

I have below config set up:
```
config: |-
  apiVersion: v1alpha1
  sts-region: us-east-1
  discovery:
    jobs:
      - type: es
        regions:
          - us-east-1
        period: 300
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Sum,Maximum,Average,Minimum]
          - name: FreeStorageSpace
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ClusterStatus.green
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ClusterStatus.yellow
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ClusterStatus.red
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.active
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.unassigned
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.delayedUnassigned
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.activePrimary
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.initializing
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.initializing
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Shards.relocating
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Nodes
            statistics: [Sum,Maximum,Average,Minimum]
          - name: SearchableDocuments
            statistics: [Sum,Maximum,Average,Minimum]
          - name: DeletedDocuments
            statistics: [Sum,Maximum,Average,Minimum]

      - type: sqs
        regions:
          - us-east-1
        enableMetricData: true
        period: 60
        length: 60
        metrics:
          - name: NumberOfMessagesSent
            statistics: [Sum,Maximum,Average,Minimum]
          - name: NumberOfMessagesReceived
            statistics: [Sum,Maximum,Average,Minimum]
          - name: NumberOfMessagesDeleted
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ApproximateAgeOfOldestMessage
            statistics: [Sum,Maximum,Average,Minimum]
          - name: NumberOfEmptyReceives
            statistics: [Sum,Maximum,Average,Minimum]
          - name: SentMessageSize
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ApproximateNumberOfMessagesNotVisible
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ApproximateNumberOfMessagesDelayed
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ApproximateNumberOfMessagesVisible
            statistics: [Sum,Maximum,Average,Minimum]

      - type: lambda
        regions:
          - us-east-1
        period: 300
        length: 300
        metrics:
          - name: Invocations
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Errors
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Throttles
            statistics: [Sum,Maximum,Average,Minimum]
          - name: Duration
            statistics: [Average, Maximum, Minimum, p90]

      - type: rds
        regions:
          - us-east-1
        period: 300
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Sum,Maximum,Average,Minimum]
          - name: DatabaseConnections
            statistics: [Sum,Maximum,Average,Minimum]
          - name: FreeableMemory
            statistics: [Sum,Maximum,Average,Minimum]
          - name: FreeStorageSpace
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ReadThroughput
            statistics: [Sum,Maximum,Average,Minimum]
          - name: WriteThroughput
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ReadLatency
            statistics: [Sum,Maximum,Average,Minimum]
          - name: WriteLatency
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ReadIOPS
            statistics: [Sum,Maximum,Average,Minimum]
          - name: WriteIOPS
            statistics: [Sum,Maximum,Average,Minimum]

      - type: alb
        regions:
          - us-east-1
        period: 300
        length: 300
        metrics:
          - name: HealthyHostCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: UnHealthyHostCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: RequestCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: TargetResponseTime
            statistics: [Sum,Maximum,Average,Minimum]
          - name: ActiveConnectionCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: NewConnectionCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: RejectedConnectionCount
            statistics: [Sum]
          - name: TargetConnectionErrorCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: IPv6RequestCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: RequestCountPerTarget
            statistics: [Sum]
          - name: NonStickyRequestCount
            statistics: [Sum,Maximum,Average,Minimum]
          - name: HTTPCode_Target_2XX_Count
            statistics: [Sum]
          - name: HTTPCode_Target_3XX_Count
            statistics: [Sum,Maximum,Average,Minimum]
          - name: HTTPCode_Target_4XX_Count
            statistics: [Sum,Maximum,Average,Minimum]
          - name: HTTPCode_Target_5XX_Count
            statistics: [Sum,Maximum,Average,Minimum]
          - name: HTTPCode_ELB_3XX_Count
            statistics: [Sum]
          - name: HTTPCode_ELB_4XX_Count
            statistics: [Sum,Maximum,Average,Minimum]
          - name: HTTPCode_ELB_5XX_Count
            statistics: [Sum,Maximum,Average,Minimum]

```
