### ISSUE TITLE
[BUG] Invalid timestamps on metrics with addCloudwatchTimestamp after upgrading from 0.53.0 to 0.54.1

### ISSUE THREAD

**Issue by doris-zhou** [nerdswords/yet-another-cloudwatch-exporter#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.54.1

### Config file

Configuration of the affected job:

```
apiVersion: v1alpha1
discovery:
  jobs:
    - type: firehose
      regions:
        - us-east-1
      period: 300
      length: 300
      addCloudwatchTimestamp: true
      metrics:
        - name: DeliveryToS3.Success
          statistics: [Average]
        - name: DeliveryToS3.DataFreshness
          statistics: [Maximum]
        - name: IncomingBytes
          statistics: [Sum]
```

### Current Behavior

We upgraded from version 0.53.0 to 0.54.1 with no changes in YACE config between versions. Prometheus started failing to scrape YACE with the message:

`expected timestamp or new record, got "INVALID"`

Prometheus logs include errors like:
```
ts=2023-09-05T15:11:17.245Z caller=scrape.go:1697 level=warn component="scrape manager" scrape_pool=<redacted> target=<redacted> msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
```

and in a separate Prometheus instance:
```
ts=2023-09-05T17:55:01.215Z caller=scrape.go:1700 level=warn component="scrape manager" scrape_pool=<redacted> target=<redacted> msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=33
ts=2023-09-05T18:03:35.763Z caller=scrape.go:1694 level=warn component="scrape manager" scrape_pool=<redacted> target=<redacted> msg="Error on ingesting out-of-order samples" num_dropped=42
```

I've checked YACE's metrics output and compared them between two versions. It seems that some metrics are getting a negative value for the timestamp.

With 0.53.0:

`aws_firehose_delivery_to_s3_success_average{<labels redacted>} 1 1693939800000`

With 0.54.1:

`aws_firehose_delivery_to_s3_success_average{<labels redacted>} 0 -62135596800000`

We have observed this only on the Firehose metrics so far. What could be causing the negative timestamp?

### Expected Behavior

I expect to be able to scrape metrics with the `addCloudwatchTimestamp` option as in previous versions of YACE.
