### ISSUE TITLE
[BUG] ECS ContainerInsights metrics not pulling for `ClusterName,ServiceName`

### ISSUE THREAD

**Issue by paulsjohnson91** [nerdswords/yet-another-cloudwatch-exporter#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.54.1

### Config file
```
apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
    - type: ecs-containerinsights
      regions: [ eu-central-1 ]
      period: 300
      length: 300
      metrics:
        - name: CpuReserved
          statistics:
            - Average
        - name: ContainerInstanceCount
          statistics:
            - Average
        - name: CpuUtilized
          statistics:
            - Average
        - name: MemoryReserved
          statistics:
            - Average
        - name: MemoryUtilized
          statistics:
            - Average
        - name: StorageReadBytes
          statistics:
            - Average
        - name: StorageWriteBytes
          statistics:
            - Average
        - name: NetworkRxBytes
          statistics:
            - Average
        - name: NetworkTxBytes
          statistics:
            - Average
        - name: DesiredTaskCount
          statistics:
            - Average
        - name: TaskCount
          statistics:
            - Average
        - name: PendingTaskCount
          statistics:
            - Average
        - name: RunningTaskCount
          statistics:
            - Average
        - name: DeploymentCount
          statistics:
            - Average
        - name: TaskSetCount
          statistics:
            - Average
```
### Current Behavior

Metrics like TaskCount are coming down correctly, but metrics like PendingTaskCount are not. 
This appears to be that metrics with only a ClusterName requirements will work but not when ClusterName and ServiceName. In the AWS Cloudwatch Console you can see they are grouped as such
![Screenshot 2023-09-06 at 11 25 21](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/28013436/8f3f9325-70bb-444f-847f-147ed9afa873)
Where in the `ClusterName,ServiceName` tab you can see PendingTaskCount
![Screenshot 2023-09-06 at 11 25 50](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/28013436/73b12cd7-49c1-4e1f-986a-c0d7b0195f2f)
But you cannot see it in the `ClusterName` tab

![Screenshot 2023-09-06 at 11 26 13](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/28013436/3c516080-2f45-4df4-b126-e1ad91b5250d)

### Expected Behavior

Metrics where the servicename dimension is required are accessible

### Steps To Reproduce

Run the yace repo provided docker-compose with no changes but applying the config above

### Anything else?

n/a
