### ISSUE TITLE
[BUG] Route53 Health checks missing tag labels

### ISSUE THREAD

**Issue by lsh-0** [nerdswords/yet-another-cloudwatch-exporter#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.54.1

### Config file

```yaml
apiVersion: v1alpha1
sts-region: us-east-1
discovery:
    exportedTagsOnMetrics:
        route53:
            - Name
            - Project
            - Environment
    jobs:
      - type: AWS/Route53
        regions:
          - us-east-1
        dimensionNameRequirements:
            - HealthCheckId
        metrics:
          - name: HealthCheckPercentageHealthy
            statistics:
                - Average
            period: 60
            length: 300
```

### Current Behavior

Metrics are being emitted for Route 53 healthchecks, but are missing the labels that (as I understand from the configuration document) should be attached to them as either `tag_Name` or `tag_name`, depending on `--labels-snake-case`.

The only labels I see are:
![Screenshot at 2023-09-12 15-03-34](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/2142748/55f9fff0-efec-45b7-af47-aa4c7a432080)

### Expected Behavior

Each healthcheck has three tags configured, `Name`, `Project` and `Environment`:

![Screenshot at 2023-09-12 15-06-21](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/2142748/d6afa518-4ef4-4c0c-a52b-3b62d9c6cda9)

 I am expecting `tag_name`, `tag_project` and `tag_environment` to be available so alerts can filter healthchecks by project and environment and include the `tag_name` label in the message.
