### ISSUE TITLE
[QUESTION] Cloudwatch alb metrics with timestamps in the future?

### ISSUE THREAD

**Issue by mike-brown-angi** [nerdswords/yet-another-cloudwatch-exporter#1153]
Hi Folks,  We are seeing future timestamps from our jobs.  I am curious about how that might be happening?

The configs are set up the same across jobs.  Like this example of for albs:

```
discovery:
  exportedTagsOnMetrics:
    alb:
      - Name
    elb:
      - kubernetes.io/service-name 
    nlb:
      - kubernetes.io/service-name 
  jobs:
...
    - type: alb
      regions:
        - <list of regions>
      roles:
        - <list of rolArns here>
        
      addCloudwatchTimestamp: true
      length: 120
      period: 60
      statistics:
        - Average
        - Sum
        - Minimum
        - Maximum
      metrics:
        - name: ActiveConnectionCount
        - name: ClientTLSNegotiationErrorCount
        - name: ConsumedLCUs
        - name: DesyncMitigationMode_NonCompliant_Request_Count
        - name: ForwardedInvalidHeaderRequestCount
        - name: HTTPCode_ELB_3XX_Count
        - name: HTTPCode_ELB_4XX_Count
        - name: HTTPCode_ELB_502_Count
        - name: HTTPCode_ELB_504_Count
        - name: HTTPCode_ELB_5XX_Count
        - name: HTTPCode_Target_2XX_Count
        - name: HTTPCode_Target_3XX_Count
        - name: HTTPCode_Target_4XX_Count
        - name: HTTPCode_Target_5XX_Count
        - name: HTTP_Redirect_Count
        - name: HealthyHostCount
```
The `addCloudwatchTimestamp: true` was added during the investigation.  Without it, the timestamps range up to 5 minutes into the future.  With it, they range up to 3 minutes into the future.

The data path is aws -> yace -> mimir and we're using grafana 9 to visualize those metrics.  

Any thoughts on how to troubleshoot this further would be much appreciated.
