### ISSUE TITLE
[BUG] inconsistent mix of namespace and alias in config files breaks `exportedTagsOnMetrics`

### ISSUE THREAD

**Issue by cristiangreco** [nerdswords/yet-another-cloudwatch-exporter#1160]
_Reported originally as https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/948, but splitting it out to better track the root cause of the issue._

In configs of type `discovery` and `customNamespace`, the job `type` field is flexible, you can use either the aws namespace or the alias. 

However, we don't document that the choice of job `type` must be consistent with `exportedTagsOnMetrics`. In other words, aliases and namespaces can't be mixed across `job.type` and `exportedTagsOnMetrics` otherwise the latter won't work as expected.

This is an example good config:

```yaml
config:
  apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      AWS/AmazonMQ:
        - my_tag
    jobs:
      - type: AWS/AmazonMQ
        roles:
```

This is an example bad config:

```yaml
config:
  apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      mq:
        - my_tag
    jobs:
      - type: AWS/AmazonMQ
        roles:
```

Config parsing and scraping works for both examples, but `exportedTagsOnMetrics` works correctly only in the first case.
