### ISSUE TITLE
[BUG] Resources without tags not getting picked up

### ISSUE THREAD

**Issue by ecktom** [nerdswords/yet-another-cloudwatch-exporter#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

```
v0.55.0
```
Running with:
```
- --enable-feature=max-dimensions-associator,list-metrics-callback,aws-sdk-v2,always-return-info-metrics
```

### Config file

```
   jobs:
    - type: AWS/Lambda
      roles:
        - roleArn: "arn:aws:iam::<redacted>:role/yace"
      dimensionNameRequirements: [FunctionName]
      regions: [eu-central-1]
      period: 300
      length: 300
      metrics:
        - name: Invocations
          statistics: [Sum]
        - name: Errors
          statistics: [Sum]
        - name: Throttles
          statistics: [Sum]
        - name: Duration
          statistics: [Average, Maximum, Minimum, p90]
        - name: DeadLetterErrors
          statistics: [Sum]
        - name: DestinationDeliveryFailures
          statistics: [Sum]
        - name: ProvisionedConcurrencyInvocations
          statistics: [Sum]
        - name: ProvisionedConcurrencySpilloverInvocations
          statistics: [Sum]
        - name: IteratorAge
          statistics: [Average, Maximum]
        - name: ConcurrentExecutions
          statistics: [Sum]
        - name: ProvisionedConcurrentExecutions
          statistics: [Sum]
        - name: ProvisionedConcurrencyUtilization
          statistics: [Maximum]
        - name: UnreservedConcurrentExecutions
          statistics: [Sum]
```

### Current Behavior

Lambda's without any tag are not getting picked up, as soon as I add a tag like `foo: bar` metrics are getting scraped. Based on debug logs within https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/fad9e02308436e0e3ec64a5807b4c67f0be8247d/pkg/job/maxdimassociator/associator.go#L136

```
{
    "account": "<redacted>",
    "arn": "arn:aws:iam::<redacted>:role/yace",
    "caller": "associator.go:152",
    "dimensions": "FunctionName",
    "job_type": "AWS/Lambda",
    "level": "debug",
    "metric_name": "Throttles",
    "msg": "associate loop start",
    "region": "eu-central-1",
    "ts": "2023-09-27T14:56:57.173465484Z",
    "version": "v0.55.0"
}
{
    "account": "<redacted>",
    "arn": "arn:aws:iam::<redacted>:role/yace",
    "caller": "associator.go:163",
    "job_type": "AWS/Lambda",
    "level": "debug",
    "mapping": "{dimensions=[FunctionName], dimensions_mappings={879082185929098817=arn:aws:lambda:eu-central-1:<redacted>:function:lambda1,12359525889515349691=arn:aws:lambda:eu-central-1:<redacted>:function:lambda2,}}",
    "mapping_idx": 0,
    "metric_name": "Throttles",
    "msg": "found mapping",
    "region": "eu-central-1",
    "ts": "2023-09-27T14:56:57.173491469Z",
    "version": "v0.55.0"
}
{
    "account": "<redacted>",
    "arn": "arn:aws:iam::<redacted>:role/yace",
    "caller": "associator.go:182",
    "job_type": "AWS/Lambda",
    "level": "debug",
    "metric_name": "Throttles",
    "msg": "resource not matched",
    "region": "eu-central-1",
    "signature": 14117472150597780025,
    "ts": "2023-09-27T14:56:57.173515197Z",
    "version": "v0.55.0"
}
{
    "account": "<redacted>",
    "arn": "arn:aws:iam::<redacted>:role/yace",
    "caller": "associator.go:194",
    "job_type": "AWS/Lambda",
    "level": "debug",
    "metric_name": "Throttles",
    "msg": "associate loop end",
    "region": "eu-central-1",
    "skip": true,
    "ts": "2023-09-27T14:56:57.173532271Z",
    "version": "v0.55.0"
}
{
    "account": "<redacted>",
    "arn": "arn:aws:iam::<redacted>:role/yace",
    "caller": "discovery.go:269",
    "dimensions": "FunctionName=lambda-without-labels",
    "job_type": "AWS/Lambda",
    "level": "debug",
    "metric": "Throttles",
    "msg": "skipping metric unmatched by associator",
    "region": "eu-central-1",
    "ts": "2023-09-27T14:56:57.173550321Z",
    "version": "v0.55.0"
}
```

### Expected Behavior

If not using any tag filtering, I would have expected any resource of a specific type is getting picked up.

### Anything else?

Seems also happen to other people and other resource types https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/946#issuecomment-1553704356

**Comment by sundarv85** [comment]
We are also facing the same issue with ec2-instances. Only if a resource is tagged, it is picked up. Any options or configurations to work around this.

**Comment by ecktom** [comment]
Found the issue over here https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/docs/configuration.md#discovery_jobs_list_config

> Note: Only [tagged resources](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html) are discovered.

**Comment by sundarv85** [comment]
Hi @ecktom Thanks for the link. 

Could you elaborate more on how you went around the requirement - to also pick up resources without the tags... I'm trying this, and still only tagged resources are picked up


```
apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/EC2
      regions:
        - ap-south-1
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
          period: 300
          length: 3600
```
