### ISSUE TITLE
[BUG] S3 Replication Cross Account Cross-Region Replication (CRR) Metrics ignored by discovery

### ISSUE THREAD

**Issue by Firefishy** [nerdswords/yet-another-cloudwatch-exporter#1188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.54.1

### Config file

```
apiVersion: v1alpha1
sts-region: eu-west-1
discovery:
  jobs:
    - type: AWS/S3
      regions:
        - eu-west-1 # source region 
        - eu-north-1 # destination region
      roundingPeriod: 300
      period: 300
      length: 300
      metrics:
        - name: ReplicationLatency
          statistics: [Maximum]
        - name: BytesPendingReplication
          statistics: [Maximum]
        - name: OperationsPendingReplication
          statistics: [Maximum]
        - name: OperationsFailedReplication
          statistics: [Sum]
```

### Current Behavior

Only `OperationsFailedReplication` replication metric is collected from `eu-west-1`

The `ReplicationLatency`, `BytesPendingReplication`, `OperationsPendingReplication` replication metrics are not collected and the following message is returned:

```json
{
  "account": "1111",
  "caller": "discovery.go:46",
  "err": "expected to discover resources but none were found",
  "job_type": "AWS/S3",
  "level": "error",
  "msg": "No tagged resources made it through filtering",
  "region": "eu-north-1",
  "ts": "2023-10-12T03:12:56.741675833Z",
  "version": "0.54.1"
}
```

### Expected Behavior

`OperationsFailedReplication` replication metric is collected from `eu-west-1`

`ReplicationLatency`, `BytesPendingReplication`, `OperationsPendingReplication` replication metrics are collected from `eu-north-1`

### Steps To Reproduce

1. Create AWS accounts `1111` and `2222`.
2. Create source S3 buckets `source-1111` in `eu-west-1` in account `11111`.
3. Create destination S3 bucket `destination-2222` in `eu-north-1` in account `22222` .
4. Setup S3 Cross Account Replication with Replication Metrics enabled.
5. AWS publishes S3 replication metric `OperationsFailedReplication` in account `11111` in the `eu-west-1` region.
6. AWS publishes S3 replication metrics `ReplicationLatency`, `BytesPendingReplication`, `OperationsPendingReplication` in account `11111` in the **`eu-north-1`** region. NOTE **`eu-north-1`** region.

### Anything else?

A workaround is to not use discovery for the `ReplicationLatency`, `BytesPendingReplication`, `OperationsPendingReplication` replication metrics and instead use static collect. [Working example](https://github.com/openstreetmap/chef/blob/3d1373107990131ab0d92a42f755c17375344136/cookbooks/prometheus/templates/default/cloudwatch.yml.erb#L218-L244)
