### ISSUE TITLE
[BUG] VPN metrics missing dimensions

### ISSUE THREAD

**Issue by igor-nikiforov** [nerdswords/yet-another-cloudwatch-exporter#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.51.0

### Config file

```yaml
  - type: AWS/VPN
    regions:
      - us-east-1
    period: 300
    length: 300
    metrics:
      - name: TunnelDataIn
        statistics: [Sum]
      - name: TunnelDataOut
        statistics: [Sum]
      - name: TunnelState
        statistics: [Maximum]
```

### Current Behavior

Below config gives me following output:

```
# HELP aws_vpn_tunnel_state_maximum Help is not implemented yet.
# TYPE aws_vpn_tunnel_state_maximum gauge
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="",dimension_VpnId="vpn-030c3b1ac3519b521",name="arn:aws:ec2:us-east-1:xxx:vpn-connection/vpn-030c3b1ac3519b521",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="",dimension_VpnId="vpn-05c2b8f94e967c0c6",name="arn:aws:ec2:us-east-1:xxx:vpn-connection/vpn-05c2b8f94e967c0c6",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="",dimension_VpnId="vpn-8bbfa1ea",name="arn:aws:ec2:us-east-1:xxx:vpn-connection/vpn-8bbfa1ea",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="3.xxx.xxx.81",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="34.xxx.xxx.115",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="34.xxx.xxx.29",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="34.xxx.xxx.212",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="34.xxx.xxx.255",dimension_VpnId="",name="global",region="us-east-1"} 1
aws_vpn_tunnel_state_maximum{account_id="xxx",dimension_TunnelIpAddress="52.xxx.xxx.211",dimension_VpnId="",name="global",region="us-east-1"} 0
```

As you see here there is no relation between TunnelIpAddress and VpnId. As a result you can understand which pair of tunnels relates to which VPN ids.

### Expected Behavior

TunnelIpAddress and VpnId should appear both in all VPN metrics.
