### ISSUE TITLE
[FEATURE] Support tag discovery with AWS/DataSync

### ISSUE THREAD

**Issue by wkneewalden** [nerdswords/yet-another-cloudwatch-exporter#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

DataSync metrics with TaskId or AgentId dimensions should be included in tag discovery service list.

### What might the configuration look like
```
discovery:
jobs:
- type: datasync
  period: 120
  length: 600
  metrics:
    - name: BytesVerifiedDestination
      statistics: [Sum]
    - name: BytesVerifiedSource
      statistics: [Sum]
    - name: FilesVerifiedDestination
      statistics: [Sum]
    - name: FilesVerifiedSource
      statistics: [Sum]
```
### Anything else?

https://docs.aws.amazon.com/datasync/latest/userguide/tagging-tasks.html
https://docs.aws.amazon.com/datasync/latest/userguide/monitor-datasync.html
