### ISSUE TITLE
[BUG] RDS metrics - values for non-existant DatabaseClass show up

### ISSUE THREAD

**Issue by MiGrandjean** [nerdswords/yet-another-cloudwatch-exporter#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

Yet Another CloudWatch Exporter version v0.55.0

### Config file

```yaml
apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
    - type: rds
      regions:
        - eu-central-1
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Maximum]
        - name: DatabaseConnections
          statistics: [Sum]
        - name: FreeableMemory
          statistics: [Average]
        - name: FreeStorageSpace
          statistics: [Average]
        - name: ReadThroughput
          statistics: [Average]
        - name: WriteThroughput
          statistics: [Average]
        - name: ReadLatency
          statistics: [Maximum]
        - name: WriteLatency
          statistics: [Maximum]
        - name: ReadIOPS
          statistics: [Average]
        - name: WriteIOPS
          statistics: [Average]

```

### Current Behavior

After upgrading from `v0.51.0` to `v0.55.0`, I start to see RDS metrics for a non-existant instance. Usually, I wouldn't bother much, but at least from `v0.54.0` on, metrics like `aws_rds_free_storage_space_average` return a value of `0` - and that fires our alerts which makes this quite urgent. No one wants to be paged for an RDS instance that does not really exist ;)

Example: The correct and existing RDS instance is a `dimension_DatabaseClass="db.t3.small"`. However, we now get also a series for a `dimension_DatabaseClass="db.r5.xlarge"`. I looked in AWS everywhere, all regions, but I can't find that instance:

![Auswahl_690](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/8418423/2e98796b-565d-4073-8f0e-0dddb68a8782)

When I downgrade to `v0.53.0`, the series is still there, but returns `NaN` (at least that does not trigger any alerts, so that's what I chose to run for now):

```
aws_rds_free_storage_space_average{account_id="XXXXXXXXXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="db.r5.xlarge",dimension_EngineName="",name="global",region="eu-central-1"} NaN
aws_rds_free_storage_space_average{account_id="XXXXXXXXXXXX",dimension_DBInstanceIdentifier="",dimension_DatabaseClass="db.t3.small",dimension_EngineName="",name="global",region="eu-central-1"} 9.2788228096e+10
```

### Expected Behavior

Don't show metric series for instances that don't exist :)

### Steps To Reproduce

1. Have an RDS instance in AWS eu-central-1
2. Run YACE v0.54.0 or newer
3. check `aws_rds_free_storage_space_average` wrt `dimension_DBInstanceIdentifier`

### Anything else?

I don't see those metrics in Cloudwatch. 
It might be that I overlooked something in AWS and there is a db.r5.xlarge hiding somewhere, but I think I would see that on the bill ;) Also, the `DatabaseClass` is the only Dimension that appears twice; the other dimensions (e.g. DBInstanceIdentifier) don't have ghost series
I thought maybe it's an old instance and the metrics are still around somehow, but since I cannot delete metrics in Cloudwatch, I still would have to deal with it in YACE, I think.

Any help, ideas, debug hints etc are welcome.
