### ISSUE TITLE
[BUG] No metrics data found for AuroraReplicaLag metric

### ISSUE THREAD

**Issue by hbollon** [nerdswords/yet-another-cloudwatch-exporter#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.55.0

### Config file

```yaml
apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
   
   [...]

    # RDS
    - type: AWS/RDS
      regions:
        - eu-central-1
      searchTags:
        - key: environment
          value: <regex>
      dimensionNameRequirements:
        - DBInstanceIdentifier
      metrics:
        - name: CPUUtilization
          statistics:
          - Maximum
        - name: SwapUsage
          statistics:
          - Maximum
        - name: DiskQueueDepth
          statistics:
          - Maximum
        - name: TransactionLogsDiskUsage
          statistics:
          - Maximum
        - name: EBSByteBalance%
          statistics:
          - Maximum
        - name: EBSIOBalance%
          statistics:
          - Maximum
        - name: AuroraReplicaLagMaximum
          statistics:
          - Minimum
        - name: StorageNetworkReceiveThroughput
          statistics:
          - Minimum
        - name: StorageNetworkTransmitThroughput
          statistics:
          - Minimum
        - name: FreeLocalStorage
          statistics:
          - Minimum
        - name: BufferCacheHitRatio
          statistics:
          - Minimum
        - name: CommitLatency
          statistics:
          - Minimum
        - name: CommitThroughput
          statistics:
          - Minimum
        - name: NetworkReceiveThroughput
          statistics:
          - Minimum
        - name: NetworkTransmitThroughput
          statistics:
          - Minimum
        - name: ReadIOPS
          statistics:
          - Minimum
        - name: WriteIOPS
          statistics:
          - Minimum
        - name: ReadLatency
          statistics:
          - Minimum
        - name: WriteLatency
          statistics:
          - Minimum
        - name: ReadThroughput
          statistics:
          - Minimum
        - name: WriteThroughput
          statistics:
          - Minimum
    - type: AWS/RDS
      regions:
        - eu-central-1
      searchTags:
        - key: environment
          value: <regex>
      dimensionNameRequirements:
        - DBClusterIdentifier
        - EngineName
      metrics:
        - name: VolumeBytesUsed
          statistics:
          - Maximum
        - name: VolumeReadIOPs
          statistics:
          - Maximum
        - name: VolumeWriteIOPs
          statistics:
          - Maximum
    - type: AWS/RDS
      regions:
        - eu-central-1
      searchTags:
        - key: environment
          value: <regex>
      dimensionNameRequirements:
        - DBClusterIdentifier
        - Role
      metrics:
        - name: AuroraReplicaLag
          statistics:
          - Average

     [...]
```

### Current Behavior

All my metrics are working except `AuroraReplicaLag`, with the dimensions `DBClusterIdentifier` and `Role`, which throw `No metrics data found` error. (I tested without tag filter too)

### Expected Behavior

I have  `AuroraReplicaLag` metric with the dimensions `DBClusterIdentifier` and `Role` in the AWS Cloudwatch explorer so I expect YACE can find them and export them.

### Anything else?

Maybe I misconfigured something but since my config work for every others metrics I don't think so

**Comment by hbollon** [comment]
So finally my issue was related to this job: 
```
- type: AWS/RDS
      regions:
        - eu-central-1
      searchTags:
        - key: environment
          value: <regex>
      dimensionNameRequirements:
        - DBClusterIdentifier
        - EngineName
      metrics:
        - name: VolumeBytesUsed
          statistics:
          - Maximum
        - name: VolumeReadIOPs
          statistics:
          - Maximum
        - name: VolumeWriteIOPs
          statistics:
          - Maximum
 ```

And it was due to an inconsistency in the AWS dimensions naming convention. Indeed, for these metrics, it's `DbClusterIdentifier` and not `DBClusterIdentifier` when used in combinaison with `EngineName`... :roll_eyes:
