### ISSUE TITLE
[BUG] Unable to retrieve CloudFront WAF metrics

### ISSUE THREAD

**Issue by thameezb** [nerdswords/yet-another-cloudwatch-exporter#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.55.0

### Config file

```
  apiVersion: v1alpha1
  sts-region: eu-central-1
  static:
    - namespace: AWS/WAFV2
      name: cloudfront_waf_metrics
      regions:
        - us-east-1
      dimensions:
      - name: Rule
        value: ALL
      metrics:
        - name: BlockedRequests
          statistics: [Sum]
          period: 60
          length: 60
        - name: AllowedRequests
          statistics: [Sum]
          period: 60
          length: 60
  discovery:
    jobs:
      - type: AWS/WAFV2
        regions:
          - eu-central-1
          - us-east-1
        period: 300
        length: 300
        metrics:
          - name: BlockedRequests
            statistics: [Sum]
          - name: AllowedRequests
            statistics: [Sum]
```

### Current Behavior

Metrics are found for standard WAF in `eu-central-1`. However Cloudfront WAF metrics are not available. 

When using dynamic config, `No tagged resources made it through filtering` error log is thrown. 
When using static config, 0 metric is returned 

### Expected Behavior

Cloudfront WAF metrics are scraped as are standard WAF metrics

### Steps To Reproduce

- Deploy YACE with the current config file
- Ensure a WAF is created for a CF distribution 
- Watch for metrics

### Anything else?

I see the metrics in Cloudwatch UI and if I query Cloudwatch from Grafana
