### ISSUE TITLE
[BUG] Jobs using `length`, `delay`, and `period` at the job level and metric level results in inconsistent start time and end time for GetMetricData queries

### ISSUE THREAD

**Issue by kgeckhart** [nerdswords/yet-another-cloudwatch-exporter#1290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The way YACE handles length, period, and rounding period when a job has metrics with different configured values is really weird.

Length, period, and rounding period all factor in to calculating the start + endtime for the GetMetricData API call. Each GetMetricData API call has 500 MetricDataQuery's. Each MetricDataQuery represent a single metric returned from ListMetrics which has a configured length, and period. This creates a mismatch in parameters the start + endtime needs to depend on values from the 500 different metrics included in the query. Instead of partitioning the requests around the potential difference in start + end time from differing length + period combinations YACE tries to make a best guess at what is a good enough value for what it is doing,
1. [Calculate rounding period](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/clients/cloudwatch/v2/input.go#L20C1-L39C3) based on the smallest period in a BATCH if the job does not have rounding period configured
    - This can easily result it different batches having different rounding periods
    - The end result will be varying start + endtimes for different batches depending on which metrics were included in the batch
2. [The length is set to the largest configured length of all metric configs in the job](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/job/discovery.go#L161-L169)
    - A longer length for a job which does not require it results in more individual data points being returned
    - Extra individual data points are thrown away resulting in wasted IO time and unclear impact on API response times (querying for more data likely takes longer)
3. [Delay is only respected at the job level](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/job/discovery.go#L89) even though it's [configurable at the metric level](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/model/model.go#L80)

### Expected Behavior

`GetMetricData` requests should contain queries for metrics which all have the same start and end time determined by the configured metric value for rounding period, period, length, and delay. These should be done in batches of 500.

**Comment by kgeckhart** [comment]
Just adding a note I realized,

> 3. [Delay is only respected at the job level](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/job/discovery.go#L89) even though it's [configurable at the metric level](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/model/model.go#L80)

Is especially bad because it will have very unintended consequences when fixed. Metric validation adds a [default 5 minute delay](https://github.com/kgeckhart/yet-another-cloudwatch-exporter/blob/8cfae8f1b1e0e5a3cc1daf846e1ed079e6e0dbfb/pkg/config/config.go#L318-L325) to all metrics if they do not have a defined delay and the job does not have a defined delay. This default delay has largely been ignored because all example configs use no delay at the job level. As soon as this is fixed that delay will take effect potentially breaking the expected behavior for everyone. I'm still trying to think through how to approach this in a safe manner but felt it was necessary to write down.

**Comment by rhys-evans** [comment]
Hi, so I need help to understand what `delay is being depreciated` means in https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/CHANGELOG.md#0590 

At present I can only consistently get metrics if I have a configuration along the lines of the below. Otherwise I more often than not get `NaN` values due to the metric not being present in CloudWatch at scrape time. 

```
  - type: AWS/NATGateway
    regions:
      - <region-1>
      - <region-2>
      - .....
    roles:
      - roleArn: arn:aws:iam::<accountid-1>:role/monitoring-role
      - roleArn: arn:aws:iam::<accountid-2>:role/monitoring-role
      - roleArn: arn:aws:iam::<...........>:role/monitoring-role
    period: 60
    length: 60
    delay: 120
    addCloudwatchTimestamp: true
    metrics:
      - name: ActiveConnectionCount
        statistics: [Maximum, Sum]
      - name: BytesInFromDestination
        statistics: [Maximum, Sum]
      - name: BytesInFromSource
        statistics: [Maximum, Sum]
      - name: BytesOutToDestination
        statistics: [Maximum, Sum]
      - name: BytesOutToSource
        statistics: [Maximum, Sum]
      - name: ConnectionAttemptCount
        statistics: [Maximum, Sum]
      - name: ConnectionEstablishedCount
        statistics: [Maximum, Sum]
      - name: ErrorPortAllocation
        statistics: [Maximum, Sum]
      - name: IdleTimeoutCount
        statistics: [Maximum, Sum]
      - name: PacketsDropCount
        statistics: [Maximum, Sum]
      - name: PacketsInFromDestination
        statistics: [Maximum, Sum]
      - name: PacketsInFromSource
        statistics: [Maximum, Sum]
      - name: PacketsOutToDestination
        statistics: [Maximum, Sum]
      - name: PacketsOutToSource
        statistics: [Maximum, Sum]
```

Are you able to help with my understanding ? I understand my period and length are short, but if by default there is a 5 minute delay, why would i need to set the `delay` option

Any help is appreciated
