### ISSUE TITLE
[FEATURE] Include configuration file

### ISSUE THREAD

**Issue by kpallade** [nerdswords/yet-another-cloudwatch-exporter#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is it possible to include configuration files in the main config file ?
Thx for help

### What might the configuration look like?

```
apiVersion: v1alpha1
sts-region: ${ aws_region }
discovery:
  jobs:
    - type: "AWS/S3"
      regions: ["${ aws_region }"]
      period: 60
      length: 120
      delay: 60
      statistics: ["Average"]
      metrics:
        - name: NumberOfObjects
        - name: BucketSizeBytes
    - include: conf.d/*.conf
```
