### ISSUE TITLE
[FEATURE] Add DocumentDB Elastic Metrics Support

### ISSUE THREAD

**Issue by Bruc3Stark** [nerdswords/yet-another-cloudwatch-exporter#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Now it looks like YACE only supports AWS/DocDB namespace (alias: "docdb"), it would be great if the AWS/DocDB-Elastic namespace can be supported.

### What might the configuration look like?

```yaml
- type: AWS/DocDB-Elastic
  regions:
    - us-west-2
  metrics:
    - name: PrimaryInstanceFreeableMemory
      statistics: [Average]
```
