### ISSUE TITLE
[FEATURE] Add AWS/EC2CapacityReservations Metrics Support

### ISSUE THREAD

**Issue by luismy** [nerdswords/yet-another-cloudwatch-exporter#1324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS supports CloudWatch metrics for `AWS/EC2CapacityReservations` according to their [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/capacity-reservation-cw-metrics.html)

I believe this service is quite straightforward as there are only 4 metrics with the ability to refine by `CapacityReservationId` as dimension

### What might the configuration look like?

```
- type: AWS/EC2CapacityReservations
  regions:
    - ew-west-2
  metrics:
    - name: UsedInstanceCount
      statistics: [Average]
    - name: AvailableInstanceCount
      statistics: [Average]
    - name: TotalInstanceCount
      statistics: [Average]
    - name: InstanceUtilization
      statistics: [Average]
```

### Anything else?

AWS documentation at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/capacity-reservation-cw-metrics.html

I'm happy to give this a go if somebody can point out how new metrics are added to be supported in YACE. I'll look into the code anyway but any pointers will be great
