### ISSUE TITLE
[BUG] API Gateway metrics missing

### ISSUE THREAD

**Issue by markspace** [nerdswords/yet-another-cloudwatch-exporter#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.57.0

### Config file

```
apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    apigateway:
      - fp-component
  jobs:
  - type: apigateway
    regions:
      - us-east-2
    searchTags:
      - key: fp-component
        value: .+
    dimensionNameRequirements:
      - ApiName
      - Method
      - Resource
      - Stage
    metrics:
      - name: Count
        statistics:
          - SampleCount
      - name: Latency
        statistics:
          - Average
      - name: IntegrationLatency
        statistics:
          - Average
      - name: 4XXError
        statistics:
          - Sum
      - name: 5XXError
        statistics:
          - Sum
```

### Current Behavior

`wget -q -O - http://localhost:5000/metrics| cut -d '{' -f 1 | grep -v -e '^#' -e yace | sort -u`
Returns nothing

If I remove the `dimensionNameRequirements` from the config, then I get
```
aws_apigateway_count_sample_count
aws_apigateway_info
```

### Expected Behavior

On version v0.56.0 and earlier
`wget -q -O - http://localhost:5000/metrics| cut -d '{' -f 1 | grep -v -e '^#' -e yace | sort -u`
returns
```
aws_apigateway_4_xxerror_sum
aws_apigateway_5_xxerror_sum
aws_apigateway_count_sample_count
aws_apigateway_info
aws_apigateway_integration_latency_average
aws_apigateway_latency_average
```

### Steps To Reproduce

1. AWS account with REST API Gateway in us-east-2 (for the config above)
2. run yace with the above config
3. If version is 0.57 then no API metrics, and only get info if no dimensionNameRequirements
4. If version 0.56 or below - get various api gw metrics
