### ISSUE TITLE
[BUG] FSx lustre read throughput metrics not available

### ISSUE THREAD

**Issue by bparamjeet** [nerdswords/yet-another-cloudwatch-exporter#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

yace version : v0.36.2-alpha

### Config file

```
discovery:
  jobs:
  - type: "fsx"
    regions:
    - ap-south-1
    delay: 10
    length: 60
    metrics:
      - name: MetadataOperations
        statistics:
        - 'Sum'
        period: 60
      - name: FreeDataStorageCapacity
        statistics:
        - 'Sum'
        period: 60
      - name: DataWriteOperations
        statistics:
        - 'Sum'
        period: 60
      - name: DataReadOperations
        statistics:
        - 'Sum'
        period: 60
      - name: DataWriteBytes
        statistics:
        - 'Sum'
        period: 60
      - name: DataReadBytes
        statistics:
        - 'Sum'
        period: 60

```

### Current Behavior

Readbytes metrics is not exposed , all other metrics are exposed as expected

### Expected Behavior

All metrics needs to be exposed properlu

**Comment by coolstim** [comment]
I have the following configuration
```
 discovery:
            jobs:
              - type: AWS/FSx
                regions:
                  - eu-west-1
                metrics:
                  - name: FreeDataStorageCapacity
                    statistics: [Average]
                  - name: StorageCapacityUtilization
                    statistics: [Average]
```

but the actual bytes are not in the prometheus metric

> aws_fsx_storage_capacity_utilization_average{
>     account_id="xxx",
>     container="prometheus-yet-another-cloudwatch-exporter",
>     dimension_FileSystemId="yyy",
>     endpoint="http",
>     instance="10.64.239.35:5000",
>     job="cloudwatch-exporter-prometheus-yet-another-cloudwatch-exporter",
>     name="arn:aws:fsx:eu-west-1:xxx:file-system/yyy",
>     namespace="monitoring",
>     pod="cloudwatch-exporter-prometheus-yet-another-cloudwatch-expobz6tz",
>     region="eu-west-1",
>     service="cloudwatch-exporter-prometheus-yet-another-cloudwatch-exporter"
> }
