### ISSUE TITLE
No tagged resources made it through filtering for AWS SQS metrics

### ISSUE THREAD

**Issue by Dhruvin4530** [nerdswords/yet-another-cloudwatch-exporter#1398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.59.0

### Config file
```
serviceAccount:
  create: true
  labels: {}
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/cloudwatch-exporter-role
  name: "yace-cw-exporter"
  automountServiceAccountToken: true
```
```
config: |-
  apiVersion: v1alpha1
  sts-region: ap-south-1
  discovery:
    exportedTagsOnMetrics:
      AWS/SQS:
        - Name
    jobs:
    - type: AWS/SQS
      regions:
        - ap-south-1
      period: 60
      length: 60
      metrics:
        - name: NumberOfMessagesSent
          statistics: [Sum,Average]
        - name: NumberOfMessagesReceived
          statistics: [Sum,Average]
        - name: NumberOfMessagesDeleted
          statistics: [Sum,Average]
        - name: ApproximateAgeOfOldestMessage
          statistics: [Sum,Average]
        - name: NumberOfEmptyReceives
          statistics: [Sum,Average]
        - name: SentMessageSize
          statistics: [Sum,Average]
        - name: ApproximateNumberOfMessagesNotVisible
          statistics: [Sum,Average]
        - name: ApproximateNumberOfMessagesDelayed
          statistics: [Sum,Average]
        - name: ApproximateNumberOfMessagesVisible
          statistics: [Sum,Average]
```
### Current Behavior

No tagged resources made it through filtering for AWS SQS metrics.

### Expected Behavior

It should extract the metrics because the metrics are there in AWS account.

### Steps To Reproduce
Use the above config file to deploy the helm chart
