### ISSUE TITLE
[FEATURE] Support AWS/EventBridge/Pipes

### ISSUE THREAD

**Issue by cosmos-sun** [nerdswords/yet-another-cloudwatch-exporter#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like to see metrics for EventBridge pipes just like [#982](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/982), it would be a great help, thanks!

### What might the configuration look like?

```yml 
- type: AWS/EventBridge/Pipes
      regions:
        - '%AWS_REGION%'
      searchTags:
        *searchTags
      period: 60
      length: 180
      delay: 180
      metrics:
        - name: Duration
          statistics: [Average]
        - name: TargetStageFailed
          statistics: [Average]
        - name: ExecutionTimeout
          statistics: [Average]
        - name: ExecutionFailed
          statistics: [Average]
        - name: Invocations
          statistics: [Average]
        - name: EventCount
          statistics: [Average]
        - name: TargetStageDuration
          statistics: [Average]
```

### Anything else?

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-monitoring.html
