### ISSUE TITLE
[BUG] is AWS/IPAM fully supported? Specifically trying to get SubnetIPUsage.

### ISSUE THREAD

**Issue by jmilliron** [nerdswords/yet-another-cloudwatch-exporter#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.61.2

### Config file

```
      - type: AWS/IPAM
        dimensionNameRequirements:
          - AddressFamily
          - OwnerID
          - Region
          - ScopeID
          - VpcID
          - SubnetID
        regions:
          - us-east-1
        period: 900
        length: 900
        statistics:
          - Average
        metrics:
          - name: SubnetIPUsage
```

### Current Behavior

Trying to pull down AWS/IPAM `SubnetIPUsage` metric. Have tried a bunch of dimensions but still getting:

> {"account":"200602884457","arn":"","caller":"discovery.go:40","err":"expected to discover resources but none were found","job_type":"AWS/IPAM","level":"error","msg":"No tagged resources made it through filtering","region":"us-east-1","ts":"2024-07-17T14:58:45.999688635Z","version":"v0.61.2"}

### Expected Behavior

Able to pull down this metric

### Anything else?

Do we even have support for this IPAM metric? I'm looking at https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/1168/files and only see stuff about `ipam-pool`.
