### ISSUE TITLE
Service is not in known list!: AWS/Logs","level":"error","msg":"Error running yace"

### ISSUE THREAD

**Issue by piano-man** [nerdswords/yet-another-cloudwatch-exporter#1473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.54.1

### Config file
 ```
kind: ConfigMap
apiVersion: v1
metadata:
  name: <name>
data:
  config.yml: |
    ---
    apiVersion: v1alpha1
    static:
      - namespace: AWS/Logs
        name: aws_logs
        regions:
          - us-west-2
        roles:
           - <role arn>       
        dimensions:
          - name: LogGroupName
            value: test
        metrics:
          - name: IncomingLogEvents
            statistics:
            - Sum
            period: 30
            length: 30
    discovery:
      exportedTagsOnMetrics:
        AWS/Logs:
          - test:test
      jobs:
      - type: AWS/Logs
        regions:
          - us-west-2
        roles:
           - <rolearn>
        searchTags:
          - key:  "test"
            value: "true"
        metrics:
          - name: IncomingLogEvents
            statistics:
              - Sum
            period: 300
            length: 300
```
### Current Behavior

When trying to dynamically discover AWS/Logs resource, I keep running into service is not in list error.

### Expected Behavior

It should be able to dynamically discover AWS/Logs.

### Anything else?

Is this a know issue with yace?
Can I not discover AWS/Logs resources dynamically?

NOTE: I have AWS/Logs namespace defined statically in the  same config file and that seems to work perfectly.
