### ISSUE TITLE
[FEATURE] Delay etc. for static jobs

### ISSUE THREAD

**Issue by guelfey** [nerdswords/yet-another-cloudwatch-exporter#1474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As setting `delay` on the metric level is deprecated with v0.59.0 (and if I understand correctly, this was never actually honored?), there is no way currently to configure delays on static jobs.

For consistency, it would make sense to support all the JobLevelMetricFields directly under `static`, which could also reduce copy-paste effort currently required for related static jobs. I have not checked the code yet in detail, but I don't see a fundamental reason that would prevent them from being supported for static jobs as well (please correct me if I'm wrong). Otherwise, I'd also be happy to work on a PR for this.

### What might the configuration look like?

```yml
apiVersion: v1alpha1
static:
- name: SomeTimestreamStuff
  namespace: AWS/Timestream
  regions: [eu-central-1]
  dimensions:
  - name: Operation
    value: WriteRecords
  delay: 180
  period: 60
  length: 60
  metrics:
  - name: CumulativeBytesMetered
    statistics: [Sum]
```
