### ISSUE TITLE
[BUG] RDS labels belong to different metrics

### ISSUE THREAD

**Issue by maksimse** [nerdswords/yet-another-cloudwatch-exporter#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

`master-baf1c3f`

### Config file

```
apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/RDS
      regions:
        - us-west-1
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Maximum]
        - name: FreeableMemory
          statistics: [Average]
        - name: DatabaseConnections
          statistics: [Sum]
        - name: DiskQueueDepth
          statistics: [Minimum]
        - name: FreeLocalStorage
          statistics: [Average]
        - name: CommitLatency
          statistics: [Maximum]
        - name: DeleteLatency
          statistics: [Maximum]
        - name: InsertLatency
          statistics: [Maximum]
        - name: ReadLatency
          statistics: [Maximum]
        - name: SelectLatency
          statistics: [Maximum]
        - name: UpdateLatency
          statistics: [Maximum]
        - name: VolumeBytesUsed
          statistics: [Minimum]
        - name: VolumeWriteIOPs
          statistics: [Average]
        - name: VolumeReadIOPs
          statistics: [Average]
    - type: AWS/EBS
      regions:
        - us-west-1
        - us-east-1
      period: 300
      length: 300
      metrics:
        - name: BurstBalance
          statistics: [Minimum]
    - type: AWS/EC2
      regions:
        - us-west-1
        - us-east-1
      period: 300
      length: 300
      metrics:
        - name: CPUCreditBalance
          statistics: [Minimum]
```

### Current Behavior

We have a regional Aurora MySQL cluster of two. 1 reader instance and 1 writer instance.
Number of aws_rds_cpuutilization_maximum{} metrics is bigger than the number of instances.
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/1aa1f77d-fc3d-41be-ab11-d9e4c0e92741">

### Expected Behavior

`dimension_DatabaseClass` label to be present on all metrics.
Why is it listed only on the last two metrics that don't identify RDS at all?

Same thing with aws_rds_freeable_memory_average{} . Memory size depends on instance size. So, we have recorded a metric like aws_rds_memory_max_alloc{} based on AWS documentation. For example:
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/ea43ecb2-3d51-482d-bc30-96835d9312c9">

We could join both metrics on dimension_DatabaseClass label to make threshold dynamic, but we cannot do that.

### Steps To Reproduce

Deploy yace with my config and try to pull RDS cloudwatch metrics.
