### ISSUE TITLE
[FEATURE] Add support of CloudWatchSynthetics in discovery mode

### ISSUE THREAD

**Issue by bawk3** [nerdswords/yet-another-cloudwatch-exporter#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to have ability to export metrics of my CW Canaries. For now I can do it in static mode. If I try to configure in discovery mode then I get error
`{"caller":"main.go:67","err":"Couldn't read /tmp/config.yml: Discovery job [0]: Service is not in known list!: CloudWatchSynthetics","level":"error","msg":"Error running yace","ts":"2024-08-30T13:11:04.404326176Z","version":"v0.61.2"}`

### What might the configuration look like?

```yml
discovery:
  exportedTagsOnMetrics:
    CloudWatch:
      - Name
  jobs:
    - type: "CloudWatchSynthetics"
      regions:
        - "eu-central-1"  # Specify the AWS region where your Canary is running
      metrics:
        - namespace: "CloudWatchSynthetics"
          name: "Duration"
          dimensions:
            - "CanaryName"
            -  "StepName"
          statistics:
            - "Average"
```
