### ISSUE TITLE
[BUG] unable to pull metrics from the specified AmazonMWAA instance using searchTags

### ISSUE THREAD

**Issue by ninad-opsverse** [nerdswords/yet-another-cloudwatch-exporter#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

I am using the latest YACE version - `v0.61.2`

### Config file

```
config: |-
  apiVersion: v1alpha1
  sts-region: us-east-1
  discovery:
    jobs:
      - type: AmazonMWAA
        length: 60
        period: 60
        searchTags:
          - key: airflow
            value: dev
        regions:
          - us-east-1
        metrics:
          - name: SLAMissed
            statistics:
              - Average
          - name: FailedSLACallback
            statistics:
              - Average
          - name: Updates
            statistics:
              - Average
          - name: Orphaned
            statistics:
              - Average
```
              

### Current Behavior

I have 2 airflow instances deployed on aws. 

I have the following tags on the instances - 
mwaa-dev instance: `airflow`: `dev`
mwaa-prod instance: `airflow`: `prod`

According to the configured `searchTags` I should be receiving metrics from `mwaa-dev` instance only. But I am able to see metrics for both the instances. 

### Expected Behavior

Metrics of only the configured mwaa instance(mwaa-dev) should be visible.
