### ISSUE TITLE
[BUG] Inaccurate CloudFront Requests Metrics

### ISSUE THREAD

**Issue by latelan** [nerdswords/yet-another-cloudwatch-exporter#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.61.2

### Config file

```
apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/CloudFront
      regions:
        - us-east-1
      roles:
        - roleArn: xxx
      searchTags:
        - key: Project
          value: cdn
      dimensionNameRequirements:
        - DistributionId
        - Region
      period: 60
      length: 60
      metrics:
        - name: Requests
          statistics: [Sum]
```

### Current Behavior

There is an inconsistency between the data seen in YACE logs and the CloudFront console for the same point in time.
At `2024-10-27 12:24:00 UTC`, YACE shows 11
<img width="786" alt="image" src="https://github.com/user-attachments/assets/125d221f-92e3-4a80-a6b2-1448514d9e98">
while CloudFront console shows 16.
<img width="787" alt="image" src="https://github.com/user-attachments/assets/2be3a530-1a33-4d1b-8c30-62a2319990cb">

### Expected Behavior

The data for both is consistent.
