### ISSUE TITLE
Feature Request : Add Metrics from namespace AWS/DX (direct connect)

### ISSUE THREAD

**Issue by grizo** [nerdswords/yet-another-cloudwatch-exporter#176]
Seeing the metrics available via `aws cloudwatch list-metrics --region us-west-2 --namespace AWS/DX`, shorten example:
```
{
    "Metrics": [
        {
            "Namespace": "AWS/DX",
            "Dimensions": [
                {
                    "Name": "ConnectionId",
                    "Value": "dxcon-removed"
                }
            ],
            "MetricName": "ConnectionBpsIngress"
        },
        {
            "Namespace": "AWS/DX",
            "Dimensions": [
                {
                    "Name": "ConnectionId",
                    "Value": "dxcon-removed"
                }
            ],
            "MetricName": "ConnectionBpsEgress"
        }
    ]
}
```

**Comment by tru-cstavares** [comment]
Hi @thomaspeitz, I am facing the same issue. DX metrics output is empty. On logs I see "_No metrics data found_". I am using v0.36.2-alpha.

> {"account":"xxxxxxxxxxxx","arn":"","job_type":"dx","level":"debug","msg":"No metrics data found","region":"eu-west-1","time":"2022-07-14T14:23:59Z"}

I tried with the following config (tried with and without "_dimensions_ config)" :

```
discovery:
  jobs:
  - type: dx
    regions:
      - eu-west-1
    dimensions:
      - name: ConnectionId
        value: dxcon-xxxxxxxx
    enableMetricData: true
    metrics:
      - name: ConnectionState
        statistics:
        - Average
        length: 180
        period: 60
```

I tested using AWS CLI and I have results. My command:

```
aws cloudwatch get-metric-statistics --namespace AWS/DX --metric-name ConnectionState --start-time '2022-07-12T14:00:56' --end-time '2022-07-12T14:30:56' --period 60 --statistics Average --dimensions Name=ConnectionId,Value=dxcon-xxxxxxxx
```

Am I missing something on YACE config?
