### ISSUE TITLE
Make exporting the average of data points optional

### ISSUE THREAD

**Issue by dudicoco** [nerdswords/yet-another-cloudwatch-exporter#204]
Currently, if you you use average statistics, YACE will export the average of all data points: https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/aws_cloudwatch.go#L731

I suggest making this optional with a flag and document the behaviour in the readme.

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.

**Comment by nhinds** [comment]
`discovery` jobs now use `GetMetricData` which [uses the result from AWS directly](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/promutil/migrate.go#L109) in `migrate.go`, but `static` jobs [still use `GetMetricStatistics](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/job/static.go#L54) and will [calculate the average of averages](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/promutil/migrate.go#L147-L159). It seems this is only partially fixed.

e.g. the following config with a discovery and static job targeting the same bucket will return the same data for `aws_s3_bucket_size_bytes_maximum` and `aws_s3_bucket_size_bytes_minimum`, but different data for `aws_s3_bucket_size_bytes_average` (assuming the bucket size has changed in the past 3 days):
```
apiVersion: v1alpha1
discovery:
  jobs:
  - type: s3
    regions:
    - ap-southeast-2
    metrics:
    - name: BucketSizeBytes
      statistics:
      - Average
      - Maximum
      - Minimum
      period: 86400
      length: 259200
static:
- namespace: AWS/S3
  name: static_s3
  regions:
  - ap-southeast-2
  dimensions:
  - name: BucketName
    value: your-bucket-name-here
  - name: StorageType
    value: StandardStorage
  metrics:
  - name: BucketSizeBytes
    statistics:
    - Average
    - Maximum
    - Minimum
    period: 86400
    length: 259200
```

```
# HELP aws_s3_bucket_size_bytes_average Help is not implemented yet.
# TYPE aws_s3_bucket_size_bytes_average gauge
aws_s3_bucket_size_bytes_average{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="arn:aws:s3:::your-bucket-name-here",region="ap-southeast-2"} 1.084161955e+09
aws_s3_bucket_size_bytes_average{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="static_s3",region="ap-southeast-2"} 1.0838232955e+09
# HELP aws_s3_bucket_size_bytes_maximum Help is not implemented yet.
# TYPE aws_s3_bucket_size_bytes_maximum gauge
aws_s3_bucket_size_bytes_maximum{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="arn:aws:s3:::your-bucket-name-here",region="ap-southeast-2"} 1.084161955e+09
aws_s3_bucket_size_bytes_maximum{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="static_s3",region="ap-southeast-2"} 1.084161955e+09
# HELP aws_s3_bucket_size_bytes_minimum Help is not implemented yet.
# TYPE aws_s3_bucket_size_bytes_minimum gauge
aws_s3_bucket_size_bytes_minimum{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="arn:aws:s3:::your-bucket-name-here",region="ap-southeast-2"} 1.084161955e+09
aws_s3_bucket_size_bytes_minimum{account_id="1234567890",dimension_BucketName="your-bucket-name-here",dimension_StorageType="StandardStorage",name="static_s3",region="ap-southeast-2"} 1.084161955e+09
```

(I would reopen but I can't do so here)
