### ISSUE TITLE
Configuration to get AWS billing metrics using YACE

### ISSUE THREAD

**Issue by Rathan-Challa** [nerdswords/yet-another-cloudwatch-exporter#257]
Hi, I am trying to get billing metrics using the YACE exporter. Does it support billing metrics? If yes, can someone please help me with the configuration to get them?

**Comment by singhjagmohan1000** [comment]
It does not support AWS billing metrics. You can try Yace static configuration, it may work

**Comment by jdomag** [comment]
Below config worked for me:
```
config: |-
  static:
    - namespace: AWS/Billing
      name: billingTotal
      regions: 
      - us-east-1
      dimensions:
      - name: Currency
        value: USD
      metrics:
        - name: EstimatedCharges
          statistics:
          - Maximum
          period: 360
          length: 86400
```

However when I tried to add to it LinkedAccounts and Services it doesn't work and there is no log information why:
```
    - namespace: AWS/Billing
      name: billingPer
      regions: 
      - us-east-1
      dimensions:
      - name: Currency
        value: USD
      - name: ServiceName
        value: .*
      - name: LinkedAccount
        value: .*
      metrics:
        - name: EstimatedCharges
          statistics:
          - Maximum
          period: 360
          length: 86400
```

**Comment by thomaspeitz** [comment]
Yeah I have better billing metrics on my list for a while as well. I think I start working on this in the next week.

I think we should be able to configure something like "full" billing metrics and get all of them.

Will check possiblities here and PR something.

Thanks for this issue.

**Comment by Pishniy** [comment]
Thanks for great exporter. I use it always instead oficial exporter. Can you please advise situation about billing metrics. Today i tried to get billing metrics using yace. But i get only "NaN" value. Another metrics such EC2, RDS work perfect.

**Comment by Pishniy** [comment]
@thomaspeitz Thanks for great exporter. I use it always instead oficial exporter. Can you please advise situation about billing metrics. Today i tried to get billing metrics using yace. But i get only "NaN" value. Another metrics such EC2, RDS work perfect.

**How i use yace:** 

_docker-compose.yml_
```
   yace-exporter:
     image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.26.3-alpha
    #image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.20.0-alpha 
     container_name: yace-exporter
     volumes:
       - ./yace/config.yml:/tmp/config.yml
     command:
       - "-debug"
       - "--config.file=/tmp/config.yml"
       - "--decoupled-scraping=false"
       - "--scraping-interval=60"
     network_mode: "host"
```

_yace.config_

```   
  - type: billing
     regions:
       - us-east-1
     metrics:
       - name: EstimatedCharges
         statistics:
           - Average
         period: 300
         length: 600
```

Thanks

**Comment by ekristen** [comment]
hey @thomaspeitz any movement on auto-discovery or fuller metric collection? Thanks.

**Comment by thomaspeitz** [comment]
Hey @ekristen sadly no update on it :/ I am afraid that this won't be worked on in the near future.
Christmas time will be relaxed for me and I am not getting any income through this update which
makes it hard to focus on it.

If you are interested (or anybody else) in getting some guidance to PR this themselves reach to me out.

**Comment by ekristen** [comment]
@thomaspeitz no worries, I totally understand the holidays and lack of income on OSS projects. I only asked as you mentioned a few comments up. I don't have the need (or cycles) for improving the features at the moment, the above configuration for estimated usage is the main thing I was being asked to provide. 

If my needs become greater, I'll reach out for guidance to help with a PR as I've writing several exporters and am proficient in go enough to assist. 

Thanks for responding so quickly. Happy Holidays, enjoy the downtime.

**Comment by thomaspeitz** [comment]
```
  - type: billing
     regions:
       - us-east-1
     metrics:
       - name: EstimatedCharges
         statistics:
           - Average
         period: 300
         length: 600
```

I check it on Thuersday and make some comments here :) So maybe somebody will work on it in the future.

Thanks for the support and understanding! - Enjoy your evening!
