### ISSUE TITLE
Not all EBSs data is pulling out of Cloudwatch

### ISSUE THREAD

**Issue by idanto** [nerdswords/yet-another-cloudwatch-exporter#294]
Hi,

I'm having an issue that I don't know how to debug.
We are running the latest version and trying to collect the EBS burst balance metric from Cloudwatch.
I see a different number of results per each query and the bottom line is that we can't get the BurstBalance metric for all volumes we have.

When I look at our EBS volumes list in AWS console I see about 336 volumes. 
in Cloudwatch metrics, when I run `MetricName="BurstBalance"` I see get 631 results
when I run `count (aws_ebs_info)` in our Prometheus I get 140 results
When I run `count (aws_ebs_burst_balance_average)` I get 124 results

Version: `v0.24.0-alpha`
Config:
```yaml
discovery:
  exportedTagsOnMetrics:
    ec2: ['Name', 'Cluster']
  jobs:
  - type: ec2
    regions:
      - eu-central-1
    metrics:
      - name: StatusCheckFailed
        statistics:
          - Sum
        period: 600
        length: 60
      - name: StatusCheckFailed_Instance
        statistics:
          - Sum
        period: 600
        length: 60
      - name: StatusCheckFailed_System
        statistics:
          - Sum
        period: 600
        length: 60
  - type: ebs
    regions:
      - eu-central-1
    metrics:
      - name: BurstBalance
        statistics:
          - Average
        period: 600
        length: 600
```

we also run with flags:
`--decoupled-scraping --labels-snake-case`

AWS IAM policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowReadingMetricsFromCloudWatch",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:ListMetrics",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:GetMetricData",
                "tag:GetResources"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by idanto** [comment]
similar to #283

**Comment by gworley3** [comment]
I'm seeing this even when searching with a tag:

```
      discovery:
        jobs:
        - type: ebs
          length: 120
          period: 60
          addCloudwatchTimestamp: true
          regions:
          - us-east-1
          awsDimensions:
          - VolumeID
          searchTags:
          - Key: KubernetesCluster
            Value: "my-cluster.ue1.example.com"
          metrics:
          - name: BurstBalance
            statistics:
            - Sum
            - SampleCount
            - Minimum
            - Maximum
            - Average
```

returns only `aws_ebs_info` results and nothing for burst balance.
