### ISSUE TITLE
Wrong values in metrics. Can be fixed by restarting exporter instance.

### ISSUE THREAD

**Issue by eugenekainara** [nerdswords/yet-another-cloudwatch-exporter#321]
Hi!

I'm using yet-another-cloudwatch-exporter(yace) inside of my EKS cluster and it seems that yace shows wrong values sometimes.

I'm have 3 EKS clusters and 1 AWS Elasticsearch. in both clusters I have similar yace installations. for some reason I've noticed with an alerts from 1 of 3 clusters. e.g yace reported aws_es_cluster_index_writes_blocked_maximum equals 1 - but other 2 clusters shows that aws_es_cluster_index_writes_blocked_maximum is 0

<img width="514" alt="Screenshot 2021-02-11 at 14 45 44" src="https://user-images.githubusercontent.com/10795260/107638218-f14a0480-6c77-11eb-8266-e91a50c3aeb7.png">
<img width="511" alt="Screenshot 2021-02-11 at 14 46 05" src="https://user-images.githubusercontent.com/10795260/107638226-f27b3180-6c77-11eb-88a2-7d4ca008049e.png">

After restart of yace - values are same for both exporter instances.

this is part of my config related to AWS ElasticSearch:
```
discovery:
  exportedTagsOnMetrics:
    es:
    - Name
  jobs:
    - awsDimensions:
      - ClientId
      - DomainName
      delay: 300
      length: 60
      metrics:
      - name: KibanaHealthyNodes
        period: 60
        statistics:
        - Minimum
      - length: 300
        name: ClusterIndexWritesBlocked
        period: 300
        statistics:
        - Maximum
      regions:
      - eu-central-1
      searchTags:
      - Key: type
        Value: k8s
      type: es
```
