### ISSUE TITLE
Additional examples wanted

### ISSUE THREAD

**Issue by nmiculinic** [nerdswords/yet-another-cloudwatch-exporter#333]
I'd like to define static metrics which defines AWS usage of certain instance types...but I'm unsure how to do it with static config and would appreciate some more examples. 

![Screenshot_20210311_125438](https://user-images.githubusercontent.com/3183610/110783649-027f3480-8269-11eb-947d-797cd66e529e.png)

Here's my feeble attempt: 

```yaml
static:
  - namespace: AWS/Usage
    name: must_be_set
    regions:
      - us-east-1
    dimensions:
      - name: Type
        value: Resource
      - name: Resource
        value: vCPU
      - name: Service
        value: EC2
      - name: Class
        value: P/OnDemand
    metrics:
      - name: ResourceCount
        statistics:
          - Maximum
        period: 300
        length: 300
```

Though I've probably massacred AWS API due to limited experience with CloudWatch; however when I look at the metrics the test static metric isn't there:

```
# HELP yace_cloudwatch_apigatewayapi_requests_total 
# TYPE yace_cloudwatch_apigatewayapi_requests_total counter
yace_cloudwatch_apigatewayapi_requests_total 0
# HELP yace_cloudwatch_autoscalingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_autoscalingapi_requests_total counter
yace_cloudwatch_autoscalingapi_requests_total 0
# HELP yace_cloudwatch_getmetricdata_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricdata_requests_total counter
yace_cloudwatch_getmetricdata_requests_total 0
# HELP yace_cloudwatch_getmetricstatistics_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricstatistics_requests_total counter
yace_cloudwatch_getmetricstatistics_requests_total 2
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 2
# HELP yace_cloudwatch_resourcegrouptaggingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_resourcegrouptaggingapi_requests_total counter
yace_cloudwatch_resourcegrouptaggingapi_requests_total 0
# HELP yace_cloudwatch_targetgroupapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_targetgroupapi_requests_total counter
yace_cloudwatch_targetgroupapi_requests_total 0
```
