### ISSUE TITLE
Unable to get metric statistics due to NoCredentialProviders

### ISSUE THREAD

**Issue by PoppleJIW** [nerdswords/yet-another-cloudwatch-exporter#342]
I have an ECS cluster running a fargate container of YACE, despite the execution shell having assumed an AWS IAM role & a provided roleARN in the YACE config I get the following errors when trying to use the Auto Discovery feature.
Any static configurations provided work just fine on the exact same instance.

Prior to having these issues I only had static configurations, only upon trying to utilise the AutoDiscovery feature have I run into issues.

`{"level":"info","msg":"Couldn't get account Id for role arn:aws:iam::REDACTED:role/cloudwatch-exporter: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n","time":"2021-03-22T11:06:21Z"}`

`{"level":"info","msg":"Couldn't get account Id for role : NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n","time":"2021-03-22T11:06:21Z"}`

`{"level":"info","msg":"Couldn't describe resources for region eu-west-2: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n","time":"2021-03-22T11:06:21Z"}`

`{"level":"warning","msg":"Unable to get metric statistics due to NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","time":"2021-03-22T11:06:21Z"}`

We build a custom docker image using YACE 26.3, you can view this [here](https://github.com/dwp/cloudwatch-exporter).
Below is the configuration used.
```
discovery:
  exportedTagsOnMetrics:
    lambda:
      - Application
  jobs:
  - type: lambda
    regions:
      - ${region}
    roleArns:
      - ${iam_role} 
    searchTags:
      - key: Application
        value: ^(.*)$
    metrics:
      - name: Invocations
        statistics:
        - Sum
        period: 60
        length: 300
      - name: Throttles
        statistics:
        - Sum
        period: 60
        length: 300
      - name: Duration
        statistics:
        - Max
        period: 60
        length: 300
      - name: ConcurrentExecutions
        statistics:
        - Max
        period: 60
        length: 300
      - name: Errors
        statistics:
        - Sum
        period: 60
        length: 300

static:
  - namespace: EMR/Collections
    name: collections
    regions:
      - ${region}
    metrics:
      - name: AllCollectionsProcessingTime
        statistics:
          - Minimum
        period: 60
        length: 300

  - namespace: AWS/EC2
    name: security
    regions:
      - ${region}
    metrics:
      - name: MetadataNoToken
        statistics:
          - Maximum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Lambda
    name: adgEMRLauncherInvocations
    regions:
      - ${region}
    dimensions:
      - name: FunctionName
        value: adg_emr_launcher
    metrics:
      - name: Invocations
        statistics:
          - Sum
        period: 60
        length: 300
```
