### ISSUE TITLE
EC2 discovery with searchTags does not work

### ISSUE THREAD

**Issue by lgogolin** [nerdswords/yet-another-cloudwatch-exporter#365]
Simply this job just does not work correctly...

```YAML
config:
  discovery:
    exportedTagsOnMetrics:
      ec2:
        - Name
        - cluster
        - service
        - env
    jobs:
    - type: AWS/EC2
      enableMetricData: true
      regions:
        - us-west-2
      searchTags:
        - Key: InstanceFamily
          Value: ^(t2|t3)$
      awsDimensions:
        - InstanceId
      metrics:
        - name: CPUCreditUsage
          statistics:
          - Average
          period: 300
          length: 3600
        - name: CPUCreditBalance
          statistics:
          - Average
          period: 300
          length: 3600
```

returned metrics:
```
# HELP aws_ec2_cpucredit_balance_average Help is not implemented yet.
# TYPE aws_ec2_cpucredit_balance_average gauge
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc05-dev-bastion-ASG",name="global",region="us-west-2"} 864
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc05-v16-master_node-ASG",name="global",region="us-west-2"} 864
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-test-bastion-ASG",name="global",region="us-west-2"} 72
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-compute_worker_node-ASG",name="global",region="us-west-2"} 576
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-master_node-ASG",name="global",region="us-west-2"} 864
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-storage_worker_node-ASG",name="global",region="us-west-2"} 576
# HELP aws_ec2_cpucredit_usage_average Help is not implemented yet.
# TYPE aws_ec2_cpucredit_usage_average gauge
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc05-dev-bastion-ASG",name="global",region="us-west-2"} 0.027776
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc05-v16-master_node-ASG",name="global",region="us-west-2"} 1.0788769999999999
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-test-bastion-ASG",name="global",region="us-west-2"} 0.035522
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-compute_worker_node-ASG",name="global",region="us-west-2"} 0.358226
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-master_node-ASG",name="global",region="us-west-2"} 0.90029
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-storage_worker_node-ASG",name="global",region="us-west-2"} 0.336893
```

even trying forcing dimension (looks like this option was removed or not ? documentation sucks here)

```YAML
discovery:
    exportedTagsOnMetrics:
      ec2:
        - Name
        - cluster
        - service
        - env
    jobs:
    - type: AWS/EC2
      enableMetricData: true
      regions:
        - us-west-2
      searchTags:
        - Key: InstanceFamily
          Value: ^(t2|t3)$
      awsDimensions:
        - InstanceId
      metrics:
        - name: CPUCreditUsage
          statistics:
          - Average
          period: 300
          length: 3600
        - name: CPUCreditBalance
          statistics:
          - Average
          period: 300
          length: 3600
```

it still the same. It only works when searchTags are removed, but then `exportedTagsOnMetrics` option is not honored

```# HELP aws_ec2_cpucredit_balance_average Help is not implemented yet.
# TYPE aws_ec2_cpucredit_balance_average gauge
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxx",dimension_AutoScalingGroupName="",dimension_InstanceId="i-xxxxxxxxxxxxxxxxxxxx",name="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:instance/i-xxxxxxxxxxxxxxxxxxxx",region="us-west-2"} 1296
aws_ec2_cpucredit_balance_average{account_id="xxxxxxxxxxxx",dimension_AutoScalingGroupName="dc05-dev-bastion-ASG",dimension_InstanceId="",name="global",region="us-west-2"} 864

# HELP aws_ec2_cpucredit_usage_average Help is not implemented yet.
# TYPE aws_ec2_cpucredit_usage_average gauge
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxx",dimension_AutoScalingGroupName="",dimension_InstanceId="i-xxxxxxxxxxxxxxxxxxxx",name="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:instance/i-xxxxxxxxxxxxxxxxxxxx",region="us-west-2"} 0.572161
aws_ec2_cpucredit_usage_average{account_id="xxxxxxxxxxxx",dimension_AutoScalingGroupName="dc13-v16-storage_worker_node-ASG",dimension_InstanceId="",name="global",region="us-west-2"} 0.333155

# HELP aws_ec2_info Help is not implemented yet.
# TYPE aws_ec2_info gauge
aws_ec2_info{name="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:instance/i-0007435c3f6c39c0f",tag_Name="dc13-v16-airflow_worker_node",tag_xxxxxxxx_cluster="dc13",tag_xxxxxxxx_env="v16",tag_xxxxxxxx_service="kubernetes_airflow_worker",tag_aws_autoscaling_groupName="dc13-v16-airflow_worker-ASG",tag_cluster="dc13",tag_cluster_name="",tag_env="v16",tag_inventory="",tag_k8s_version="v16",tag_metrics_etcd_port="",tag_metrics_etcd_scrape="",tag_metrics_mongodb_port="",tag_metrics_mongodb_scrape="",tag_metrics_mysql_port="",tag_metrics_mysql_scrape="",tag_metrics_node_port="",tag_metrics_node_scrape="",tag_metrics_rabbitmq_port="",tag_metrics_rabbitmq_scrape="",tag_metrics_redis_port="",tag_metrics_redis_scrape="",tag_node_number="",tag_node_role="airflow",tag_node_schedulable="true",tag_node_type="worker",tag_reference="",tag_role="",tag_service="",tag_service_group="",tag_service_mongo="",tag_service_mongo_replica=""} 0
```

looks like TAGs are added as matrix of all possibilities across all instances 🤦
