### ISSUE TITLE
apigateway metrics with no dimensions

### ISSUE THREAD

**Issue by brunocriado** [nerdswords/yet-another-cloudwatch-exporter#416]
I'm wondering how can I get all dimensions declared on the configuration on apigateway metrics? 

```
discovery:
  jobs:
    - regions:
        - us-east-1
      type: apigateway
      awsDimensions:
        - ApiName
        - Stage
        - Resource
        - Method
      metrics:
        - name: 5XXError
          statistics:
            - Sum
          period: 60
          length: 60
```
What I get:
```
aws_apigateway_5_xxerror_sum{account_id="XXXXXXXXXXX",dimension_ApiName="xxxapinamexxx",name="arn:aws:apigateway:us-east-1::/restapis/xxxapinamexxx",region="us-east-1"} NaN
```
On prometheus, it's scraping each 60s and I've added AIM permissions too.
Thoughts?
