### ISSUE TITLE
searchTags does not work on the latest version

### ISSUE THREAD

**Issue by adrianmiron** [nerdswords/yet-another-cloudwatch-exporter#434]
Hi,

First of all, thanks for a great tool !

I have been using it for a while with the 0.21 version and i have tried today to update to 0.28 , but tag searching seems to have issues. This is the config which used to work : 
```
discovery:
      jobs:
      - type: alb
        regions:
          - {{ .Values.region }}
        searchTags:
          - Key: ManagedBy
            Value: "k8s"
          - Key: Env
            Value: {{ .Values.name }}
        metrics:
          - name: UnHealthyHostCount
            statistics: [Maximum]
            period: 60
            length: 120
```

On the latest version this does return any metrics, unless i remove all the searchTags ( not even .* does not seem to match anything).

Any clues ?

Thanks,
Adrian
