### ISSUE TITLE
`nilToZero` is not returning `0` metrics when no metrics exist in cloudwatch

### ISSUE THREAD

**Issue by smahalingam** [nerdswords/yet-another-cloudwatch-exporter#439]
I tried setting following Yace config,
```apiVersion: v1
kind: ConfigMap
metadata:
 name: yace-configmap
 namespace: monitoring
data:
 config.yml: |
    discovery:
      jobs:
      - type: lambda
        period: 120
        length: 60
        regions:
          - eu-west-2
        metrics:
          - name: Invocations
            statistics:
            - Sum
            nilToZero: true
            addCloudwatchTimestamp: true
          - name: Duration
            statistics:
            - Average
            nilToZero: true
            addCloudwatchTimestamp: true
          - name: Errors
            statistics:
            - Sum
            nilToZero: true
            addCloudwatchTimestamp: true
          - name: IteratorAge
            statistics:
            - Maximum
            nilToZero: true
            addCloudwatchTimestamp: true
          - name: ProvisionedConcurrencySpilloverInvocations
            statistics:
            - Sum
            nilToZero: true
            addCloudwatchTimestamp: true
```
and deployment looks like this 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yace
  template:
    metadata:
      labels:
        name: yace
    spec:
      serviceAccount: prometheus-yace-exporter
      serviceAccountName: prometheus-yace-exporter
      containers:
      - name: yace
        image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.29.0-alpha # release version as tag - Do not forget the version 'v'
        imagePullPolicy: IfNotPresent
        args:
          - "--config.file=/tmp/config/config.yml"
          - "--debug=true"
          - "--scraping-interval=30"
        ports:
        - name: app
          containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/config
      volumes:
      - name: config-volume
        configMap:
          name: yace-configmap
```

Yace is not returning `0` for the metric which doesn't exists in cloudwatch. 

Anything i missed in the config ? Help is appreciated
