### ISSUE TITLE
Unable to collect Cloudwatch Metrics from multiple AWS accounts

### ISSUE THREAD

**Issue by ookangzheng** [nerdswords/yet-another-cloudwatch-exporter#442]
We're using version `v0.30.1-alpha` on AWS Fargate with Kubernetes.

We deploy `yace` on `devops` account, and we want `yace` to have ability of grabbing Lambda metrics from multiple  account (A & B). Furthermore, we configured `devops` account IAM role to assume  account A and account B role, also account A and account B both have corresponds IAM role and trust advisor.

The problem we encounter is that we won't able to collect Account A and Account B Lambda metrics back to DevOps account.

### DevOps account IAM Fargate Role

```
...
{
            "Sid": "",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::<A Account>:role/svc-cw-exporter"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::<B Account>:role/svc-cw-exporter"
        },

```

### Account A and Account B IAM Role
Trusted entities: `arn:aws:iam::<DEVOPS Account>:role/svc-fargate-task-cw-exporter`
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "tag:GetResources",
                "cloudwatch:ListMetrics",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:GetMetricData",
                "apigateway:GET"
            ],
            "Resource": "*"
        }
    ]
}

```

### Configuration YAML

```yaml
apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    ecs-svc:
      - Name
      - Application
      - Environment
      - Team
      - Group
      - Product
      - ApplicationVersion
    lambda:
      - Name
      - type
jobs:
  - type: ecs-svc
    regions:
      - ap-northeast-1
    roleArns:
      - "arn:aws:iam::<DEVOPS Account>:role/svc-fargate-task-cw-exporter"
    searchTags:
      - key: Service
        Value: monitor
    metrics:
      - name: CPUReservation
        statistics:
        - Minimum
        - Maximum
        - Average
        period: 600
        length: 600
 - type: lambda
    regions:
      - ap-northeast-1
    roleArns:
      - "arn:aws:iam::<A Account>:role/svc-cw-exporter"
      - "arn:aws:iam::<B Account>:role/svc-cw-exporter"
    searchTags:
      - key: Application
        Value: cp-api
    metrics:
      - name: Invocations
        statistics:
        - Sum
        period: 600
        length: 600
  - type: lambda
    regions:
      - ap-northeast-1
    roleArns:
      - "arn:aws:iam::<A Account>:role/svc-cw-exporter"
    searchTags:
      - key: aws:cloudformation:stack-name
        Value: api-v2-dev
    metrics:
      - name: Invocations
        statistics:
        - Sum
        period: 600
        length: 600
```

**Comment by ookangzheng** [comment]
any hint or update?

**Comment by thomaspeitz** [comment]
Hey,

can you please run it in debug mode and show me the output?

I currently not really having an idea and thinking about improving logging if the debug output won't help.

Due to the complexity of the setup (spin up eks, set up two accounts) it is hard to debug for me. (doing it in my spare time).

Greetings, Thomas

**Comment by thomaspeitz** [comment]
cc: https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/440

**Comment by ookangzheng** [comment]
Okay, Will let you know tomorrow

**Comment by thomaspeitz** [comment]
Awesome <3 Thanks a lot. Really appreciate it.

**Comment by thomaspeitz** [comment]
```
{"level":"debug","msg":"Skipping resource arn:aws:lambda:ap-northeast-1:906670484956:function:aws-controltower-NotificationForwarder because search tags do not match","time":"2021-09-22T03:25:12Z"}
```

Can you verify your search tags are configured correctly? I do not see any permission error. Looks from my perspective like an issue with tagging of resources.

If that does not help, we can make a quick google meet debugging:
Today: 13:15 - 16:00
Tomorrow: 10:00 - 12:00

Just send me a calendar invite to yace-issue-442@nerdswords.de with a 30 minutes timeslot.

Greetings, Thomas :)

**Comment by ookangzheng** [comment]
@thomaspeitz  which time zone?

**Comment by thomaspeitz** [comment]
```
# Before
    roleArns:
      - "arn:aws:iam::<DEVOPS Account>:role/svc-fargate-task-cw-exporter"
    searchTags:
      - key: Service
        Value: monitor
 # After
    roles:
      - roleArn: "arn:aws:iam::<DEVOPS Account>:role/svc-fargate-task-cw-exporter"
    searchTags:
      - key: Service
        value: monitor
```

Found some small issues in the config. This fixed it.
We had some issues with some Lambda functions but this issue will be raised as a new issue.

Out of the debugging session fell this issue:
https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/457

The frustration of config which is not validated (and looks good but is not) must be fixed with high priority.

Closing this one.
