### ISSUE TITLE
scraping-interval seems to be ignored with discovery config

### ISSUE THREAD

**Issue by DerFels** [nerdswords/yet-another-cloudwatch-exporter#446]
It seems that the scraping-interval parameter only works if you use a `static` config. 
docker-compose.yml:
```
version: '2'

services:
  cloudwatch_exporter:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.30.1-alpha
    command: -debug -scraping-interval 10 -config.file /tmp/config.yml
    env_file:
      - .env
    build: ./
    ports:
      - 5000:5000
```

With `static`:
```
cloudwatch_exporter_1  | {"level":"info","msg":"Parse config..","time":"2021-09-21T12:01:56Z"}
cloudwatch_exporter_1  | {"level":"info","msg":"Startup completed","time":"2021-09-21T12:01:56Z"}
cloudwatch_exporter_1  | {"level":"debug","msg":"Starting scraping async","time":"2021-09-21T12:02:06Z"}
...
```

With `discovery`:
```
cloudwatch_exporter_1  | {"level":"info","msg":"Parse config..","time":"2021-09-21T12:02:49Z"}
cloudwatch_exporter_1  | {"level":"info","msg":"Startup completed","time":"2021-09-21T12:02:49Z"}
cloudwatch_exporter_1  | {"level":"debug","msg":"Starting scraping async","time":"2021-09-21T12:07:48Z"}
...
```
