### ISSUE TITLE
AWS RDS - StartTime and EndTime never change for all scrape requests

### ISSUE THREAD

**Issue by tru-cstavares** [nerdswords/yet-another-cloudwatch-exporter#455]
Hi, 

I installed YACE (v0.31.0-alpha) to scrape AWS RDS metrics. My config is the following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-rds
data:
  config.yml: |-
    ---
    apiVersion: v1alpha1
    discovery:
      jobs:
      - type: rds
        regions:
          - eu-west-1
        enableMetricData: true
        decoupled-scraping: false
        metrics:
          - name: WriteIOPS
            statistics:
            - Average
            length: 120
            period: 60
```

From logs I see a very weird behavior, YACE is correctly asking AWS API each 300s (default value for scrape-interval) but interval of data is always the same, as you can see bellow **EndTime** and **StartTime**:

First API request:
```
2021/09/29 16:54:05 DEBUG: Request monitoring/GetMetricData Details:
Action=GetMetricData&EndTime=2021-09-29T16%3A50%3A00Z&MetricDataQueries.member.1.Id=id_5577006791947...StartTime=2021-09-29T16%3A48%3A00Z&Version=2010-08-01
```
then 300s after new API Request
 
```
2021/09/29 16:59:06 DEBUG: Request monitoring/GetMetricData Details:
Action=GetMetricData&EndTime=2021-09-29T16%3A50%3A00Z&MetricDataQueries.member.1.Id=id_5465989353755...StartTime=2021-09-29T16%3A48%3A00Z&Version=2010-08-01
```
Then 300s after new API Request
```
2021/09/29 17:04:06 DEBUG: Request monitoring/GetMetricData Details:
Action=GetMetricData&EndTime=2021-09-29T16%3A50%3A00Z&MetricDataQueries.member.1.Id=id_6100275367158...StartTime=2021-09-29T16%3A48%3A00Z&Version=2010-08-01
```
and so on.

On Response I see always the same result, this:

```
      <member>
        <Timestamps>
          <member>2021-09-29T16:49:00Z</member>
          <member>2021-09-29T16:48:00Z</member>
        </Timestamps>
        <Values>
          <member>1.500175020419049</member>
          <member>1.433428895259684</member>
        </Values>
        <Label>my-rds WriteIOPS</Label>
```

Can this be related with the fact that period=60s and length=120s?

Thanks.
