### ISSUE TITLE
Cloudfront metrics only exported once

### ISSUE THREAD

**Issue by Jeinhaus** [nerdswords/yet-another-cloudwatch-exporter#461]
I'm using the following config:

```yaml
---
apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    cloudfront:
      - DistributionId
      - Name
  jobs:
    - regions:
        - us-east-1
      type: cloudfront
      length: 180
      period: 60
      metrics:
        - name: Requests
          statistics:
            - Sum
```
and run yace like this `yace -config.file=config.yaml --scraping-interval=60 --debug`.

After first startup the metrics that are returned by `/metrics` then show the correct value that is shown by Cloudwatch.
But every subsequent scrape does not change those initial values (even though the debug log shows that the exporter scraped Cloudwatch and the `yace_cloudwatch_requests_total` increased).

I tried various configuration combinations of `length`, `period`, and `scraping-interval` but to no avail.
Does anyone have a clue how to get this working?
