### ISSUE TITLE
EC2 Tags filtering doesn't work

### ISSUE THREAD

**Issue by arnitolog** [nerdswords/yet-another-cloudwatch-exporter#466]
Hello, 
I have the following config to scrape metrics from instances with tag Product=test:
```     
      - regions:
          - us-east-1
        type: "ec2"
        length: 600
        searchTags:
          - key: Product
            value: test
        metrics:
          - name: CPUCreditBalance
            statistics:
            - 'Minimum'
            period: 300
          - name: CPUUtilization
            statistics:
            - 'Average'
            period: 300 
```

But in Prometheus, I see a lot of metrics with the label `dimension_AutoScalingGroupName` which have tag Product not equal to `test` or even do not have such tag at all.
At the same time, for the correct metrics, there is a label dimension_InstanceId
```
aws_ec2_cpuutilization_average{Environment="dev", Product="test", ProductComponents="ElasticSearch", account_id="xxxxxxx", aws_cluster="dev", aws_region="us-east-1", cluster="dev", component="yace-exporter", container="prometheus-yace-exporter", dimension_InstanceId="i-xxxxxxxxx", endpoint="metrics", job="yace-exporter", namespace="monitoring", region="us-east-1"}
```
in the logs I see the following messages:
```
{"level":"error","msg":"Resource tag list is empty (in 1234567890). Tags must be defined for ec2 to be discovered.","time":"2021-10-13T20:33:46Z"}
{"level":"error","msg":"Resource tag list is empty (in 1234567890). Tags must be defined for ec2 to be discovered.","time":"2021-10-13T20:36:16Z"}
```

Have I missed something in configuration? How to avoid exporters scraping metrics in AutoScalingGroupName dimension, or if it should why filtering on tag doesn't work there?
