### ISSUE TITLE
tag has the same values for all ecs services

### ISSUE THREAD

**Issue by sandangel** [nerdswords/yet-another-cloudwatch-exporter#473]
although ECS services have different tag values, it appeared in Prometheus that all the services have the same tag values.

```yaml
apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    AWS/ECS:
      - tier
      - env
      - app
    ECS/ContainerInsights:
      - tier
      - env
      - app
  jobs:
    - regions:
        - ${region}
      type: ECS/ContainerInsights
      searchTags:
        - key: env
          value: .+
        - key: tier
          value: .+
        - key: app
          value: .+
      metrics:
        - name: CpuUtilized
          statistics:
            - Average
          period: 60
          length: 300
```
