### ISSUE TITLE
[BUG] Running Docker Image on ARM

### ISSUE THREAD

**Issue by jlamande** [nerdswords/yet-another-cloudwatch-exporter#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am deploying the yace Docker image in a Kubernetes Cluster (EKS) on a arm64 node (graviton).

I get the following error (and only the error) in the logs of the container :

```
standard_init_linux.go:228: exec user process caused: exec format error
```

I think that this issue is linked to the Docker image which is only built and published for amd64 processors by default.

amd64 by default :
https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/Dockerfile#L13

no cross build when releasing :
https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/.github/workflows/release.yml#L14

### Expected Behavior

To run correctly on an ARM instance.

### Steps To Reproduce

1. Have a docker running on an arm 64 instance
2. launch a docker run of the image `ghcr.io/nerdswords/yet-another-cloudwatch-exporter`

**Comment by jlamande** [comment]
I confirm that an image built with GOARCH=amd64 resolves the issue.

A cross build amd64 + arm64 would be necessary in the release workflow.

**Comment by thomaspeitz** [comment]
Will fix probably on Thuersday :)

Would be happy for a PR to save me time! <3

**Comment by thomaspeitz** [comment]
@jlamande  - ghcr.io/nerdswords/yet-another-cloudwatch-exporter:support-docker-arm-2021-11-26-v2-arm64 - Does it work for you?

Then I would rebase some things and merge into master and release a new version today.

**Comment by jlamande** [comment]
Hi @thomaspeitz,

Thanks a lot !

Sorry I didn't give you some help. I am not really an user of github actions :/

Working as expected 👍🏻 
```
NAME:
   Yet Another CloudWatch Exporter - YACE configured to retrieve CloudWatch metrics through the AWS API
...
{"level":"info","msg":"Parse config..","time":"2021-11-28T08:20:27Z"}
{"level":"info","msg":"Startup completed","time":"2021-11-28T08:20:27Z"}
```

_Note that the recent changes in 0.32 introduced a strange behavior displaying the usage the command on start but this is another subject._

In fact the better way to obtain multi arch Docker images is certainly to use the `docker buildx` command with multiple architectures.

The most important benefit is to obtain the image with the same name and the same tag but with different architectures. This way, it provides to the docker/containerd/... daemon the ability to take automatically the best image for its current running architecture and this transparently for the users.

As examples these open images have multiple architectures for the same tag :

- https://hub.docker.com/_/golang?tab=tags
- https://hub.docker.com/_/node?tab=tags

The Docker community provided github actions for this : 
- https://github.com/docker/setup-buildx-action
- https://github.com/docker/build-push-action

Sample usage :
```
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: ${{ steps.prep.outputs.tags }}
```

But as I said I am not an advanced user of github actions. I will give a try.

**Comment by jlamande** [comment]
Another feature of `buildx` which could be very useful is to push automatically :

```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ghcr.io/nerdswords/yet-another-cloudwatch-exporter:${{ github.event.release.tag_name }} --build-arg VERSION=${{github.event.release.tag_name}} --push .
```

**Comment by jlamande** [comment]
It could give something like this : 

```
on: release

name: Build, test and publish
jobs:
  buildDockerImage:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - name: Is release published?
      if: github.event.action != 'published'
      run: exit 78
    - uses: actions/checkout@master
    - name: Log into docker
      env:
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: ghcr.io
        DOCKER_USERNAME: ${{ github.actor }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
    - name: Release if tagged
      if: "!startswith(github.ref, 'refs/tags/v')"
      run: exit 78
    - name: Build and Publish docker image
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ghcr.io/nerdswords/yet-another-cloudwatch-exporter:${{ github.event.release.tag_name }} --build-arg VERSION=${{github.event.release.tag_name}} --push .
    - name: Build && release binaries
      uses: docker://goreleaser/goreleaser:v0.179.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
```

with this flow the docker build is done before the goreleaser action, so any issues occuring during the docker build would block the release.
