### ISSUE TITLE
[BUG] DMS metrics not discovered, using incorrect dimension

### ISSUE THREAD

**Issue by nhinds** [nerdswords/yet-another-cloudwatch-exporter#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only `aws_dms_info` metrics are returned from yace when configured for DMS discovery.

### Expected Behavior

All configured DMS metrics should be returned from yace

### Steps To Reproduce

1. Deploy a DMS replication instance with e.g. `ReplicationInstanceIdentifier=my-nice-replication-instance-id` and ARN `arn:aws:dms:us-west-2:<account-id>:rep:<aws-assigned-random-id>`
2. Configure yace to retrieve DMS metrics, e.g.
```
discovery:
  jobs:
  - type: dms
    regions:
    - ap-southeast-2
    roles:
    - roleArn: ""
    searchTags:
    - key: MyTagKey
      value: ^(mytagvalue)$
    length: 1200
    period: 60
    metrics:
    - name: CDCLatencySource
      statistics: [Maximum]
```
3. Scrape metrics from yace - `aws_dms_info{name="arn:aws:dms:us-west-2:<account-id>:rep:<aws-assigned-random-id>"}` is returned for matching DMS replication instances, but not e.g. `aws_dms_cdc_latency_source_maximum`

### Anything else?

The discovery retrieves an ARN from the resource groups API like `arn:aws:dms:us-west-2:<account-id>:rep:<aws-assigned-random-id>` and tries to look for DMS metrics with dimension `ReplicationInstanceIdentifier=<aws-assigned-random-id>`. Unfortunately the `<aws-assigned-random-id>` part of the ARN does not necessarily match the `ReplicationInstanceIdentifier`, which can be set by users to e.g. `my-nice-replication-instance-id`. When yace looks for DMS metrics with the ID from the ARN, in my environment it is unable to find the metics.

It doesn't look like the replication instance identifier can be retrieved from the resource groups API directly.
