### ISSUE TITLE
How to get API Gateway 4XX / 5XX Error metrics

### ISSUE THREAD

**Issue by ookangzheng** [nerdswords/yet-another-cloudwatch-exporter#486]
I'm trying to calculate SLO and error budget via YACE. But I couldn't grab API Gateway 4xx, 5xx metrics from YACE. 
Inside CLI or Grafana Prometheus, I cannot find API gateway 4xx or 5xx error.
Is there any step or something I messed up with?

Screenshot below

![Screen Shot 2021-11-24 at 16 13 27](https://user-images.githubusercontent.com/6301735/143200877-424c8148-3d3c-441f-b0a4-77b2991d3b88.png)

Running environment
1. Cross-account
2. version: v0.32
3. AWS Fargate
4. Terraform deploy

Thanks

**Comment by aleslash** [comment]
Here we are using like this and its working fine.
![image](https://user-images.githubusercontent.com/2106871/143484503-906eb983-3a7e-47ee-ab64-280189473753.png)

Running environment:
1- cross-account
2- version v0.32
3- AWS ECS Fargate
4- Codepipeline deploy

**Comment by ookangzheng** [comment]
Somehow to get it working I have to add dimension to the config

```
  - type: apigateway
    regions:
      - ap-northeast-1
    roles:
      - roleArn: "arn:aws:iam::1234567890:role/svc-cw-exporter"
    searchTags:
      - key: Name
        value: api-v1
    awsDimensions:
        - ApiName
        - Stage
        - Resource
        - Method
    metrics:
      - name: Count
        statistics:
        - Sum
        period: 600
        length: 600
      - name: IntegrationLatency
        statistics:
        - Average
        period: 600
        length: 600
      - name: 4XXError
        statistics:
        - Sum
        period: 600
        length: 600
      - name: 5XXError
        statistics:
        - Sum
        period: 600
        length: 600
```
