### ISSUE TITLE
[FEATURE] Support custom namespace

### ISSUE THREAD

**Issue by ywyt738** [nerdswords/yet-another-cloudwatch-exporter#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

How to get metrics from custom namespace, eg. CWAgent

**Comment by guypATstarsgroup** [comment]
for static you can do the following

- namespace: service-metrics
      name: service-metrics1
      regions:
      - eu-west-1
      dimensions:
      - name: StatusCode
        value: 500
      metrics:
      - name: QueryDuration
        statistics:
        - Average
        - Maximum
        - SampleCount
        period: 60
        length: 300

when looking in prometheus the metric will be made available with the addition of aws_ before the metric name i.e aws_service_metrics_count_sample_count

**Comment by NickLarsenNZ** [comment]
This doesn't work for me, my custom namespace has a `/` in it.

```yml
apiVersion: v1alpha1
static:
- namespace: App/Part
  name: system-metrics # not sure what this is for
  regions:
  - af-south-1
  roles:
  - roleArn: arn:aws:iam::...
  - roleArn: arn:aws:iam::...
  dimensions:
  - name: environment
    value: uat
  metrics:
  - name: Mem.used
    statistics: [Minimum, Maximum]
    period: 60
    length: 120
  - name: Mem.total
    statistics: [Minimum, Maximum]
    period: 60
    length: 120
  - name: cpu_p
    statistics: [Minimum, Maximum]
    period: 60
    length: 120
  - name: user_p
    statistics: [Minimum, Maximum]
    period: 60
    length: 120
  - name: system_p
    statistics: [Minimum, Maximum]
    period: 60
    length: 120
```

With debug on, I see a 200 Ok response back, just no metics.

```
2022/02/15 23:22:02 DEBUG: Response monitoring/GetMetricStatistics Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 332
Content-Type: text/xml
Date: Tue, 15 Feb 2022 23:22:02 GMT
X-Amzn-Requestid: fdcd...


-----------------------------------------------------
2022/02/15 23:22:02 <GetMetricStatisticsResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <GetMetricStatisticsResult>
    <Datapoints/>
    <Label>Mem.total</Label>
  </GetMetricStatisticsResult>
  <ResponseMetadata>
    <RequestId>fdcd...</RequestId>
  </ResponseMetadata>
</GetMetricStatisticsResponse>

{"level":"debug","msg":"{\n  Label: \"Mem.total\"\n}","time":"2022-02-15T23:22:02Z"}
{"level":"debug","msg":"Metrics scraped.","time":"2022-02-15T23:22:02Z"}
```
