### ISSUE TITLE
Showing statically configured metrics with more than one dimension of the same name

### ISSUE THREAD

**Issue by wanieldilson** [nerdswords/yet-another-cloudwatch-exporter#497]
We have a metric that is available on more than one dimension (primary and standby containers)  is it possible to configure both in one block?

Config

```
- namespace: Custom-Namespace   
  name: "Name"   
  regions: [eu-west-2]   
  dimensions:   
  - name: Server     
  - value: primary
  - name: Server
  - value: standby
  metrics:
  - name: custom-metric-name
    statistics: [Average, Sum]
    nilToZero: true
    period: 300
    length: 300

```

Expected output

```

# HELP aws_custom_metric_name_average Help is not implemented yet.
# TYPE aws_custom_metric_name_average gauge
aws_custom_metric_name_average{account_id="############",dimension_Server="primary",name="Name",region="eu-west-2"} _metric_value_
aws_custom_metric_name_average{account_id="############",dimension_Server="standby",name="Name",region="eu-west-2"} _metric_value_

```

Actual config (that works, but can only see output from one server)

```
- namespace: Custom-Namespace   
  name: "Name"   
  regions: [eu-west-2]   
  dimensions:   
  - name: Server     
  - value: primary
  metrics:
  - name: custom-metric-name
    statistics: [Average, Sum]
    nilToZero: true
    period: 300
    length: 300

```

We already tried

```
dimensions
name : Server
Value:
- primary
- standby

```

```
dimensions
name: Server
Value: .* and * (both didn't work)

```
