### ISSUE TITLE
[BUG] period ignored in config

### ISSUE THREAD

**Issue by maratsh** [nerdswords/yet-another-cloudwatch-exporter#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cloudwatch metric scraping happens once in 5m

### Expected Behavior

scraping schould happen every 60s

### Steps To Reproduce

```
    apiVersion: v1alpha1
    discovery:
      jobs:
        - regions:
            - {{ .Values.region }}
          type: elb
          metrics:
            - name: BackendConnectionErrors
              statistics:
              - Sum
              period: 60
              length: 3600
...
20+ other jobs with the same period and length
```

cmd options:
```
- "--config.file=/exporter/config/config.yml"
```
