### ISSUE TITLE
[BUG] Metrics NaN periodically

### ISSUE THREAD

**Issue by marekhanzlik** [nerdswords/yet-another-cloudwatch-exporter#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Metrics are returning `NaN` periodically
My config 
```
--scraping-interval=600
```
```
- type: ses
    period: 60
    length: 600
```
(tried period 600, lenght 600)
![image](https://user-images.githubusercontent.com/1983577/148786775-e975b722-0fbe-4742-a1d3-557b94df06cf.png)

Between 13:55 and 14:25 there was a restart of `yace` so the metrics hold for a little longer but then breaks anyway
Because of this, my alertmanager fires alert, then have no data so goes back to OK state and after 10 minutes triggers the error again which is noisy

**Comment by GataullinRR** [comment]
Same problem for me
Would be great to fix that

**Comment by simmessa** [comment]
Seeing this on 0.33.0-alpha and also after switching to 0.34.0-alpha, I'm using yace only for AWS/ApiGateway metrics at the moment but it's full of NaN values.

I've checked other issues with similar problems, like the closed #378 and even after specifying a length bigger than period I'm still seeing this, here's an example from my current config:

```
[...]
      jobs:

      # Api Gateway Metrics

      - type: AWS/ApiGateway
        regions:
          - eu-south-1
        metrics:
          - name: Count
            statistics:
            - SampleCount # same as Sum here
            period: 60
            length: 600
          - name: Latency
            statistics:
            - Average
            - p95
            period: 60
            length: 600
[...]
```
Does anybody know why we're getting this? Any clues?

Thank you,
Simone.
