### ISSUE TITLE
[BUG] Percentiles Stats throws error on static configuration

### ISSUE THREAD

**Issue by rajiv-g** [nerdswords/yet-another-cloudwatch-exporter#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the below configuration to extract the percentile stats from ALB 
```
static:
  - namespace: AWS/ApplicationELB
    name: test
    regions:
      - us-east-1
    roles:
      - roleARN: XXX
    dimensions:
     - name: LoadBalancer
       value: YYY
    metrics:
      - name: TargetResponseTime
        statistics:
        - p95
        period: 300
        length: 1800
```

But got the following error:
```
{"level":"info","msg":"Parse config..","time":"2022-01-21T14:06:01Z"}
{"level":"info","msg":"Startup completed","time":"2022-01-21T14:06:01Z"}
panic: runtime error: index out of range [0] with length 0

goroutine 204 [running]:
github.com/nerdswords/yet-another-cloudwatch-exporter/pkg.createGetMetricStatisticsInput({0xc0004b8430, 0x1, 0x0}, 0xc00007da80, 0xc000201040)
	/opt/pkg/aws_cloudwatch.go:82 +0x698
github.com/nerdswords/yet-another-cloudwatch-exporter/pkg.scrapeStaticJob.func1()
	/opt/pkg/abstract.go:122 +0x2eb
created by github.com/nerdswords/yet-another-cloudwatch-exporter/pkg.scrapeStaticJob
	/opt/pkg/abstract.go:100 +0xe5
```

### Expected Behavior

It needs to scrape the percentile stats without error for static configuration

### Steps To Reproduce

1. Use the following configuration:

```
apiVersion: v1alpha1
discovery:
static:
  - namespace: AWS/ApplicationELB
    name: amplify
    regions:
      - us-east-1
    roles:
      - roleARN: XXX
    dimensions:
     - name: LoadBalancer
       value: YYY
    metrics:
      - name: TargetResponseTime
        statistics:
        - p95
        - Average
        period: 300
        length: 1800
```
2. Exporter version: v0.33.0-alpha

### Anything else?

When I use additional stats along with percentile it works
Example:

```
static:
  - namespace: AWS/ApplicationELB
    name: test
    regions:
      - us-east-1
    roles:
      - roleARN: XXX
    dimensions:
     - name: LoadBalancer
       value: YYY
    metrics:
      - name: TargetResponseTime
        statistics:
        - p95
        - Sum
        period: 300
        length: 1800
```
