### ISSUE TITLE
addCloudwatchTimestamp blocks zero metrics

### ISSUE THREAD

**Issue by johnlane** [nerdswords/yet-another-cloudwatch-exporter#524]
I had a problem where I was not getting zero metrics published despite having `nilToZero: true`. I discovered that having `addCloudwatchTimestamp: true` [stops it publishing zero metrics](https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/437/commits/8d2f6c28ae6e07b8e3048331ec98807c29c6c1b7). As it's explicitly coded to work like that I expect there is a reason for this that is not clear to me. I couldn't find an explanation in the documentation, perhaps this could be clarified ?

**Comment by guypATstarsgroup** [comment]
i also experienced exactly the same issue which has made the addCloudwatchTimestamp function unusable as this creates multiple metrics with zero data.

**Comment by deybhayden** [comment]
I also have been bit by this. Current example is `aws_alb_httpcode_elb_5_xx_count_sum` - my application has produced no 5xx, but instead of YACE returning 0, it's not reporting the metric at all.

Version: v0.38.0-alpha
My config looks like:

```yaml
apiVersion: v1alpha1
discovery:
  jobs:
  - regions: 
    - us-east-1
    type: alb
    addCloudwatchTimestamp: true
    metrics:
      - name: ActiveConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ClientTLSNegotiationErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ConsumedLCUs
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: HTTP_Fixed_Response_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTP_Redirect_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTP_Redirect_Url_Limit_Exceeded_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_3XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_4XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_5XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_500_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_502_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_503_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_ELB_504_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: IPv6ProcessedBytes
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: IPv6RequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: NewConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ProcessedBytes
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RejectedConnectionCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: RequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RuleEvaluations
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ELBAuthError
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthFailure
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthLatency
        statistics:
        - Average
        period: 300
        length: 3600
      - name: ELBAuthRefreshTokenSuccess
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthSuccess
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: ELBAuthUserClaimsSizeExceeded
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
  - regions: 
    - us-east-1
    type: alb
    addCloudwatchTimestamp: true
    awsDimensions:
      - AvailabilityZone
    metrics:
      - name: DroppedInvalidHeaderRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: ForwardedInvalidHeaderRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
  - regions: 
    - us-east-1
    type: alb
    addCloudwatchTimestamp: true
    awsDimensions:
      - TargetGroup
    metrics:
      - name: HealthyHostCount
        statistics:
        - Average
        period: 300
        length: 3600
      - name: HTTPCode_Target_2XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_3XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_4XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: HTTPCode_Target_5XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: NonStickyRequestCount
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: RequestCountPerTarget
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: TargetConnectionErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: TargetResponseTime
        statistics:
        - p95
        period: 300
        length: 3600
      - name: TargetTLSNegotiationErrorCount
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true
      - name: UnHealthyHostCount
        statistics:
        - Average
        period: 300
        length: 3600
```
