### ISSUE TITLE
Add AWS/PrivateLink to YACE exporter

### ISSUE THREAD

**Issue by aslamkhan-dremio** [nerdswords/yet-another-cloudwatch-exporter#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS introduced cloudwatch metrics for PrivateLink  : https://docs.aws.amazon.com/vpc/latest/privatelink/privatelink-cloudwatch-metrics.html

It is good to include AWS/PrivateLinkServices namespace as well to discovery.

### What might the configuration look like?

```
regions:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - ca-central-1
          - eu-central-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
        metrics:
          - name: ActiveConnections
            statistics: [Sum,Average,Minimum,Maximum]
            period: 600
            length: 600
            nilToZero: true
          - name: NewConnections
            statistics: [Sum,Average,Minimum,Maximum]
            period: 600
            length: 600
            nilToZero: true
          - name: BytesProcessed
            statistics: [Sum,Average,Minimum,Maximum]
            period: 600
            length: 600
            nilToZero: true
          - name: EndpointsCount
            statistics: [Sum,Average,Minimum,Maximum]
            period: 600
            length: 600
            nilToZero: true
          - name: RstPacketsSent
            statistics: [Sum,Average,Minimum,Maximum]
            period: 600
            length: 600
            nilToZero: true
```
