### ISSUE TITLE
[FEATURE] support Airflow

### ISSUE THREAD

**Issue by sdenham** [nerdswords/yet-another-cloudwatch-exporter#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS Introduced [Amazon Managed Workflows for Apache Airflow (MWAA)](https://docs.aws.amazon.com/mwaa/latest/userguide/what-is-mwaa.html).
It produces metrics in the _AmazonMWAA_ namespace.

### What might the configuration look like?

```yml
discovery:
  jobs:
  - type: airflow
    period: 30
    length: 600
    metrics:
    - name: DAGDurationSuccess
      statistics: [Minimum, Maximum]
```
