### ISSUE TITLE
[FEATURE] Allow auto-discovery jobs to filter dimension combinations

### ISSUE THREAD

**Issue by jutley** [nerdswords/yet-another-cloudwatch-exporter#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When configuring auto-discovery jobs, I would like to provide the dimension combinations I am or am not interested in. This can allow us to significantly reduce the number of metrics that we pull from CloudWatch, which will help reduce the CloudWatch bill.

For example, for ALB metrics, if I don't care about per-AZ dimensionality, I can significantly reduce the number of requested data points by not requesting them.

### What might the configuration look like?

```yaml
  - type: alb
    regions:
      - eu-west-1
    searchTags:
      - key: kubernetes.io/service-name
        value: .*
    dimensions:
      - LoadBalancer
      - TargetGroup
      # Not AvailabilityZone!
    metrics:
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 60
        length: 600
```

### Anything else?

This is functionality we had with cloudwatch-exporter. While YACE seems to be much better in most regards, this is definitely something I am missing. I imagine others will run into similar concerns.
