### ISSUE TITLE
[FEATURE] Support for Amazon Prometheus

### ISSUE THREAD

**Issue by romich** [nerdswords/yet-another-cloudwatch-exporter#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Would be nice to support recently-released Amazon Prometheus (AMP) CloudWatch metrics.
https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-CW-usage-metrics.html

### What might the configuration look like?

```yml
discovery:
  jobs:
  - type: amp
    period: 60
    length: 600
    metrics:
    - name: IngestionRate
      statistics: [Average]
```
