### ISSUE TITLE
[BUG] CPU Metric of RDS not correct

### ISSUE THREAD

**Issue by tieungao88** [nerdswords/yet-another-cloudwatch-exporter#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used yet-another-cloudwatch-exporter for monitor RDS but metric yace (yet-another-cloudwatch-exporter) collect is not match with cloudwatch metric.
Detail with CPU metric:
In yace: 9.23% but in cloudwatch: 9.45%, period: 60s.
This is my config:
```
  - type: rds
    enableMetricData: true
    regions:
      - ap-southeast-1
    roles:
      - roleArn: "arn:aws:iam::xxxxxxx:role/xxxx-yace-cloudwatch-role"
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        period: 60
        length: 60
```

Thanks.
