### ISSUE TITLE
[BUG] IAM/STS auth for k8s service accounts is not working 

### ISSUE THREAD

**Issue by arjunnayak** [nerdswords/yet-another-cloudwatch-exporter#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy YACE with the IAMRole for service accounts setup, documented [here](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/). i'm fairly sure i've done the right setup, since the call to `sts:AssumeRoleWithWebIdentity` works, but for some reason, the pod is issuing a subsequent request to `sts:AssumeRole` with the session token that fails (which I presume is done by the aws lib's STS provider) and we get the error:

```
User: arn:aws:sts::448435121187:assumed-role/yace/1658973178631034062 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::448435121187:role/yace
```

I'm wondering if this subsequent request is done by the underling AWS lib STS provider, or by YACE session code? Shouldn't the token retrieved by `sts:AssumeRoleWithWebIdentity` be sufficient to call cloudwatch apis?

Some additional context:

Pod definition:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: yace
    name: yace
  name: yace-695f5849f6-2sb5x
  namespace: observability
spec:
  containers:
  - args:
    - --config.file=/tmp/config.yml
    - --debug=true
    env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: us-east-1
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::REDACTED_ACCT_ID:role/yace
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: REDACTED_ACCT_ID.dkr.ecr.us-east-1.amazonaws.com/observability:yace-v0.38.0-alpha
    imagePullPolicy: IfNotPresent
    name: yace
    ports:
    - containerPort: 5000
      name: app
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-q84dl
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: REDACTED_NODE
  preemptionPolicy: PreemptLowerPriority
  priority: 200000000
  priorityClassName: cosmos-default
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: yace
  serviceAccountName: yace
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - configMap:
      defaultMode: 420
      name: yace
    name: config-volume
  - name: kube-api-access-q84dl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

And here are the debug logs
```
{"level":"info","msg":"Parse config..","time":"2022-07-28T01:52:58Z"}
{"level":"info","msg":"Startup completed","time":"2022-07-28T01:52:58Z"}
{"level":"debug","msg":"Starting scraping async","time":"2022-07-28T01:52:58Z"}
{"level":"debug","msg":"Scrape initially first time","time":"2022-07-28T01:52:58Z"}
2022/07/28 01:52:58 DEBUG: Request sts/AssumeRoleWithWebIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.47 (go1.18.4; linux; amd64)
Content-Length: 1256
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept-Encoding: gzip

Action=AssumeRoleWithWebIdentity&RoleArn=arn%3Aaws%3Aiam%3A%3AREDACTED_ACCT_ID%3Arole%2Fyace&RoleSessionName=1658973178631034062&Version=2011-06-15&WebIdentityToken=REDACTED_WEB_IDENTITY_TOKEN
-----------------------------------------------------
2022/07/28 01:53:03 DEBUG: Response sts/AssumeRoleWithWebIdentity Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 2314
Content-Type: text/xml
Date: Thu, 28 Jul 2022 01:53:03 GMT
X-Amzn-Requestid: 8d1fa3e2-8074-4bb2-9b9d-19c0e3dfbe93


-----------------------------------------------------
2022/07/28 01:53:03 <AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <AssumeRoleWithWebIdentityResult>
    <Audience>sts.amazonaws.com</Audience>
    <AssumedRoleUser>
      <AssumedRoleId>AROAWQ2GQ5QRSJHG43OSO:1658973178631034062</AssumedRoleId>
      <Arn>arn:aws:sts::REDACTED_ACCT_ID:assumed-role/yace/1658973178631034062</Arn>
    </AssumedRoleUser>
    <Provider>arn:aws:iam::REDACTED_ACCT_ID:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/REDACTED_PROVIDER_ID</Provider>
    <Credentials>
      <AccessKeyId>REDACTED</AccessKeyId>
      <SecretAccessKey>REDACTED</SecretAccessKey>
      <SessionToken>REDACTED</SessionToken>
      <Expiration>2022-07-28T02:53:03Z</Expiration>
    </Credentials>
    <SubjectFromWebIdentityToken>system:serviceaccount:observability:yace</SubjectFromWebIdentityToken>
  </AssumeRoleWithWebIdentityResult>
  <ResponseMetadata>
    <RequestId>8d1fa3e2-8074-4bb2-9b9d-19c0e3dfbe93</RequestId>
  </ResponseMetadata>
</AssumeRoleWithWebIdentityResponse>

2022/07/28 01:53:03 DEBUG: Request sts/AssumeRole Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.47 (go1.18.4; linux; amd64)
Content-Length: 250
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20220728/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=fef50e37f3a096b0a1b0509af5e4990f322567e49f1f5c4e4557a5135f709b38
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20220728T015258Z
X-Amz-Security-Token: REDACTED
Accept-Encoding: gzip

Action=AssumeRole&DurationSeconds=900&RoleArn=arn%3Aaws%3Aiam%3A%3AREDACTED_ACCT_ID%3Arole%2Fyace&RoleSessionName=1658973178630967500&Version=2011-06-15
-----------------------------------------------------
2022/07/28 01:53:03 DEBUG: Response sts/AssumeRole Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Content-Length: 551
Content-Type: text/xml
Date: Thu, 28 Jul 2022 01:53:03 GMT
X-Amzn-Requestid: 4bd10d6c-fa4f-4852-a266-1ad145f34860


-----------------------------------------------------
2022/07/28 01:53:03 <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>User: arn:aws:sts::REDACTED_ACCT_ID:assumed-role/yace/1658973178631034062 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED_ACCT_ID:role/yace</Message>
  </Error>
  <RequestId>4bd10d6c-fa4f-4852-a266-1ad145f34860</RequestId>
</ErrorResponse>

{"arn":"arn:aws:iam::REDACTED_ACCT_ID:role/yace","error":"AccessDenied: User: arn:aws:sts::REDACTED_ACCT_ID:assumed-role/yace/1658973178631034062 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED_ACCT_ID:role/yace\n\tstatus code: 403, request id: 4bd10d6c-fa4f-4852-a266-1ad145f34860","job_type":"kinesis","level":"error","msg":"Couldn't get account Id","region":"us-east-1","time":"2022-07-28T01:53:03Z"}
{"level":"debug","msg":"Metrics scraped.","time":"2022-07-28T01:53:03Z"}
{"level":"debug","msg":"Scraping every 300 seconds","time":"2022-07-28T01:53:03Z"}
```

YACE Config
```
apiVersion: v1alpha1
discovery:
  jobs:
  - type: kinesis
    regions:
      - us-east-1
    roles:
      - roleArn: "arn:aws:iam::REDACTED_ACCT_ID:role/yace"
    searchTags:
      - key: environment
        value: stage
    metrics:
      - name: PutRecords.Success
        statistics:
        - Sum
        period: 60
        length: 300
```
