### ISSUE TITLE
Searchtags do not work for Amazonmq

### ISSUE THREAD

**Issue by rasr12** [nerdswords/yet-another-cloudwatch-exporter#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following configmap created for amazonmq collection
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-yace-exporter
  namespace: openshift-monitoring
data:
  config.yml: |-
    ---
    apiVersion: v1alpha1
    sts-endpoint: <region>
    discovery:
      exportedTagsOnMetrics:
        mq:
          - Name
          - cluster
      jobs:
        - type: AWS/AmazonMQ
          regions:
            - <region>
          searchTags:
            - key: cluster
              value: <system>
          metrics:
            - name: RabbitMQDiskFree
              statistics:
                - Average
              period: 60
              length: 300
            - name: RabbitMQDiskFreeLimit
              statistics:
                - Average
              period: 60
              length: 300
```

however, all mq brokers are sent to prometheus:

<img width="1375" alt="amazonmq" src="https://user-images.githubusercontent.com/58571456/185966166-0701d135-549f-44b6-92c8-0538d9105dbb.png">

on the logs it can be seen that it skips the non-matching resource:

{"account":"xxxxxxxxx","arn":"","job_type":"AWS/AmazonMQ","level":"debug","msg":"Skipping resource because search tags do not match","region":"eu-north-1","time":"2022-08-20T03:09:54Z"}

however, at some point this ignored and it ends up sending all brokers to prometheus

This does not happen for other resources like RDS, elasticsearch, etc

### Expected Behavior

Amazonmq should respect the searchtags parameter and only send to prometheus the matching brokers/nodes

### Steps To Reproduce

create a configmap that uses searchtags for amazonmq
