### ISSUE TITLE
AWS service discovery with searchTags does not work

### ISSUE THREAD

**Issue by Jeremydozzy** [nerdswords/yet-another-cloudwatch-exporter#647]
I am trying to scrape metrics from AWS Cloudwatch to prometheus ; I configured both “Job” for S3 and “Static” for EC2. I have metrics for the Static configuration (aws_ec2_cpuutilization_minimum{account_id=“**********,custom_tag_Service=“*****”,dimension_AutoScalingGroupName=“*******”,name=“******,region="us-west-2”} 2.035 ) but not having metrics from the Job configuration. I have used the tag associated with the S3 bucket  but I don’t get metics for S3. I don’t know what is missing at this point. Could someone please assist me on this ? Please see my configuration below:
```
 apiVersion: v1
kind: ConfigMap
metadata:
  name: yace
  namespace: monitoring
data:
  config.yml: |-  
    apiVersion: v1alpha1
    sts-endpoint: us-west-2
    discovery:
        exportedTagsOnMetrics:
          s3:
            - Name
    jobs:
    - type: s3
      regions: 
        - us-west-2
      searchTags:
        - key: env
          value: staging
      metrics: 
        - name: NumberOfObjects
          statistics:
            - Average
          period: 86400
          length: 172800
        - name: BucketSizeBytes
          statistics:
            - Average
          period: 86400
          length: 172800

    static:
      - namespace: AWS/EC2
        name: ****************
        regions:
          - us-west-2
        dimensions:
         - name: AutoScalingGroupName
           value: test
        customTags:
          - key: env
            value: dev
        metrics:
          - name: CPUUtilization
            statistics:
            - Minimum
            period: 60
            length: 300

 ```
