### ISSUE TITLE
[BUG] Metric Missing when upgrading from 0.38 to 0.39

### ISSUE THREAD

**Issue by mloiseleur** [nerdswords/yet-another-cloudwatch-exporter#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the same config, a dynamic metric is missing after the update : `StorageBytes` on `AWS/EFS`. 

It seems to be related to the dimensions filter and the fact that, as [documented by AWS](https://docs.aws.amazon.com/efs/latest/ug/efs-metrics.html), this specific metric comes with an other Dimension.

It seems to be related to this [Pull Request](https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/621) from @femiagbabiaka.

The metric comes with two dimensions
```xml
    <Metrics>
      <member>
        <Namespace>AWS/EFS</Namespace>
        <MetricName>StorageBytes</MetricName>
        <Dimensions>
          <member>
            <Name>StorageClass</Name>
            <Value>Total</Value>
          </member>
          <member>
            <Name>FileSystemId</Name>
            <Value>fs-xxxxxxxxxxxxxxxxx</Value>
          </member>
        </Dimensions>
      </member>
      [...]
```

And the dimensionsFilter discovered has only one filer, on FileSystemId, so it skips the metrics [on this line](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/aws_cloudwatch.go#L333).

It was also reported in this comment by @rasr12 in https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/643#issuecomment-1222581687_

### Expected Behavior

The `StorageSize` metric (and probably others with the same issue) still works on new release

### Steps To Reproduce

With this config, it does not work:
```yaml
---
apiVersion: v1alpha1
sts-endpoint: eu-north-1
discovery:
  jobs:
  - type: efs
    regions:
      - eu-west-1
      - eu-west-2
    metrics:
      - name: ClientConnections
        statistics:
          - Sum
        period: 60
        length: 300
      - name: "StorageBytes"
        statistics:
          - Average
        period: 900
        length: 3600
```

### Anything else?

I managed to workaround this issue by using static configuration, which allows to specify dimensions :
```yaml
static:
  - namespace: AWS/EFS
    name: arn:aws:elasticfilesystem:eu-west-2:XXXXXXXXXXX:file-system/fs-xxxxxxxxxxxxxxxxx
    regions:
      - eu-west-2
    dimensions:
      - name: StorageClass
        value: Standard
      - name: FileSystemId
        value: fs-xxxxxxxxxxxxxxxxx
    metrics:
      - name: "StorageBytes"
        statistics:
          - Average
        period: 900 
        length: 3600
```
