### ISSUE TITLE
[BUG] Cloudfront metrics missing in v0.39.0-alpha

### ISSUE THREAD

**Issue by strangeman** [nerdswords/yet-another-cloudwatch-exporter#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

yet-another-cloudwatch-exporter:v0.39.0-alpha doesn't return any Cloudfront-related metrics, only internal yace metrics.

### Expected Behavior

yet-another-cloudwatch-exporter:v0.38.0-alpha working correctly with the same config and returns all needed metrics.

### Steps To Reproduce

I used minimal config:
```
# Start of config file
apiVersion: v1alpha1
discovery:
  jobs:
  - type: cloudfront
    enableMetricData: true
    regions:
      - us-east-1
    additionalDimensions:
      - DistributionId
      - Region
    metrics:
      - name: Requests
        statistics:
        - Sum
        period: 60
        length: 600
        nilToZero: true
```

`docker run --rm -v /home/user/.aws/credentials:/exporter/.aws/credentials -v $PWD/config.yml:/tmp/config.yml -p 5000:5000 --name yace ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.38.0-alpha` - working OK

`docker run --rm -v /home/user/.aws/credentials:/exporter/.aws/credentials -v $PWD/config.yml:/tmp/config.yml -p 5000:5000 --name yace ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.39.0-alpha` - doesn't return any cloudfront-related metrics
