### ISSUE TITLE
[FEATURE] Role account friendly name

### ISSUE THREAD

**Issue by LowLevel96** [nerdswords/yet-another-cloudwatch-exporter#669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When using multiple roles, label account_id is populated as a label in a metric, however there is no support for an user friendly name. Currently i have around 10 AWS accounts, so differentiating between them based on account_id is difficult. We can either use `externalId` value to add as a label in a metric, or we can introduce a new field `name` under roles.

### What might the configuration look like?

```    
discovery:
  jobs:
  - type: rds
    roles:
      - roleArn: "arn:aws:iam::<account_id>:role/platform/grafana_cloudwatch_access"
        externalId: "internal1"
      - roleArn: "arn:aws:iam::<account_id>:role/platform/grafana_cloudwatch_access"
        externalId: "workload1"
```

or

```    
discovery:
  jobs:
  - type: rds
    roles:
      - roleArn: "arn:aws:iam::<account_id>:role/platform/grafana_cloudwatch_access"
        name: "internal1"
        externalId: "internal1"
      - roleArn: "arn:aws:iam::<account_id>:role/platform/grafana_cloudwatch_access"
        name: "workload1"
        externalId: "workload1"
```

**Comment by cristiangreco** [comment]
Hey @LowLevel96, I think this is better achieved with relabeling at scrape time with something like:

```yml
      metric_relabel_configs:
        - source_labels: ["account_id"]
          regex: "1234567890"
          replacement: "workload1"
          target_label: "account_name"
          action: replace
```

This is a good source of [examples](https://grafana.com/blog/2022/03/21/how-relabeling-in-prometheus-works/) for relabeling settings.
