### ISSUE TITLE
[FEATURE] Add support for Amazon Managed Prometheus Metrics alongwith AWS/Usage metrics

### ISSUE THREAD

**Issue by datsabk** [nerdswords/yet-another-cloudwatch-exporter#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add the support to fetch Amazon managed prometheus metrics as presented in this [link](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-CW-usage-metrics.html)

### What might the configuration look like?

```yml
- type: amp
    regions:
      - eu-west-1
    metrics:
      - name: DiscardedSamples
        statistics:
        - Sum
        period: 60
        length: 600
```
