### ISSUE TITLE
ALB "HTTPCode_Target_5XX_Count" value is not updated correctly.

### ISSUE THREAD

**Issue by alexei-bykovski** [nerdswords/yet-another-cloudwatch-exporter#686]
ALB "HTTPCode_Target_5XX_Count" value changes only if the CloudWatch value has been changed to another(other than 0).

Current Behavior:
When the value changes in CloudWatch, I see that the value also changes in prometheus. After the value changes to 0 in CloudWatch, in prometheus I see the same value that was before (is doesn't change). And then the value in prometheus changes only if it changes to other (not 0) in CloudWatch. So, for example if I have 4 errors, I have the same value until it changes to 2. Then I have value 2 throughout the rest of the time period.

Expected Behavior:
When the value changes to 0 in CloudWatch, the value in prometheus also changes to 0, not stays the same until it changes to other (not 0).

<img width="880" alt="cloudwatch" src="https://user-images.githubusercontent.com/11819387/195343855-8ca48b28-ae7d-4840-8d51-29a7d6841d75.png">
<img width="1424" alt="prometheus" src="https://user-images.githubusercontent.com/11819387/195343876-d6adbe05-b8b0-416f-9fb2-30bc13a99f12.png">

Config:

```
discovery:
  jobs:
    - regions:
        - us-east-1
      type: alb
      metrics:
        - name: HTTPCode_Target_5XX_Count
          statistics:
            - Sum
          period: 60
          length: 60
          nilToZero: true
```
