### ISSUE TITLE
[BUG] SQS metrics not picked up by Prometheus

### ISSUE THREAD

**Issue by majandres** [nerdswords/yet-another-cloudwatch-exporter#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

First I want to say that I appreciate the work that is going into this exporter!  Fantastic job.

Now, I'm running into a bit of an issue with SQS metrics.  I'm Running with yace v0.40. and i've configured a static configuration:
```
apiVersion: v1alpha1
sts-endpoint: us-east-1
static:
  - namespace: AWS/SQS
    name: my_queue_name.fifo
    regions:
      - us-east-1
    dimensions:
      - name: QueueName
        value: my_queue_name.fifo
    metrics:
      - name: NumberOfMessagesSent
        statistics:
          - Average
          - Sum
        period: 60
        length: 60
        addCloudwatchTimestamp: true
        nilToZero: true
```

And the exporter displays the metrics, however prometheus (v2.39) doesn't seem to ingest.  I have similar configurations for RDS metrics running which get ingested just fine... but for whatever reason SQS doesn't seem to want to work.

Prometheus config is pretty basic also:
```
- job_name: yace-exporter-prod
  honor_timestamps: true
  scrape_interval: 45s
  metrics_path: /metrics
  static_configs:
    - targets: [ yace:5000 ]
  relabel_configs:
    - source_labels: [job]
      target_label: instance
```

### Expected Behavior

see my config above

### Steps To Reproduce

this is the output of the exporter:
