### ISSUE TITLE
[FEATURE] Documentation Improvement on ALB Targetgroups

### ISSUE THREAD

**Issue by jportasa** [nerdswords/yet-another-cloudwatch-exporter#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I the sense of improving documentation on how to use ALB targetgroups:

Is frecuent to see an ALB shared by multiple app's, so each APP is a different targetgroup.
I want to get metrics from a specific Targetgroup of a specific ALB, filtering targetgroup name by TAG
what would be the configuration?

The ALB TAG is:
 ingress.k8s.aws/stack: web-platform-prpduction

The targetgroup TAG is:
ingress.k8s.aws/resource: production-prd-1-global-tofu/tofu-tofu:80 

### What might the configuration look like?

```
  - type: AWS/ApplicationELB
    regions:
    - us-east-1
    searchTags:
    - key:  ingress.k8s.aws/stack
      value: global-production-external
    statistics:
    - Maximum
    metrics:
    - name: HTTPCode_Target_2XX_Count
      period: 60
      length: 600
```
