### ISSUE TITLE
[BUG] More timestamps returned than expected (length not respected)

### ISSUE THREAD

**Issue by k24dizzle** [nerdswords/yet-another-cloudwatch-exporter#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

arguments:
```
      --config.file=/tmp/config.yml
      --scraping-interval=60
      --debug
```
config:
```
discovery:
  jobs:
  - type: es
    regions:
      - us-west-2
    dimensionNameRequirements:
      - DomainName
      - ClientId
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        - Minimum
        - Maximum
        period: 60
        length: 60


```
Debug Logs:
```
2022/11/01 20:30:31 <GetMetricDataResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <GetMetricDataResult>
    <MetricDataResults>
      <member>
        <Timestamps>
          <member>2022-11-01T20:29:00Z</member>
          <member>2022-11-01T20:28:00Z</member>
          <member>2022-11-01T20:27:00Z</member>
          <member>2022-11-01T20:26:00Z</member>
          <member>2022-11-01T20:25:00Z</member>
        </Timestamps>
        <Values>
          <member>14.5</member>
          <member>7.333333333333333</member>
          <member>6.666666666666667</member>
          <member>6.333333333333333</member>
          <member>11.666666666666666</member>
        </Values>
        <Label>CPUUtilization Average</Label>
```

As a result, the prometheus metrics (for averages) don't match up with what appears in Cloudwatch. this is because I assume the prometheus metric is the average of all the 5 timestamps, instead of returning the most recent timestamp value (which is what I want).

instead of the average of the last 60 seconds, it takes the average of the last 5 timestamps.

I expect this behavior if the length was `300`, but my config is period: 60, length: 60.

### Expected Behavior

```
2022/11/01 20:30:31 <GetMetricDataResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <GetMetricDataResult>
    <MetricDataResults>
      <member>
        <Timestamps>
          <member>2022-11-01T20:29:00Z</member>
        </Timestamps>
        <Values>
          <member>14.5</member>
        </Values>
        <Label>CPUUtilization Average</Label>
```

### Steps To Reproduce

See the config above

### Anything else?

Did I set up the config wrong somewhere? Not sure if this is a bug, or I just misconfigured something

**Comment by k24dizzle** [comment]
```
      - type: es
        regions:
          - us-west-2
        dimensionNameRequirements:
          - DomainName
          - ClientId
        length: 60
        metrics:
          - name: CPUUtilization
            statistics:
            - Average
            - Minimum
            - Maximum
            period: 60
            length: 60
```

This seems to have solved it, not sure why two lengths need to be specified though, and what each one configures
