### ISSUE TITLE
[BUG] Error when found non-ascii tag key on AWS resource

### ISSUE THREAD

**Issue by lprincewhn** [nerdswords/yet-another-cloudwatch-exporter#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Process will panic if non-ascii tag key found. The error is like: 

panic: descriptor Desc{fqName: "aws_rds_info", help: "Help is not implemented yet.", constLabels: {}, variableLabels: []} is invalid: "tag_应用名称" is not a valid label name for metric "aws_rds_info"

### Expected Behavior

Ignore the non-ascii tag key or make it configurable. 

### Steps To Reproduce

1. Add non-ascii tag key in RDS instance of AWS.
2. Use following config file to start yace.
```
apiVersion: v1alpha1
sts-region: eu-west-1
discovery:
  jobs:
  - type: rds
    regions:
      - ap-southeast-1
    metrics:
      - name: CPUUtilization
        statistics:
        - Average
        period: 30
        length: 300
```
