### ISSUE TITLE
[BUG] StartTime equals EndTime for GetMetricData on customNamespace

### ISSUE THREAD

**Issue by ClaudiusMZ** [nerdswords/yet-another-cloudwatch-exporter#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looks like there is an issue with GetMetricData on customNamespace.
No matter what parameters of lenght , delay, period, roundingPeriod I try, start_time & end_time are allways set to the same value.

Most simple config: 

```
customNamespace:
  - name: xxxxx
    namespace: "xxxxx"
    regions:
      - eu-west-1
    period: 60
    metrics:
      - name: xxxxxxx
        statistics:
          - Average
        length: 600
```

Results in: 

"start_time":"2022-11-21T14:57:00+00:00",
"end_time":"2022-11-21T14:57:00+00:00",

-----------------------------------------------------
DEBUG: Response monitoring/GetMetricData Details:
---[ RESPONSE ]--------------------------------------
...
    <Code>ValidationError</Code>
    <Message>The parameter StartTime must not equal parameter EndTime.
</Messag>

### Expected Behavior

lenght is used as expected on customNamespace 

### Steps To Reproduce

see current behavior 

### Anything else?

customNamespace  is not processed at all with latest release https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases/tag/v0.42.0-alpha , although its already documented. 

Described behavior can be reproduced with latest code in master branch (commit 7c7562cd064f708eed26131ed87bffbeedd83792)

**Comment by sandeepnethi** [comment]
I'm also facing the same issue. any workaround for this issue?

**Comment by ClaudiusMZ** [comment]
We analyzed the code and found the problem: 
length on metrics level is not utilized.   it only works at job level with the current code.

```
customNamespace:
  - name: xxxxx
    namespace: "xxxxx"
    regions:
      - eu-west-1
    period: 60
    metrics:
      - name: xxxxxxx
        statistics:
          - Average
        #ignored   
        length: 600
    #used   
    length: 600    
```
