### ISSUE TITLE
[FEATURE] <title>

### ISSUE THREAD

**Issue by lgogolin** [nerdswords/yet-another-cloudwatch-exporter#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add the support to fetch DynamoDB Accelerator (DAX) metrics as presented in [link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/dax-metrics-dimensions-dax.html)

### What might the configuration look like?

```yml
- type: dax
    regions:
      - eu-west-1
    metrics:
      - name: ItemCacheMisses
        statistics:
        - Average
        period: 60
        length: 600
```
