### ISSUE TITLE
[FEATURE] Add instance state to aws_ec2_info

### ISSUE THREAD

**Issue by geekofalltrades** [nerdswords/yet-another-cloudwatch-exporter#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I have an alert combining metrics from YACE and kube-state-metrics that determines whether there are any EC2 instances running that have failed to join the Kubernetes cluster.

```
label_replace(
  aws_ec2_info{tag_kubernetes_io_cluster_my_cluster_name="owned"}
  "instance_id", "$1", "name", "".*/(i-[0-9a-z]*)$""
)
unless on(instance_id)
label_replace(kube_node_info, "instance_id", "$1", "provider_id", ".*/(i-[0-9a-z]*)$")
```

This alert would work great, except that the `aws_ec2_info` series does not reliably stop existing for an EC2 instance when that EC2 instance is terminated. Presumably it sticks around until all metrics related to the instance expire, or something?

To work around this, I also set up configuration for `aws_ec2_status_check_failed_maximum`. This metric tends to become NaN when the instance is terminated, and then I can filter out the NaN by comparing the series to itself, since NaN != NaN in Prometheus. So I can adjust the query to something like this:

```
label_replace(
  aws_ec2_info{tag_kubernetes_io_cluster_${replace(eks_cluster_name, "-", "_")}="owned"}
  + on (name) group_left(dimension_InstanceId) (
    aws_ec2_status_check_failed_maximum{display_endpoint="yace"} ==
    aws_ec2_status_check_failed_maximum
  ),
  "instance_id", "$1", "dimension_InstanceId", "(.*)"
)
unless on(instance_id)
label_replace(kube_node_info, "instance_id", "$1", "provider_id", ".*/(i-[0-9a-z]*)$")
```

This is better, but the point at which `aws_ec2_status_check_failed_maximum` becomes NaN is also not very consistent. So I end up having a very long `for` period on this alert configuration and hoping that the metrics get into the right state before I get any false positives.

One way to remedy this could be to include the instance state as a label in the `aws_ec2_info` metric, and not export the metric except when the instance is in that state. Then I could filter my alert with `aws_ec2_info{state="running", ...}`.

I haven't found other ways to determine just from cloudwatch metrics/this exporter whether an EC2 instance is actually running, but if there are other suggestions, I'm happy to consider them.

### What might the configuration look like?

```yml
# Just to generate the aws_ec2_info metric:
discovery:
  jobs:
    - type: ec2
      dimensionNameRequirements:
        - InstanceId
      period: 60
      regions:
        - us-west-2 # or any
      searchTags:
        - key: Name # use any tag
          value: foo
      metrics:
        - name: StatusCheckFailed
          statistics:
            - Maximum
```

### Anything else?

The pattern of joining in `aws_ec2_status_check_failed_maximum` is one I brought over from cloudwatch-exporter when I switched. cloudwatch-exporter would stop exporting the metric for terminated instances, rather than going NaN. I'm not sure why _any_ metrics are being exported with NaN values, but that's a different issue.
