### ISSUE TITLE
[FEATURE] Add support for RDS Enhanced Monitoring

### ISSUE THREAD

**Issue by zunkree** [nerdswords/yet-another-cloudwatch-exporter#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add support to fetch AWS RDS Enhanced Monitoring metrics.

### What might the configuration look like?

```yml
discovery:
  jobs:
  - type: rds-enhanced
    period: 30
    length: 600
    metrics:
    - name: SomeExportedMetric
      statistics: [Minimum, Maximum]
```
