### ISSUE TITLE
[BUG] AWS SES resource cant have TAG assigned, so is not scraped anymore

### ISSUE THREAD

**Issue by marekhanzlik** [nerdswords/yet-another-cloudwatch-exporter#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS SES metrics are not scraped anymore, because they do not contain any TAG, but you can't assign tags to SES

### Expected Behavior

Should scrape SES anyway, even without tags

### Anything else?

`v3.36.1-alpha` was last that version was working  
i suppose it was caused by 
```
Return early if no tagged resources are found. by @cristiangreco in https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/606
```
that was merged in version `v3.36.2-alpha`

**Comment by abualy** [comment]
this is broken for us too now! looking forward for the fix to be merged!

**Comment by cristiangreco** [comment]
@marekhanzlik @abualy thanks for the bug report.

Even though ses metrics are not fetched with discovery jobs, you can still use a static job, e.g.

```yaml
apiVersion: v1alpha1
static:
- name: ses
  namespace: AWS/SES
  regions:
    - eu-west-3
  metrics:
    - name: Send
      statistics:
        - Sum
      period: 60
      length: 600
      nilToZero: true
    - name: Reputation.ComplaintRate
      statistics:
        - Sum
      period: 60
      length: 600
      nilToZero: true
    - name: Reputation.BounceRate
      statistics:
        - Sum
      period: 60
      length: 600
      nilToZero: true
    - name: Delivery
      statistics:
        - Sum
      period: 60
      length: 600
      nilToZero: true
    - name: Bounce
      statistics:
        - Sum
      period: 60
      length: 600
      nilToZero: true
```

Does this work for you?
