### ISSUE TITLE
EC2 are not filtred 

### ISSUE THREAD

**Issue by AssiremLoualia** [nerdswords/yet-another-cloudwatch-exporter#745]
Hi, 

I'm stucking with the result I get when I run the EC2 metrics, when I apply filters it bring like all the EC2 of my region and not the ones I've specified in the filter searchTags.
this is my conf with the helm chart : 
 

>  apiVersion: v1alpha1
>   sts-region: eu-west-3
>   discovery:
>     exportedTagsOnMetrics:
>       ec2:
>         - testag
>         - aws:eks:cluster-name
>         - aws:autoscaling:groupName
>         - Vpcid
>         - eks:nodegroup-name
>     jobs:
>     - type: ec2
>       regions:
>         - eu-west-3
>       enableMetricData: true
>       awsDimensions:
>         - AutoScalingGroupName
>       searchTags:
>         - key: testag
>           value: ala
>       metrics:
>         - name: CPUUtilization    
>           statistics:
>           - Average
>           period: 300
>           length: 300
>           nilToZero: true
> 

I tried many configuration but the result is always the same. I saw that issue was fixed but it seems that the problem persists for me (I'm using the helm chart from the master branch) 

thanks

**Comment by cristiangreco** [comment]
Hi @AssiremLoualia thanks for reporting this. I see your config mentions a search tag with key `testag` and value `ala`. I assume you have ec2 instances in your account with that exact tag name and value, correct? Do they appear in the results together with the rest of ec2 instances?

**Comment by cristiangreco** [comment]
Closing for lack of information, but feel free to re-open if you're still having problems.

**Comment by AssiremLoualia** [comment]
Hi, 
Sorry for my late answer, of course I have EC2 with that exact tag name and value. 
Yes they appear in the result, but this result is randomly showing all other EC2 that are not part of filter. 
This bug is still persistent can you please keep this issue open. 
For now we are putting on hold the integration of YACE, because all of those filters are not working and we are getting a lot of inconsistent data with YACE.
Any help is welcome. 

Thanks a lot

**Comment by AssiremLoualia** [comment]
Hi @cristiangrecon, 

I've tested with  v0.51.0  and it works fine now with dimensionNameRequirements parameter. 

thanks a lot
Here is the config that works fin : 
`  apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      ec2:
        - cluster-name
    jobs:
    - type: AWS/EC2
      regions:
        - us-east-1
      searchTags:
        - key: cluster-name
          value: test
      dimensionNameRequirements:
        - InstanceId
      metrics:
        - name: CPUUtilization    
          statistics:
          - Average
          period: 300
          length: 300
          nilToZero: `true``

**Comment by cristiangreco** [comment]
@AssiremLoualia thanks for the feedback. When you say

>  it works fine now with dimensionNameRequirements parameter

Does it _only_ work with `dimensionNameRequirements` (and is it broken otherwise) or do you specifically need that parameter for something?

**Comment by theodrim** [comment]
Hello, seems we have a similar issue. Using yace version v0.51.0 and having following configuration:
```
apiVersion: v1alpha1
sts-region: eu-west-1
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
      - Component

  jobs:
  - type: "ec2"
    regions:
      - eu-west-1
    searchTags:
      - key: Environment
        value: integration
      - key: Component
        value: sensu
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
        period: 60
        length: 360
```

pulling all of available ec2 instainces CPUUtilization metrics, instead of only one with matching tags. Anything we can do to reduce amount of data pulled and narrow it down only for our filters @cristiangreco ?
