### ISSUE TITLE
Directory Service metrics not supported

### ISSUE THREAD

**Issue by wkneewalden** [nerdswords/yet-another-cloudwatch-exporter#757]
AWS/DirectoryService metrics are not supported in tag discovery. Tested using custom namespace with the following config:

```
customNamespace:
  - name: aws_directoryservice
    namespace: AWS/DirectoryService
    regions:
      - us-east-1
    metrics:
      - name: "% Processor Time"
        statistics:
          - Average
        period: 120
        length: 600
      - name: Avg. Disk Queue Length
        statistics:
          - Average
        period: 120
        length: 600
      - name: "% Free Space"
        statistics:
          - Average
        period: 120
        length: 600
      - name: "% Committed Bytes in Use"
        statistics:
          - Average
        period: 120
        length: 600
```

No tagging available for Directory Service resources.

**Comment by wkneewalden** [comment]
Solution:

```
customNamespace:
  - name: aws_directoryservice
    namespace: AWS/DirectoryService
    regions:
      - us-east-1
    period: 120
    length: 600
    nilToZero: false
    metrics:
      - name: "% Processor Time"
        statistics:
          - Average
      - name: Avg. Disk Queue Length
        statistics:
          - Average
      - name: "% Free Space"
        statistics:
          - Average
      - name: "% Committed Bytes in Use"
        statistics:
          - Average
```
