### ISSUE TITLE
[FEATURE] Using Service account

### ISSUE THREAD

**Issue by lidora-everc** [nerdswords/yet-another-cloudwatch-exporter#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

How to specify service account?
i try as following but not work.

### What might the configuration look like?

```yaml
serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::937712594651:role/everc-cloudwatch-exporter-role
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
```
