### ISSUE TITLE
[FEATURE] Service Account Roles ( IRSA ) in Non-EKS clusters

### ISSUE THREAD

**Issue by tareqhs** [nerdswords/yet-another-cloudwatch-exporter#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,

Looks like the current chart does not allow the customizations that are necessary for using service account roles in non-EKS clusters, or cluster that do not run the pod identity webhook in general. These customizations are needed to achieve this:
1. custom env vars
2. custom volumes
3. custom volume mounts

And then the deployment template takes care of putting each block where it belongs. (not including here for simplicity)

This allows authentication from any kubernetes cluster, regardless of the vendor setup.

### What might the configuration look like?

```yml
extraEnvVars:
  AWS_ROLE_ARN: arn:aws:iam::<myaccount>:role/<myrole>
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/<mysa>/serviceaccount/token
extraVolumeMounts:
- name: <mysa>
  mountPath: /var/run/secrets/<mysa>/serviceaccount
  readOnly: true
extraVolumes:
- name: <mysa>
  projected:
    sources:
    - serviceAccountToken:
        audience: <myaud>
        expirationSeconds: 3600
        path: token
```
