### ISSUE TITLE
[BUG] searchTags not working

### ISSUE THREAD

**Issue by saharmethneni** [nerdswords/yet-another-cloudwatch-exporter#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In order to filter our aws_apigateway metrics, we used searchTags with the "Owner" key which is a specific tag we created:
```yaml
 searchTags:
        - key: Owner
        - value: team1
```
and it doesn't work; filter not working because metrics for all teams appeared

### Expected Behavior

We expect only team1 metrics to appear as configured on searchTags

### Steps To Reproduce

```yaml
discovery:
  exportedTagsOnMetrics:
    apigateway:
      - Owner
      - CostCenter
  jobs:
    - type: apigateway
      dimensionNameRequirements:
        - ApiName
        - Method
        - Resource
        - Stage
      regions:
        - eu-central-1
      searchTags:
        - key: tag_Owner
        - value: team1
     enableMetricData: true
      period: 60
      length: 600
      statistics:
        - Average
        - Maximum
        - Minimum
        - Sum
        - SampleCount
        - Average
      metrics:
        - name: Latency
        - name: IntegrationLatency
        - name: Count
        - name: CacheMissCount
        - name: CacheHitCount
        - name: 5XXError
        - name: 4XXError

```

**Comment by cristiangreco** [comment]
@saharmethneni you can validate your config file with this command:

```
$ yace verify-config -config.file config.yml
```

The config you pasted contains 3 errors:
- `searchTags` must be a list of objects, each one with a `key` and `value` field (you are using `- key` and `- value`)
- `enableMetricData` is wrongly aligned and anyway it's a config field that doesn't exist anymore
- you're missing `apiVersion`

This is the corrected version of your config:
```yaml
apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    apigateway:
      - Owner
      - CostCenter
  jobs:
    - type: apigateway
      dimensionNameRequirements:
        - ApiName
        - Method
        - Resource
        - Stage
      regions:
        - eu-central-1
      searchTags:
        - key: tag_Owner
          value: team1
      period: 60
      length: 600
      statistics:
        - Average
        - Maximum
        - Minimum
        - Sum
        - SampleCount
        - Average
      metrics:
        - name: Latency
        - name: IntegrationLatency
        - name: Count
        - name: CacheMissCount
        - name: CacheHitCount
        - name: 5XXError
        - name: 4XXError
```
