### ISSUE TITLE
[BUG] Metrics are not scrapped via Cross Account role

### ISSUE THREAD

**Issue by mykhailoshevchenko** [nerdswords/yet-another-cloudwatch-exporter#790]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

No metrics are scrapping via cross-account role. 

All messages in logs looks like following:

```

      {
        "account":"account_A",
        "arn":"",
        "error":"resource tag list is empty",
        "job_type":"alb",
        "level":"error",
        "msg":"Account contained no tagged resource. Tags must be defined for resources to be discovered.",
        "region":"us-east-2",
        "time":"2023-02-02T10:53:26Z"
      }

```

Config is next:
```
  - type: alb
    regions:
      - us-east-2
    roleArn: "arn:aws:iam::account_B:role/CrossAccount-Monitoring-Role"
    searchTags:
      - Key: monitor 
        Value: true
    metrics:
     *metrics*
```

Account_A - is monitoring account where fargate monitoring cluster with yace is located
Account_B - is monitored account

That config perfectly works on 0.18.0-alpha, but not on 0.43-45.0-alpha

### Expected Behavior

Metrics are scraped via Cross Account role

### Steps To Reproduce

Just use cross account role for metrics scrapping on version 0.43.0, 0.44.0, 0.45.0 and maybe on some earlier versions

**Comment by cristiangreco** [comment]
@mykhailoshevchenko  The configuration has evolved over time with breaking changes.

You can validate your config file with this command:

```
$ yace verify-config -config.file config.yml
```

Using `verify-config` you can look at errors and fix them one by one. 

Something wrong I can already see in the snippet you pasted:

1. Role must be specified like this:

```yaml
roles:
  - roleArn: ...
```

2. Use lowercase letters for search tags:

```yaml
searchTags:
  - key: monitor 
    value: true
```

3. It is recommended to specify `apiVersion` at the top:

```yaml
apiVersion: v1alpha1
discovery:
  jobs:
```
