### ISSUE TITLE
Include Metrics for AWS  ActiveMQ broker in "active/standby" setup

### ISSUE THREAD

**Issue by saurabhgcect** [nerdswords/yet-another-cloudwatch-exporter#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is it possible to add feature to get metrics  that belong to the active vs standby hosts of AWS  ActiveMQ broker.

### What might the configuration look like?

```
discovery:
  jobs:
  - type: AWS/AmazonMQ
    roles:
      - roleArn: "arn:aws:iam::xxx:role/xxxx" 
    regions:
      - us-east-1
    addCloudwatchTimestamp: true
    metrics:
      - name: CpuUtilization
        statistics:
        - Average
        period: 300
        length: 300
```
