### ISSUE TITLE
[BUG] Cannot scrape DDOS metrics

### ISSUE THREAD

**Issue by nikitakogan1** [nerdswords/yet-another-cloudwatch-exporter#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, 

I am trying to scrape the metric for ddos protection (DDoSDetected) for my elastic ips. I have the DDOS protection configured in AWS side and i can see the metrics in cloud watch in the needed region.
I also set the "Name" tag in all elastic ips. 

I use the following config:

```

  - type: AWS/DDoSProtection
    regions:
    - eu-central-1
    length: {{ index .Values "extraArgs" "length" }}
    searchTags:
      - key: Name
        value: .*
    metrics:
    - name: DDoSDetected
      dimensions:
        - Name: ResourceArn
          Value: "*"
      statistics:
      - Sum
      period: {{ index .Values "extraArgs" "period" }}
      nilToZero: true

```

But in the logs i see:

{"account":"xxxxxx","arn":"","error":"resource tag list is empty","job_type":"AWS/DDoSProtection","level":"error","msg":"Account contained no tagged resource. Tags must be defined for resources to be discovered.","region":"eu-central-1","time":"2023-02-07T13:41:03Z"}
{"account":"xxxxxx","arn":"","job_type":"AWS/DDoSProtection","level":"info","msg":"No tagged resources made it through filtering","region":"eu-central-1","time":"2023-02-07T13:41:03Z"}

### Expected Behavior

I expected to be able to export the metric for all the elastic Ips with the tag: Name.(All values)

### Steps To Reproduce

1. Create static ip in AWS and add it to ddos protection plan.
2. Inspect that cloudwatch creates the metrics in its side, in the needed region.
3. Try to use the config above and you should get the same log as i get. (Hopefully not, and it is something with my configuration...)

Thanks (:

**Comment by cristiangreco** [comment]
Hi @nikitakogan1, could you maybe run yace with `-debug` and attach the scrubbed output?

**Comment by nikitakogan1** [comment]
@cristiangreco Thanks for the answer. Here is the additional output:

```

{"account":"****","arn":"","level":"debug","msg":"GetMetricStatistics","output":"{\n  Label: \"DDoSDetected\"\n}","region":"eu-central-1","static_job_name":"DDoSDetected","time":"2023-02-07T21:01:55Z"}
{"account":"****","arn":"","level":"debug","msg":"CLI helper - aws cloudwatch get-metric-statistics --metric-name DDoSDetected --dimensions Name=ResourceArn,Value=*  --namespace AWS/DDoSProtection --statistics Maximum --period 60 --start-time 2023-02-07T20:57:53Z --end-time 2023-02-07T21:02:53Z","region":"eu-central-1","static_job_name":"DDoSDetected","time":"2023-02-07T21:02:53Z"}
{"account":"****","arn":"","level":"debug","msg":"createGetMetricStatisticsInput","output":"{\n  Dimensions: [{\n      Name: \"ResourceArn\",\n      Value: \"*\"\n    }],\n  EndTime: 2023-02-07 21:02:53.936021202 +0000 UTC m=+182.993883022,\n  MetricName: \"DDoSDetected\",\n  Namespace: \"AWS/DDoSProtection\",\n  Period: 60,\n  StartTime: 2023-02-07 20:57:53.936021542 +0000 UTC m=-117.006116726,\n  Statistics: [\"Maximum\"]\n}","region":"eu-central-1","static_job_name":"DDoSDetected","time":"2023-02-07T21:02:53Z"}
{"account":"****","arn":"","input":"{\n  Dimensions: [{\n      Name: \"ResourceArn\",\n      Value: \"*\"\n    }],\n  EndTime: 2023-02-07 21:02:53.936021202 +0000 UTC m=+182.993883022,\n  MetricName: \"DDoSDetected\",\n  Namespace: \"AWS/DDoSProtection\",\n  Period: 60,\n  StartTime: 2023-02-07 20:57:53.936021542 +0000 UTC m=-117.006116726,\n  Statistics: [\"Maximum\"]\n}","level":"debug","msg":"GetMetricStatistics","region":"eu-central-1","static_job_name":"DDoSDetected","time":"2023-02-07T21:02:53Z"}
Action=GetMetricStatistics&Dimensions.member.1.Name=ResourceArn&Dimensions.member.1.Value=%2A&EndTime=2023-02-07T21%3A02%3A53.936Z&MetricName=DDoSDetected&Namespace=AWS%2FDDoSProtection&Period=60&StartTime=2023-02-07T20%3A57%3A53.936Z&Statistics.member.1=Maximum&Version=2010-08-01
{"account":"****","arn":"","error":"resource tag list is empty","job_type":"AWS/DDoSProtection","level":"error","msg":"Account contained no tagged resource. Tags must be defined for resources to be discovered.","region":"eu-central-1","time":"2023-02-07T21:02:54Z"}
{"account":"****","arn":"","job_type":"AWS/DDoSProtection","level":"info","msg":"No tagged resources made it through filtering","region":"eu-central-1","time":"2023-02-07T21:02:54Z"}


```

**Comment by cristiangreco** [comment]
@nikitakogan1 what version of Yace are you running? Could you please paste the full config file?

**Comment by nikitakogan1** [comment]
Hi,

I am running version v0.42.0.

My full config.yml file:
```
apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
  - type: AWS/DDoSProtection
    regions:
    - eu-central-1
    length: 60
    searchTags:
    - key: Name
      value: .*
    metrics:
    - name: DDoSDetected
      statistics:
      - Maximum
      period: 60
      nilToZero: true
    - name: DDoSAttackPacketsPerSecond
      statistics:
      - Maximum
      period: 60
      nilToZero: true
    - name: DDoSAttackBitsPerSecond
      statistics:
      - Maximum
      period: 60
      nilToZero: true
```

In AWS side, i have the elastic ips with the needed tags:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/46023717/218268710-cc11f2f7-f794-4551-b838-d6698905e916.png">


Thanks

**Comment by nikitakogan1** [comment]
Update: I was able to make it work for us-esat-1 region. For some reason, the scraping is not working for eu-central-1. (Both regions has the resources with the needed tags).

I was able to use this configuration to scrape the metrics:
```
apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
  - type: AWS/DDoSProtection
    regions:
    - eu-central-1
    - us-east-1
    length: 60
    searchTags: 
    - key: Name
      value: .*
    metrics:
    - name: DDoSDetected
      statistics:
      - Maximum
      period: 60
      nilToZero: true
    - name: DDoSAttackPacketsPerSecond
      statistics:
      - Maximum
      period: 60
      nilToZero: true
    - name: DDoSAttackBitsPerSecond
      statistics:
      - Maximum
      period: 60
      nilToZero: true
```

I still see the same error in the logs for eu-central-1 region. But i see all the metrics for us-east-1.
