### ISSUE TITLE
[BUG] Cannot scrape metrics from ap-southeast-3 region

### ISSUE THREAD

**Issue by orcunuso** [nerdswords/yet-another-cloudwatch-exporter#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to scrape metrics from `ap-southeast-3` region. The following configuration works well for other regions like us-east-1, us-west-2, etc but unfortunately not for ap-southeast-3.

I'm using the following configMap :

```
apiVersion: v1
data:
  config.yaml: |
    apiVersion: v1alpha1
    discovery:
      exportedTagsOnMetrics:
        ec2:
          - Environment
          - Stage
          - Type
      jobs:
        - type: ec2
          length: 300
          period: 300
          addCloudwatchTimestamp: true
          regions:
            - us-east-1
            - ap-southeast-3
          roles:
            - roleArn: "arn:aws:iam::<aws_account_id>:role/<role_name>"
          searchTags:
            - key: Environment
              value: ".*"
          metrics:
            - name: CPUUtilization
              statistics:
                - Average
```

The error message is;
`2023/02/23 06:55:13 {"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid"}`

I run yace pod in debug mode and I spotted that it gets 400 from tagging APIs right after requests to STS APIs.

```
2023/02/23 06:55:12 DEBUG: Request tagging/GetResources Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: tagging.ap-southeast-3.amazonaws.com
User-Agent: aws-sdk-go/1.44.194 (go1.20; linux; amd64)
Content-Length: 63
Authorization: AWS4-HMAC-SHA256 Credential=ASI2COMDED/20230223/ap-southeast-3/tagging/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=<signature>
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20230223T065512Z
X-Amz-Security-Token: <a-valid-looking-security-token-received-from-sts>
X-Amz-Target: ResourceGroupsTaggingAPI_20170126.GetResources
Accept-Encoding: gzip

{"ResourceTypeFilters":["ec2:instance"],"ResourcesPerPage":100}
-----------------------------------------------------
2023/02/23 06:55:13 DEBUG: Response tagging/GetResources Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 106
Content-Type: application/x-amz-json-1.1
Date: Thu, 23 Feb 2023 06:55:13 GMT
X-Amzn-Requestid: 504f5e48-884d-4bc0-bd7a-a2cde4260671
```
Yace version: 0.48.0

### Expected Behavior

I expect to be able to export the metrics from `ap-southeast-3` region like any other region.

### Steps To Reproduce

1. Scrape metrics from `ap-southeast-3` region with a config similar to what is shared in this issue.

### Anything else?

Is it possible that `ap-southeast-3` is not supported with yace?
Yace version: 0.48.0
Thanks.

**Comment by orcunuso** [comment]
I've solved the issue by switching STS endpoint from global to regional with the following environment variables.
```
env:
- name: AWS_STS_REGIONAL_ENDPOINTS
  value: regional
- name: AWS_DEFAULT_REGION
  value: ap-southeast-3
- name: AWS_REGION
  value: ap-southeast-3
```
Closing the issue.
