### ISSUE TITLE
[BUG] Add AWS Dimensions as Labels for Static Configuration

### ISSUE THREAD

**Issue by Xalphor** [nerdswords/yet-another-cloudwatch-exporter#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to Export the AWS/RDS EBSByteBalance% Metric. Right now my configuration looks like this:

```yaml
  static:
    - namespace: AWS/RDS
      name: aws_rds_byte_balance_percent 
      dimensions:
        - name: DBInstanceIdentifier
          value: qa
      regions:
        - eu-central-1
      metrics:
        - name: EBSByteBalance% 
          statistics:
            - 'Average'
          period: 300
          length: 3600
```

This results in a metric getting correctly scraped:

```sh
# HELP aws_rds_ebsbyte_balance_percent_average Help is not implemented yet.
# TYPE aws_rds_ebsbyte_balance_percent_average gauge
aws_rds_ebsbyte_balance_percent_average{account_id="<my-account-id>",dimension_DBInstanceIdentifier="qa",name="aws_rds_byte_balance_percent",region="eu-central-1"} 99
```
But I want to just add the `DBInstanceIdentifier` as a Label to my metric, instead of using it as a filter.

In Grafana+CloudWatch what I want looks like this:

![image](https://user-images.githubusercontent.com/49435535/222480451-0244518c-8af1-409f-940e-47ef57a4e95e.png)

I tried using `value: \*`, but with that the metric doesn't get exported at all. (Probably because there is no DB with such a Identifier) 

### Expected Behavior

It would be great to have a configuration like this:

```yaml
  static:
    - namespace: AWS/RDS
      name: aws_rds_byte_balance_percent 
      dimensions:
        - name: DBInstanceIdentifier
          value: *
      regions:
        - eu-central-1
      metrics:
        - name: EBSByteBalance% 
          statistics:
            - 'Average'
          period: 300
          length: 3600
```

result in a metric where the `DBInstanceIdentifier` dimension is just added as a label while scraping all DBs. 

I am 99.8% sure that what I want is possible with the right configuration. But I read the documentation multiple times w/o finding a hint to what I am doing wrong. Maybe someone can help and improve the docs a bit?

Thanks in advance; :)
