### ISSUE TITLE
Static mode - How to use multiple values in dimensions

### ISSUE THREAD

**Issue by agarciahumanes** [nerdswords/yet-another-cloudwatch-exporter#841]
Hello there, i'm trying to get a few metrics with yace, it's working, but i'm not sure how to apply configuration properly:

Let's say I have yace on my cluster, with 2 different LoadBalancers, each of them with 2 TargetGroups

So when it comes to this:

```
- namespace: AWS/NetworkELB
          name: healthy_host_count
          regions:
            - us-west-2
          dimensions:
          - name: LoadBalancer
            value: net/LB1
          - name: TargetGroup
            value: targetgroup/TG1
```

for ex, that will retrieve the metric just for that case. Is there any way for yace to admit multiple values for each dimension on static mode? Like having LB1 and LB2 and TG1-4, so in case it matches any case like LB1+TG1 or LB2+TG4 I will get the metric. Or will i need to create a new metric for each pair or them?
