### ISSUE TITLE
[FEATURE] Add support for AWS/MemoryDB metrics

### ISSUE THREAD

**Issue by ddotafonso** [nerdswords/yet-another-cloudwatch-exporter#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add the support to fetch MemoryDB and its host-level metrics as presented in:
[Metrics for MemoryDB
](https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.memorydb.html)
[Host-Level Metrics](https://docs.aws.amazon.com/memorydb/latest/devguide/metrics.HostLevel.html)

### What might the configuration look like?

```
- type: memorydb
    regions:
      - eu-west-1
    metrics:
      - name: ActiveDefragHits
        statistics:
        - Average
        period: 60
        length: 600
```
