### ISSUE TITLE
exportedTagsOnMetrics only works for a AWS resource which has Tags ( Array of Dictionary ) but not for a resource with Tags ( A Dictionary ).

### ISSUE THREAD

**Issue by gouthamssc** [nerdswords/yet-another-cloudwatch-exporter#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we are using YACE exporter to get metrics from MWAA namespace we aren't able to get the tags for the resource to filter further.

```
data:
  config.yml: |
    apiVersion: v1alpha1
    sts-region: us-east-1
    discovery:
      exportedTagsOnMetrics:
        redshift:
          - Environment
          - BusinessUnit
        airflow:
          - Environment
          - BusinessUnit
      jobs:
      - type: airflow
        regions:
          - us-east-1
        dimensionNameRequirements:
          - DAG
          - Environment
          - State
          - Task
        metrics:
          - name: TaskInstanceFinished
            statistics:
            - Average
      - type: redshift
        regions:
          - us-east-1
        dimensionNameRequirements:
          - ClusterIdentifier
          - Database
          - Schema
        metrics:
          - name: PercentageQuotaUsed
            statistics:
            - Average
          - name: StorageUsed
            statistics:
            - Average
```

Above is my configuration to get metrics from redshift and airflow along with tags i.e **Environment** & **BusinessUnit**.
But I'm able to get tags for redshift metrics _**but not for airflow**_.

When i debugged further using the below commands i got to know that

`aws redshift describe-clusters --cluster-identifier reshift-sandbox --output json  >> redshift.json`
`aws mwaa get-environment --name mwaa-poc  >> mwaa.json`

Redshift resource has Tags listed as _Array of Dictionaries_ where as airflow resource has tags listed as a _single Dictionary_ i.e.

Redshift Tags:
```
        "Tags": [
                {
                    "Key": "SysName",
                    "Value": "Redshift"
                },
                {
                    "Key": "BusinessUnit",
                    "Value": "IT"
                },
                {
                    "Key": "Environment",
                    "Value": "POC"
                }
            ]
```

Airflow Tags:

```
        "Tags": {
            "SysName": "Airflow",
            "BusinessUnit": "IT",
            "Environment": "POC"
        },
```

when i checked the GoLang code YACE, i got to know that Tags are defined as Array Datatype.

### Expected Behavior

Automatic discovery of Tags should work for all the AWS resources even its Tags are of type single dictionary.

### Steps To Reproduce

Try to use this config to get the metrics for Airflow.

```
data:
  config.yml: |
    apiVersion: v1alpha1
    sts-region: us-east-1
    discovery:
      exportedTagsOnMetrics:
        redshift:
          - Environment
          - BusinessUnit
      jobs:
      - type: airflow
        regions:
          - us-east-1
        dimensionNameRequirements:
          - DAG
          - Environment
          - State
          - Task
        metrics:
          - name: TaskInstanceFinished
            statistics:
            - Average
      - type: redshift
        regions:
          - us-east-1
        dimensionNameRequirements:
          - ClusterIdentifier
          - Database
          - Schema
        metrics:
          - name: PercentageQuotaUsed
            statistics:
            - Average
          - name: StorageUsed
            statistics:
            - Average
```

Try to check whether auto discovery tags i.e Environment, BusinessUnit works for Airflow and Redshift Metrics.
