### ISSUE TITLE
[FEATURE] Allow filtering ListMetrics results by labels

### ISSUE THREAD

**Issue by joaopccosta** [nerdswords/yet-another-cloudwatch-exporter#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The AWS Observability Access Management(`oam`) allows one to define a central account onto which all metrics/logs/traces can be sinked into. This account is referred to as the monitoring account, whereas all data source accounts are referred to as source accounts.
​
There is another [open issue](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/861#issuecomment-1506729266) where the account linking from `oam` is discussed so that metrics that fit this scenario can indeed be scraped by `yace`.
​
Whenever using `oam`, metrics from resources that are external to the monitoring account are pushed, being accessible from that point on thanks to a dimensions such as the `account_id`.
​
It would be great to be able to filter the results of `ListMetrics` by labels - with something like `searchLabels`, like:

### What might the configuration look like?

```yaml
apiVersion: v1alpha1
sts-region: eu-west-1
discovery:
  includeLinkedAccounts: true # See issue link above
  jobs:
    - regions:
        - eu-west-1
      type: lambda
      searchLabels:
        - key: account_id
          value: .* # some regex pattern
      metrics:
        - name: Duration
          statistics:
            - Sum
```

### Anything else?

On top of this, the `searchTags` feature will not work properly since the resources themselves do not lie within the monitoring account. So you can list the metrics, but you can not get the metric data based on certain tags as the resources live elsewhere.
