### ISSUE TITLE
sagemaker support

### ISSUE THREAD

**Issue by runesl** [nerdswords/yet-another-cloudwatch-exporter#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Today a `customNamepace` is required to gather sagemaker stats, which is giving an annoying log message every minute.

Please add native support for `type: sagemaker`.

`namespace: AWS/Sagemaker `

### What might the configuration look like?

```
  - type: sagemaker
    length: 300
    period: 300
    regions:
      - eu-north-1
    metrics:
      - name: ExecutionSucceeded
        statistics:
        - Sum
```
