### ISSUE TITLE
[BUG] metric name building is changed since v0.51.0 is it intended?

### ISSUE THREAD

**Issue by gavin-jeong** [nerdswords/yet-another-cloudwatch-exporter#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.51.0

### Config file

```yaml
    apiVersion: v1alpha1
    discovery:
      - type: AWS/ElastiCache
        regions:
          - ap-northeast-2
        period: 300
        length: 300
        dimensionNameRequirements:
          - CacheClusterId
          - CacheNodeId
        metrics:
          - name: CPUUtilization
            statistics: [Average]
```

### Current Behavior

It builds metrics `aws_elasti_cache_cpuutilization_average`

### Expected Behavior

Before v0.51.0 it builds `aws_elasticache_cpuutilization_average`

### Steps To Reproduce

Just run the configuration and compare

### Anything else?

Seems using PromString in the PR https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/885 makes this change

**Comment by cristiangreco** [comment]
@gavin-jeong thanks for reporting this, I can confirm this is an unintended behaviour. Will look into a fix today.

**Comment by gavin-jeong** [comment]
Yap it would better just to make it lowercase before putting it PromString()
And Can I request one more
Seems when we use sagemaker it creates CW metrics with custom namespace `/aws/sagemaker/Endpoints`
For this case I could use customNamespace like the below but it would build metric ugly

```yaml
apiVersion: v1alpha1
discovery:
customNamespace:
  - name: sagemaker_custom
    namespace: /aws/sagemaker/Endpoints
    regions:
      - ap-northeast-2
    metrics:
      - name: CPUUtilization
        statistics: [Average]
        period: 300
        length: 300
        nilToZero: true
      - name: MemoryUtilization
        statistics: [Average]
        period: 300
        length: 300
        nilToZero: true
      - name: DiskUtilization
        statistics: [Average]
        period: 300
        length: 300
        nilToZero: true

```
