### ISSUE TITLE
[BUG] AmazonMQ exportedTagOnMetrics doesn't append tags

### ISSUE THREAD

**Issue by RetroJumper** [nerdswords/yet-another-cloudwatch-exporter#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/912 version based on this fix used

### Config file

```
config: |-
  apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      mq:
        - "custom:brokertag" # how it shows up in AWS console, tried without string quotes and with variations of how it shows up in amazon_mq_info metric
        - "tag_custom_brokertag"
        - "custom_brokertag"
    jobs:
      - type: AWS/AmazonMQ
        roles:
          - roleArn: "arn:aws:iam::XXXX:account"
        regions:
          - us-east-1
        period: 60
        length: 60
        nilToZero: true
        statistics: [Minimum, Maximum, Average]
        metrics:
          - name: QueueSize
          - name: ConsumerCount
          - name: ProducerCount
          - name: EnqueueTime
          - name: EnqueueCount
          - name: DequeueCount
          - name: InFlightCount
```

### Current Behavior

Missing tag in all other metrics, however on aws_amazon_mq_info metric only that tag is there even when exportedTagOnMetrics not used:
`aws_amazon_mq_info{ default_tags: XXXXX, tag_custom_brokertag: XXXXX}`

### Expected Behavior

Expected Value in prometheus:
`aws_amazon_mq_queue_size_maximum{ default_tags: XXXX, tag_custom_brokertag: XXXXX}`

### Anything else?

Is this because the tags are only associated to the broker for amazonMQ in cloudwatch? or are we not calling the right name?

**Comment by xantrix** [comment]
I had the exact same issue, but using `rds` key in `exportedTagsOnMetrics`.
Fixed using service namespace so `AWS/RDS` instead 
Full snippet:
```
config: |-
  apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      AWS/RDS:
        - k8s.mytag.io/db/scope
```
And now the tag is also present in all metrics, e.g. `aws_rds_database_connections_sum`

I'm wondering if the service aliases are still working as reported in the config or we must use namespaces
https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/docs/configuration.md#exported_tags_config
cc @cristiangreco
