### ISSUE TITLE
[BUG] EC2 Metrics not being scraped

### ISSUE THREAD

**Issue by felipedds** [nerdswords/yet-another-cloudwatch-exporter#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

{"level":"info","msg":"Yace startup completed","time":"2023-05-29T14:59:10Z","version":"v0.51.0"}

### Config file

```
config: |-
      apiVersion: v1alpha1
      discovery:
        jobs:
          - type: AWS/EC2
            regions:
              - eu-west-1
            searchTags:
              - key: Name
                value: staging-win-maker
            metrics:
              - name: CPUUtilization
                statistics: 
                  - Average
                period: 60
                length: 600
```

### Current Behavior

I am trying to scrape the metrics from service EC2 but no metrics are being exhibited and in the Grafana the metrics don't appear as well. I have been attempting some configuration variations following the documentation and examples but without success. Always the YACE is started but doesn't execute the scrape therefore I don't see any information about the scrape.

My logs when I consult the pod:
```
kubectl logs yace-cloudwatch-exporter-6c79cd44cb-2g5
{"level":"info","msg":"Parsing config","time":"2023-05-29T14:59:10Z"}
{"level":"info","msg":"Yace startup completed","time":"2023-05-29T14:59:10Z","version":"v0.51.0"}
```

### Expected Behavior

I expected to see some information about metrics in logs and that scrapes occur.

### Anything else?

I followed these links:
https://github.com/nerdswords/yet-another-cloudwatch-exporter
https://github.com/nerdswords/helm-charts/blob/main/charts/yet-another-cloudwatch-exporter/values.yaml
https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/examples/ec2.yml
