### ISSUE TITLE
[FEATURE] Don't remove `customNamespace` support

### ISSUE THREAD

**Issue by necaris** [nerdswords/yet-another-cloudwatch-exporter#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Per the CHANGELOG for v0.51.0, `customNamespace` jobs are deprecated -- however, at Materialize we're using them in production to monitor our CockroachDB setup -- see https://www.cockroachlabs.com/docs/cockroachcloud/export-metrics for this.

If there's another (better?) way to configure this, please let us know -- otherwise we'll continue to need `customNamespace` jobs.

### What might the configuration look like?

```yml
customNamespace:
  name: Cockroach
  namespace: crdb-metrics
  regions: 
    - us-east-1
  metrics:
    ...
```

**Comment by mhester-nutrien** [comment]
The above `static` configuration has stopped collecting metrics after a separate configuration update. Returning the config to the previously functioning commit did not work and it is still not collecting custom namespace metrics with a `static` job config.  I have tried everything I can think of, turned on debug logging, and to no avail. Something strange is going on.

**Comment by okummer** [comment]
I support the request by @necaris. The customNamespace option is very useful, because it allows to collect metrics for multiple dimension values at once without having to configure the individual values.

We use this to collect heath check data for multiple services that are not known by the central monitoring server. We add a dimension "service" to the custom AWS metric, which is represented in Prometheus as the label "dimension_service". We can then define a central alert that is raised whenever one of the services reports unhealthy. The exact service that is unhealthy can be determined from the Prometheus label, if needed.

To replicate this using a static job would mean to define one job for each service, which is redundant and might lead to inconsistencies, if one forgets to update the scrape configuration.

**Comment by tkummer33** [comment]
I also second what @necaris and @okummer wrote. The custom namespaces are the only way to get the metrics without auto discovery in somewhat dynamic way. Our current setups rely on this feature.

**Comment by cristiangreco** [comment]
Thanks everybody for the feedback here. I think we're going to revert the decision on deprecating `customNamespace` support, but leaving this open for now in case anybody else has something to say.

**Comment by z0rc** [comment]
I'm using cloudwatch metric filter to generate additional metrics from logs. https://repost.aws/knowledge-center/custom-cloudwatch-metrics-rds. New metrics recorded in custom namespace. I'm using YACE customNamespace to discover those metrics automatically, without specifying dimension values for each database, like this:
```yaml
customNamespace:
- name: rds_os
  namespace: RDSOSMetrics
  regions:
  - us-east-1
  period: 60
  length: 60
  dimensionNameRequirements:
  - DBInstanceIdentifier
  - FileSysMountPoint
  nilToZero: true
  metrics:
  - name: FileSystemUsed
    statistics:
    - Maximum
  - name: FileSystemTotal
    statistics:
 
```
I wasn't able to migrate this configuration to `static`, it requires specifying dimension values, which in my case can change dynamically over time without my control. Am I missing something? Maybe `customNamespace` can be integrated into `discovery`?
