### ISSUE TITLE
[FEATURE] EventBridge Support in Auto-discovery

### ISSUE THREAD

**Issue by hbjydev** [nerdswords/yet-another-cloudwatch-exporter#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like to see metrics for things like EventBridge buses and rules added to the auto-discovery, it'd be a big help. :)

### What might the configuration look like?

```yml
discovery:
  jobs:
  - type: AWS/Events
    period: 60
    length: 600
    metrics:
    - name: Events
      statistics: [Sum]
    - name: FailedInvocations
      statistics: [Sum]
    - name: Invocations
      statistics: [Sum]
    - name: FailedInvocations
      statistics: [Sum]
    - name: MatchedEvents
      statistics: [Sum]
    - name: TriggeredRules
      statistics: [Sum]
```

### Anything else?

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-monitoring.html#eb-metrics-dimensions
