### ISSUE TITLE
[BUG] ALB ConsumedLCUs metric is irregular/inconsistent

### ISSUE THREAD

**Issue by azadsagar** [nerdswords/yet-another-cloudwatch-exporter#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.49.2

### Config file

```
          - type: alb
            regions:
              - us-east-1
            roles:
              - roleArn: "cross_account_role"
            searchTags:
              - key: environment
                value: .*
            customTags:
              - key: aws_account
                value: ###########
            addCloudwatchTimestamp: true
            length: 300
              - name: ConsumedLCUs
                length: 3600
                period: 300
                delay: 2400
                statistics:
                  - Sum
```

### Current Behavior

Metrics are reported inconsistently for ConsumedLCUs. This metric is available in Cloudwatch and I know that this metric is available after 1 hour ( not exactly, but somewhat 40 mins with observations).
If I hit on `/metrics` endpoint, datapoints are unavailable. Sometimes they apears after an hour or after 50 mins (very irregular behaviour), that too with just 6 data points.
I adjusted length to 3600 (1 hour) and period to 5 mins, delay 2400 (40 mins). We use grafana-agent in the cluster to scrape the metrics. All other ALB metris like `ActiveConnectionCount` are reported without any hiccups.

### Expected Behavior

ConsumedLCUs metrics should be available on /metrics endpoint as soon as they are available in the Cloudwatch.

### Steps To Reproduce

Refer the config file.

### Anything else?

![Screenshot 2023-06-08 at 7 21 07 PM](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/8531843/7a0fe4f4-4e7b-4d4d-8ab9-7dd476dd73e2)
